### ISSUE TITLE
Make sure the immutable tag work as expected after introducing the OCI work

### ISSUE THREAD

**Issue by ywk253100** [goharbor/harbor#10067]
- [ ] Refactor the logic about sharing-digest tags

**Comment by xaleeks** [comment]
is the locking mechanism still operating at the tag level?  Since indexes can be recursive in nature, do we only support locking at the tag or the highest index level, and this propagates down to everything it references?  do you need a detailed story around this? @ywk253100 

@lweitzman  possible UI refactor needed here

**Comment by wy65701436** [comment]
this could be closed as PR merged.
