### ISSUE TITLE
[Feature] Harbor as pull through cache for private docker registry

### ISSUE THREAD

**Issue by pgkulkarn** [goharbor/harbor#10084]
We are planning to setup Harbor as private container registry. I understand that that it currently supports local cache only for Docker Hub.
Is it possible that I can setup cache for another private registry?
https://github.com/goharbor/harbor/blob/master/contrib/Configure_mirror.md

E.g. 
Harbor as a private registry at "my.company.com"
I would like to setup local pull through cache for above private registry (and not for Central Hub)
Thank you!

**Comment by dawidmalina** [comment]
We would also love to see such improvement. Basically what we are looking for is ability to create repository which will allow us to fetch images based on configured registry endpoint and store it in the local cache. Ideally if we could still use scaning features.

**Comment by xaleeks** [comment]
'I understand that that it currently supports local cache only for Docker Hub.' this is due to implementation of docker distribution, actually it supports local cache for anything that uses docker registry, so technically it can proxy for another harbor instance for example.  I'd like to learn more about your use case, is this acting as a pure pull through cache or is it doing other things, will things be pushed to this local cache ever.  How many other hosts are pulling from this cache.  @pgkulkarn @dawidmalina

**Comment by dawidmalina** [comment]
We have main docker registry in our premise and have a number of proxies in satellite data centers or cloud deployments. What we need is to have more sophisticated proxy with local cache in case of network (vpn connectivity) issues. On the other hand we don't need to have all images in each of the satellite registry that's why full synchronisation is not an option. Basically if image is needed in dedicated satellite environment this image should be fetched from the central place and store in the local cache. What i need is to have all features which harbor provides like security scanning, user management, etc. I don't need to mix images so for me it can be a new dedicated type of the proxy - probably even don't need to have local repository in this case.
