### ISSUE TITLE
Deleting images from harbor does not delete from s3 bucket

### ISSUE THREAD

**Issue by AyushCloud** [goharbor/harbor#10137]
Hi,

I deleted the images from the harbor Ui but they are still in the s3 bucket.
Is there any config in the harbor.yml file needs to be done to get it automatically delete from the s3 bucket or do we have to delete them manually from the s3 bucket.

Thanks

**Comment by bjethwan** [comment]
@AyushCloud - Deleting images on UI would mean the deletion of tags. You will have to run GC to get rid of the actual image blobs from S3. I guess that's the reason why Harbor always proposes to run multiple registries so that you can run GC more often in non-prod while less frequent in prod. GC schedule is global.

Remember, although Harbor document says that it's on online GC, but behind the scenes, Harbor is invoking docker registry gc script, so harbor has to mark the registry read-only, while GC is running.

HTH

**Comment by reasonerjt** [comment]
@bjethwan  thanks!

**Comment by AyushCloud** [comment]
Thanks
