### ISSUE TITLE
webhook .vs. cloudEvents

### ISSUE THREAD

**Issue by reasonerjt** [goharbor/harbor#10146]
This was not in our radar, but we may consider to be compliant to this spec?

https://github.com/cloudevents/spec

cc @mmpei

**Comment by mmpei** [comment]
we can make the payload following the CloudEvent rule. but should consider the compatibility. low priority.

**Comment by rguske** [comment]
Hi @reasonerjt @mmpei ,
since the adoption of CloudEvents is continuously increasing, the support for CEs in Harbor would be an awesome enhancement for the project IMO. Projects like [VEBA](https://github.com/vmware-samples/vcenter-event-broker-appliance) for example, which goal is to e.g. make event-driven automation/interaction easy consumable for "everyone", could immediately make benefit from it.
A concrete use case is already filed: [VEBA issue #914](https://github.com/vmware-samples/vcenter-event-broker-appliance/issues/914)
