### ISSUE TITLE
[feature request]: embeddable vulnerability status badge

### ISSUE THREAD

**Issue by tuxknight** [goharbor/harbor#10391]
A vulnerability status badge would be shown in ci/cd tools or dashboards. And that will clarify the status of docker image in time in our devops workflow.

**Comment by AllForNothing** [comment]
This has been completed

**Comment by benediktberger** [comment]
What is the result on this issue? Why is it discarded? We would love to integrate the scanning results in our security overviews.

**Comment by AllForNothing** [comment]
@benediktberger This has been implemented already:
You can have the overview of the artifact on the artifact list page:
<img width="1305" alt="image" src="https://user-images.githubusercontent.com/30999793/208030022-c38fb817-1b0b-4a3a-814c-322b8a9e7a1a.png">
And you can view CVE details on the artifact detail page
<img width="1394" alt="image" src="https://user-images.githubusercontent.com/30999793/208030129-63cae334-61db-46d0-8ac0-f6e140ac06c4.png">

**Comment by benediktberger** [comment]
@AllForNothing  As I mentioned we want to include this information in an external overview page, so I would need a link to display this information. As far as I could see from the rendered HTML there is no such possibility because the tooltip is rendered statically in the Harbor UI.
I was referring to a info badge like Dependency Track or GitLab provide, see https://docs.dependencytrack.org/integrations/badges/ or https://docs.gitlab.com/ee/user/project/badges.html for example.

**Comment by AllForNothing** [comment]
@benediktberger 
Thanks for the explanation, I misunderstood your requirement earlier.
Currently, Harbor does not have an API/function that can statistically analyze all CVEs to form an overview page.
See #10496. If possible, you can share your use case/requirement in this issue.
So I'll keep this closed, as it's a duplicate with #10496
