### ISSUE TITLE
Tag Retention/Immutability

### ISSUE THREAD

**Issue by kmmanto** [goharbor/harbor#10506]
What can we help you?
I have 2 Tag Retention Rules set:
Rule 1: For the repositories matching **, retain the images pulled within the last 7 days with tags matching **
Rule 2: For the repositories matching **, retain the most recently pulled 5 images with tags matching **

I also have set Tag Immutability for all repos and tags.

---
A tag is set to be deleted due to Tag Retention rules, however Immutability prevents it from being deleted. 

Is this by design or a limitation in Docker itself? 
Is there a way to for delete an Immutable tag if it's deemed deletable according to Tag Retention rules?

**Comment by xaleeks** [comment]
It's by design that immutability has higher precedence over retention since immutability blocks the deletes at the API level, so images are locked.  retention is just one manifestation of the deletion.  Only way to delete immutable objects is to turn off immutability, run retention again, and turn it back on when you think you've deleted what you wanted.  @kmmanto

**Comment by Vad1mo** [comment]
related to https://github.com/goharbor/harbor/issues/20989
