### ISSUE TITLE
Harbor v1.4.0-rc2 --- The mirror size is zero

### ISSUE THREAD

**Issue by Kry1702** [goharbor/harbor#10690]
Login UI interface Part of the image size in the project address is zero.
Cannot be deleted.

How do I delete a mirror with zero size？

**Comment by bitsf** [comment]
this is quite an old release, what error can you see ?
@reasonerjt do you remember if we have such issues or workaround ?

**Comment by Kry1702** [comment]
I've found out why does the mirror image go to size zero.

**Comment by Kry1702** [comment]
> this is quite an old release, what error can you see ?
> @reasonerjt do you remember if we have such issues or workaround ?

**Comment by Kry1702** [comment]
> 这是一个很旧的版本，您会看到什么错误？
> @reasonerjt您还记得我们是否存在此类问题或解决方法吗？

Thank you for reply

I only know it is an old version. I once tested the upgrade and migration, but some function menus were not normal after the upgrade was completed.

Such as:

Tasks function, which normally displays as "任务" in Chinese, but actually displays "SIDE_NAV.TASKS"

**Comment by reasonerjt** [comment]
Per this release document:
https://github.com/goharbor/harbor/blob/master/RELEASES.md

Only 3 versions are officially maintained

We try to help as much as we can but 1.4 is really too old.

The size "0" issue may be due to a known bug in backend registry.
You can try the workaround by pushing it again, see https://github.com/goharbor/harbor/issues/7924
