### ISSUE TITLE
Backup and restore

### ISSUE THREAD

**Issue by cuprumpea** [goharbor/harbor#10729]
How to backup and restore harbor

**Comment by renmaosheng** [comment]
We can some backup script you can use for docker-compose deployment . Daojun, could you please help provide it? thanks.

**Comment by stonezdj** [comment]
We have some backup and restore script before:

https://github.com/stonezdj/harbor/blob/backup_restore/tools/harbor-backup.sh
https://github.com/stonezdj/harbor/blob/backup_restore/tools/harbor-restore.sh

**Comment by renmaosheng** [comment]
@cuprumpea would above document help? thanks.

**Comment by tiendungitd** [comment]
Hi @renmaosheng , @stonezdj 
The provided script is backup for whole Harbor registry. Is it possible to only backup and restore some specific Repositories?
It is make sense that if some repositories corrupt, I ony need to restore this repositoires instead of whole instance.
Thanks.

**Comment by calen3** [comment]
> We have some backup and restore script before:
> 
> https://github.com/stonezdj/harbor/blob/backup_restore/tools/harbor-backup.sh
> https://github.com/stonezdj/harbor/blob/backup_restore/tools/harbor-restore.sh

harbor-restore.sh , always has "ERROR:  database "registry" is being accessed by other users" ,  I had try "SELECT * FROM pg_stat_activity;" and kill -9 pid, did not work,  another way  "SELECT pg_terminate_backend(pg_stat_activity.pid) FROM pg_stat_activity WHERE datname='registry' AND pid<>pg_backend_pid();" , still get that ERROR. 
Did someone test the scripts?

**Comment by sakshirathorebgw** [comment]
> We have some backup and restore script before:
> 
> https://github.com/stonezdj/harbor/blob/backup_restore/tools/harbor-backup.sh
> https://github.com/stonezdj/harbor/blob/backup_restore/tools/harbor-restore.sh

these files are licence protected, so how one can execute this on the system to take the backup . please help

**Comment by stieglma** [comment]
As far as I found out you can basically just backup the whole `data` directory, and for restore just put it back into the place where the containers expect it to be. I always use `tar xvfp` for doing such backups and did not have any problems with it so far. 

Additionally I do manual database dumps with `pg_dump`.  I also only get pg_dump to work properly when not piping it out of a docker container directly, so instead of doing that, I mount an additional volume `./backup:/backup` to the `postgresql` container and then have the commands as follows:

```bash
docker-compose exec -T postgresql bash -c "pg_dump -c -b -U postgres -d registry > /backup/registry.sql"
docker-compose exec -T postgresql bash -c "pg_dump -c -b -U postgres -d postgres > /backup/postgres.sql"
docker-compose exec -T postgresql bash -c "pg_dump -c -b -U postgres -d notarysigner > /backup/notarysigner.sql"
docker-compose exec -T postgresql bash -c "pg_dump -c -b -U postgres -d notaryserver > /backup/notaryserver.sql"
```
I am not sure if I need the notary db backups at all, as I did not set up notary, but like that they are already included in the case I need it at some point ;)
From the local `backup` folder you can the copy the sql files to wherevery you want to store them. I personally put them into the same tar.gz file I create for the `data` folder
