### ISSUE TITLE
Docker login expires unexpectedly with OIDC ?

### ISSUE THREAD

**Issue by Eric-Fontana-Bose** [goharbor/harbor#10737]
Running with v1.10.0 and OIDC Enabled.

Here is what is happening:

1. User OIDC Logs in.   User goes to profile tab and gets his token
2. docker login -u username with the token
3. User can do a "docker push" using the token.
4. 24 Hours later, the Users OIDC session expires
5. User tries to docker push using <token> and it fails 
```denied: requested access to the resource is denied
unauthorized: authentication required
```
6. User then re-logs into Harbor, gets the same token as in step 1.
7. User does a docker push with the same step 1 token, this time it succeeds.

Why does the user's token expire?   Why does re-logging into Harbor seem to reset the token?

**Comment by reasonerjt** [comment]
This is working as design because the user at the OIDC provider side may be removed or invalidated so the OIDC CLI secret has same life span as the id token.

But when docker login it will try to refresh the oidc if it expires, in your case it's possible the OIDC provider does not respond with refresh token, so when the id token expires the cli secret stop working.

When you login again you get the new id token to associate with the CLI secret so the docker login  works again.

**Comment by cafeliker** [comment]
I like this Harbor design because our cyber security always asks for multi-factor authentication on personal account - and this Harbor design with OIDC ensures this.

For CI/CD purpose, we use the robot accounts which don't have such control.

**Comment by xaleeks** [comment]
@Eric-Fontana-Bose Let me know if you still have questions around this, closing for now.
