### ISSUE TITLE
Missing documentation around validated or supported versions of dependent components like REDIS & Postgres

### ISSUE THREAD

**Issue by bjethwan** [goharbor/harbor#10778]
Missing documentation around validated or supported versions of dependent components like REDIS & Postgres.

https://cloud-native.slack.com/archives/CC1E09J6S/p1581949074152400

**Comment by renmaosheng** [comment]
thanks for filing the issue, we are not testing every version of redis and postgres, but in our offline installation bundle, we have the built-in version, it would be good we can expose that in our documentation.

**Comment by bjethwan** [comment]
@renmaosheng the docker-compose file generated by the installer has below versions...looks like postgres and redis images have been re-tagged.

  postgresql:
    image: goharbor/harbor-db:v1.10.1

  redis:
    image: goharbor/redis-photon:v1.10.1
    container_name: redis

**Comment by reasonerjt** [comment]
We'll make sure it's added in the release note.
@xaleeks anywhere else you think appropriate for such information?

**Comment by xaleeks** [comment]
@bjethwan  Hi Biping, you can see the component versions listed here https://github.com/goharbor/harbor/blob/master/docs/1.10/install-config/_index.md, right now we only list the ones used by the most current versions.  Because we ship as containers that has all the dependencies packaged, you get something that works out of box.  If you want to use a specific version of a particular dependency like redis or pgsql, we welcome you test it and let us know the version of Harbor you tested against so we can also maintain that information for other users.  Right now, this is the only way to build out this compatibility matrix.

**Comment by reasonerjt** [comment]
We'll only document the versions of the built-in components, and will not verify other versions due to lack of resource.

**Comment by bjethwan** [comment]
@reasonerjt @xaleeks 
Since this is important for folks deploying HA model.
And we are definitely deploying Harbor in HA mode.
I can sure try my best to run the tests against the latest Postgres and if I save time I can also run tests against latest REDIS.

Do you have some end-to-end tests automated? Kindly point me to the test scripts and I will record my results.
