### ISSUE TITLE
tag retention and GC schedule should run at a different time

### ISSUE THREAD

**Issue by bitsf** [goharbor/harbor#11052]
issue #10835 
If tag retention and GC run at the same time, the deletion may failed because of registry readonly status.
It is suggest to stagger time.

Currently for daily schedule, both are at 00:00:00

**Comment by bitsf** [comment]
@xaleeks @steven-zou @ywk253100 What do you think a good time or other suggestion ?

**Comment by reasonerjt** [comment]
@bitsf  are you suggesting that we should set a different default value?

**Comment by xaleeks** [comment]
Can you describe the issue in detail?  @bitsf

**Comment by bitsf** [comment]
@reasonerjt yes, I suggest run GC after tag retention, maybe 1 or 2 hours later

**Comment by bitsf** [comment]
This is mainly useful for harbor 1.9.x and 1.10.x.

@wy65701436 for harbor 2.x, if we implement the non-block GC, there should be no problem ?

**Comment by xaleeks** [comment]
The issue is calls to registry to delete images are blocked while GC is running.  Here is what I propose before this can be fully resolved by non-blocking GC.  Use different default values for the daily scheduled jobs, at least 1 hour apart.  In the case where GC job is running when tag retention job starts, tag retention should bow out gracefully and wait until the next scheduled execution.  It should also fire a webhook indicating it ran unsuccessfully due to conflict with GC.

**Comment by xaleeks** [comment]
If non-blocking cannot resolve this, it's not truly non-blocking.

**Comment by xaleeks** [comment]
what is status here?  Is it something that needs to be addressed? @bitsf

**Comment by bitsf** [comment]
@reasonerjt Yes, I'm suggesting to use different time for daily schedule

**Comment by bitsf** [comment]
GC is very quickly in 2.1.0 now, so this conflict will not be obvious
