### ISSUE TITLE
Document the limitations of downloading the Trivy VULN DB from the github

### ISSUE THREAD

**Issue by steven-zou** [goharbor/harbor#11061]
No token: 6 per hour?
Token: 5000 per hour?

**Comment by danielpacak** [comment]
As explained here: https://developer.github.com/v3/#rate-limiting

For API requests using Basic Authentication or OAuth, you can make up to 5000 requests per hour. Authenticated requests are associated with the authenticated user, regardless of whether Basic Authentication or an OAuth token was used. This means that all OAuth applications authorized by a user share the same quota of 5000 requests per hour when they authenticate with different tokens owned by the same user.

For unauthenticated requests, the rate limit allows for up to 60 requests per hour. Unauthenticated requests are associated with the originating IP address, and not the user making requests.

**Comment by renmaosheng** [comment]
we will add this into the install md file, thanks.

**Comment by danielpacak** [comment]
> we will add this into the install md file, thanks.

I think it's also worth mentioning that the Trivy DB is updated every 12 hours and Trivy detects that it has up to date DB file to unnecessary downloads. That's why the deployment of trivy adapter should use the volume mount to cache the DB file. With that it's very unlikely to hit the GitHub rate limit.

**Comment by heww** [comment]
Closed #11916
