### ISSUE TITLE
Vulerability policy checker error message is confusing

### ISSUE THREAD

**Issue by wy65701436** [goharbor/harbor#11202]
The error that I get from docker client

`Error response from daemon: unknown: current image with "" vulnerable' cannot be pulled due to configured policy in 'Prevent images with vulnerability severity of "Low" from running.' Please contact your project administrator for help'`

[step]
1, push hello-world
2, scan it with clair
3, Enable polick check `Prevent vulnerable images from running`.
4, pull hello-world

**Comment by xaleeks** [comment]
@wy65701436  @heww 
It should say

current image with xx vulnerabilities cannot be pulled due to configured policy in 'Prevent images with vulnerability severity of "Low" or higher from running.' To continue with pull, please contact your project to exempt matched vulnerabilities through configuring the CVE whitelist
