### ISSUE TITLE
trivy sets severity to `unknown` after scanning image based on photon:2.0

### ISSUE THREAD

**Issue by reasonerjt** [goharbor/harbor#11210]
I tried to scan image using the trivy scan adapter, and the severity is `unknown`:
![Screen Shot 2020-03-24 at 12 21 47 PM](https://user-images.githubusercontent.com/2390463/77388905-6b596c80-6dcc-11ea-9d7f-8f88a4bb5b4c.png)

it should not be `unknown` if the vulnerability list is empty.
The image has been pushed to docker hub: `danieljt/harbor-migrator:test`

**Comment by danielpacak** [comment]
When there are no vulnerabilities the harbor-scanner-trivy returns the following JSON report:

```json
{
  "generated_at": "2020-03-25T08:33:00.155430773Z",
  "artifact": {
    "repository": "library/harbor-migrator",
    "digest": "sha256:06d932402423c5b5fe6c358a48cec6551adaa8896c28cee1e9b899647220737f",
    "mime_type": "application/vnd.docker.distribution.manifest.v2+json"
  },
  "scanner": {
    "name": "Trivy",
    "vendor": "Aqua Security",
    "version": "0.5.3"
  },
  "severity": "Unknown",
  "vulnerabilities": [
    
  ]
}
```

In Harbor `v1.10.0-6b84b62f`it's displayed as follows:

<img width="1104" alt="harbor_v1 10_no_vulns" src="https://user-images.githubusercontent.com/1322923/77517519-8f748680-6e7c-11ea-91c3-f5070ed2bba7.png">

With that I'm checking whether it's caused by some changeds to the UI code in the master branch.

**Comment by steven-zou** [comment]
@danielpacak 

Is it ok to introduce a `None` to indicate the case of no vulnerabilities in the spec?

**Comment by danielpacak** [comment]
> @danielpacak
> 
> Is it ok to introduce a `None` to indicate the case of no vulnerabilities in the spec?

@steven-zou Pluggable Scanners API v1 uses qualitative ratings inspired by Clair, i.e.:
- Unknown
- Negligible
- Low
- Medium
- High
- Critical

I believe that at some point, maybe Pluggable Scanners API v2, we should adapt standard [CVSS v3.0][cvss] qualitative severity rating scale:


| Rating | CVSS Score |
| --- | --- |
| None | 0.0 |
| Low | 0.1 - 3.9 |
| Medium | 4.0 - 6.9 |
| High | 7.0 - 8.9 |
| Critical | 9.0 - 10.0 |

To do that in a proper order I'd:
- (Optional) Rename `Negligible` to `None` to get closer to the CVSS v3.0 metrics
- If there're no vulnerabilities, we should return `None` as overall severity instead of `Unknown`, e.g.:
   ```js
   {
     "generated_at": "2020-03-25T08:33:00.155430773Z",
     "artifact": {
       "repository": "library/harbor-migrator",
       "digest": 
       "sha256:06d932402423c5b5fe6c358a48cec6551adaa8896c28cee1e9b899647220737f",
       "mime_type": "application/vnd.docker.distribution.manifest.v2+json"
     },
     "scanner": {
        "name": "Trivy",
        "vendor": "Aqua Security",
        "version": "0.5.3"
     },
     "severity": "None",
     "vulnerabilities": []
   }
   ```

[cvss]: https://www.first.org/cvss/v3.0/specification-document

**Comment by steven-zou** [comment]
Let's fix it from UI or harbor backend side as a temporary solution.

We'll raise a new issue to follow up on the enhancement in the future. e.g.: upgrade severity spec to CVSS 3.0 which Daniel P suggested.

**Comment by steven-zou** [comment]
@AllForNothing 

summary:{} should also be counted as no vulnerability

@heww 

Please update VUL check middleware too.
