### ISSUE TITLE
artifacts not be deleted after replication failed because of quota

### ISSUE THREAD

**Issue by bitsf** [goharbor/harbor#11213]
harbor 2.0
commit 3158
1. set a count quota
2. upload enough images and make the quota full
3. do replication which should just copy 1 artifact
![image](https://user-images.githubusercontent.com/188115/77390430-e58bf000-6dd0-11ea-9540-3474e28be2c3.png)
4. job failed as expected
5. but there will be 6 artifacts left in project
![image](https://user-images.githubusercontent.com/188115/77390487-18ce7f00-6dd1-11ea-91de-3106ad79b8e2.png)

These should be cleaned after job failed

**Comment by ywk253100** [comment]
The replication here has the same behavior with artifact clients. Every blob/manifest uploading is a separated request, the rollback only happens inside one request.

So I don't think this needs any fix. This works as expected

**Comment by reasonerjt** [comment]
Actually in the particular case for replication, there is something we can do to mitigate, we can calculate the the total number of the artifacts in manifest list and fail early. (do-able in both push and pull based replication)

But I agree there's no easy way to solve all corner cases and contain the cases for user pushing index with 3rd party tool.

Not a P0 for me

**Comment by reasonerjt** [comment]
We'll see this as a limitation, and leave it as is for 2.0.0

**Comment by xaleeks** [comment]
@bitsf  This description is not very clear and it makes it hard to further diagnose the issue, we should be aware to add back any internal discussion we might have had prior to creating these and to give proper context so the issue is self-contained.  ie 'replication failed because of quota' is too generic IMHO.

That said, is the issue that quota reached does not prevent completion of replication?  In which case we should mitigate by fail early or clean them off after replication, with storage to be freed by running GC.  Replicating these after quota has already been reached on the target and keeping them there is a bad idea, because you can flood the target with whatever you want and bring it down.  

Or is this an issue of a replication an index being interpreted as one request, with the index containing multiple children images each of which will replicate successfully until the parent request fails?  I can't really tell.

**Comment by bitsf** [comment]
This is about the second scene.
And this is discussed before, wenkai and others don't think this is a critical problem, just mark as an known issue
