### ISSUE TITLE
doc "Upgrade Harbor and Migrate Data" is missing

### ISSUE THREAD

**Issue by bitsf** [goharbor/harbor#11220]
![image](https://user-images.githubusercontent.com/188115/77397132-03148600-6de0-11ea-8cbc-8538a0b634a4.png)

which should be in docs/1.10/administration/upgrade/upgrade-migrate-data.md

**Comment by dvaerum** [comment]
The same link exists here

![image](https://user-images.githubusercontent.com/6872940/79631425-99c33100-8159-11ea-8342-7ae5f3f1854f.png)

**Comment by xaleeks** [comment]
docs have been reorganized now, 1.10 docs are on its own branch

**Comment by dvaerum** [comment]
@xaleeks what branch are you talking about, I have check release-1.10.0, release-1.10-doc & sclements-1.10-doc-updates and I cannot find any docs for upgrade Harbor and migrate data to version 1.10+ also I think it is a really bad idea to put this under its own branch instead of having it in the master branch, if you don't write it any were because that is not how it normally works and I really doubt anyone will find it in it own branch

**Comment by renmaosheng** [comment]
Hi Dannis, we are referring https://goharbor.io/docs/2.0.0/ , you can choose which version of docs we would like to read. Hope this helps.
