### ISSUE TITLE
Tag retention should not accidentally delete untagged child manifests

### ISSUE THREAD

**Issue by bitsf** [goharbor/harbor#11273]
when not check untagged in retention policy
![image](https://user-images.githubusercontent.com/188115/77518245-6245c980-6eb8-11ea-8f1c-77f71ebc36a2.png)

if user pushing images with multi manifest, that means in the meanwhile the artifact do not have any tags, tag retention policy may delete it

**Comment by reasonerjt** [comment]
I recall when the policy is taking action it is doing a scan and delete process?

If that's true when it's deleting the artifact it should make sure the artifact has no tags.

**Comment by reasonerjt** [comment]
There will be such corner case but we believe it will not cause inconsistency in data as there's foreign key.

**Comment by xaleeks** [comment]
A majority of OCI indexes when pushed onto Harbor will not have tags on the children manifests and only on the parent manifest.  I don't know off the top of my head what the correct behavior is, we need to map out some user stories.  I don't think checking that box by default to prevent accidental deletion is enough mitigation.  

At the same time, we built v2.0 around the idea of being able to operate on the bundle as a whole as well as on the children images individually, so if a child image was actively manipulated to have a different tag or no tag, it should not suffer the consequence of an action intended for the parent, if that makes sense.

**Comment by bitsf** [comment]
这个是说在用户 push 镜像时，部分manifest已经上传的时候，正好自动运行了retention任务，有可能会把已上传的还没关联到parent的，没有tag的这些manifest给删了
不过这个应该由于之后会报错重试，理论上不会真正产生问题

**Comment by xaleeks** [comment]
@bitsf we should test this scenario, push something large so you have enough time to start a retention job mid push.  I'm not sure what you meant by it will generate an error, which operation will generate the error?  The other thing we can do is check to make sure no pushes are happening while running retention (restricted to that project and repository), and defer the retention job to when pushes have completed.  It's not unreasonable to force user to wait since otherwise the result is unreliable and they have to resort to running it again

**Comment by xaleeks** [comment]
Hi Ziming, can we close this or does the behavior need to be modified? @bitsf
