### ISSUE TITLE
harbor 2.0 upgrade from old, UI not show correct error message

### ISSUE THREAD

**Issue by bitsf** [goharbor/harbor#11301]
After upgrade harbor from 1.10 to 2.0, click UI there's a confuse error message "Admin"

![image](https://user-images.githubusercontent.com/188115/77622102-a1d3ea80-6f78-11ea-9662-3154d95fdfc6.png)

This error is because of old session not cleared, and HTTP 403 error.
UI should redirect to login or show a more clear error message, such as "Session invalid, please login again"

**Comment by wy65701436** [comment]
The root cause is that the user model is changed, the field to index whether the user is the admin has been changed from `HasAdminRole` to `SysAdminFlag`.

After upgrade, Harbor gets the session from the store but with the old style user model and it cannot be mapped to the new user model, then Harbor sees he as non-admin and gives a 403.
