### ISSUE TITLE
Harbor is not pushin image on Azure registry

### ISSUE THREAD

**Issue by joshisagar92** [goharbor/harbor#11685]
You can find details as below

https://github.com/goharbor/harbor/issues/11442#issuecomment-617088679

When I try without override option replication is success but Not able to seen any image over azure registry

**Comment by joshisagar92** [comment]
I am using Version v1.8.0-25bb24ca

**Comment by fl-max** [comment]
I am using Harbor v2.0.1 and appear to be experiencing the same issue. My Registry Endpoint is setup with:
Provider: `Azure ACR`
Name: `My ACR`
Endpoint URL: `http://<acr_name>.azurecr.io`
Access ID: `<acr_name`
Access Secret: `<admin_secret_key>`
Verify Remote Cert: `unchecked`

Replication Setup:
Name: `replicate-image`
Source resource filter:
- Name: `<project_name>/* `
- Tag: `* `
- Label: ``
- Resource: `image`

Destination registry: `My ACR-http://<acr_name>.azurecr.io`
Destination namespace: `<project_name>`
Trigger Mode: `Event Based`
Delete remote resources when locally deleted: `checked`
Override: `checked`
Enable rule: `checked`

In my Job Service Pod, I can see that the replication is a "success":
`Job 'REPLICATION:e2811c40099a02d9ac4480d6' exit with success`

However in ACR, no images exist,

**Comment by constantinpr** [comment]
Any help with this will be greatly appreciated, I'm facing the exact same issues as above, identical setup as well for he registry and the replication setup

**Comment by fl-max** [comment]
This is still an issue in `v2.1.1`

**Comment by fl-max** [comment]
Actually, digging in a little more I was able to get it to work now!

I believe the issue was with `https` not working when defining a registry endpoint for ACR in `v2.0.*`. I now have the following settings:

Provider: `Azure ACR`
Name: `My ACR`
Endpoint URL: `https://<acr_name>.azurecr.io`
Access ID: `<acr_name`
Access Secret: `<admin_secret_key>`
Verify Remote Cert: `checked`

Replication Setup:
Name: `replicate-image`
Source resource filter:
- Name: `<project_name>/**`
- Tag: `**`
- Label: ``
- Resource: `image`

Destination registry: `My ACR-https://<acr_name>.azurecr.io`
Destination namespace: `<project_name>`
Trigger Mode: `Event Based`
Delete remote resources when locally deleted: `checked`
Override: `checked`
Enable rule: `checked`

Using the above, I can now see images being replicated to ACR. This issue can probably be closed now.
