### ISSUE TITLE
OIDC with Microsoft ADFS: Email in not retreived

### ISSUE THREAD

**Issue by larde** [goharbor/harbor#11769]
When using ADFS as an OIDC provider, user is created with an empty email.

In core.log, I have this:
Apr 27 12:02:19 192.168.0.1 core[1425]: 2020-04-27T10:02:19Z [WARNING] [/common/utils/oidc/helper.go:331]: Unable to get groups from claims, claims: map[aud:7df138b6-222a-445f-b12c-a1faae17f4bf auth_time:1.587981739e+09 exp:1.587985339e+09 iat:1.587981739e+09 iss:https://adfs.company.com/adfs pwd_exp:14937432 sid:S-1-5-21-54645767-567568778-2345453566-1127 sub:TgnDEyejXtlvtfCX3/jtx3oj0ucj+Txc= unique_name:ACMECORP\doe upn:doe@acmecorp.com], groups claims key: 

=> upn can be used for the email field. Is it possible to map this field to email?

Moreover, as I'm in the OIDC mode, users can't update themself the email field in the profile page.
So only one user can be created as the email field in harbor_user table as to be unique...

**Comment by t109595** [comment]
We are using ADFS and are able to populate email. It needs to be in the claim field "email". From your log, it looks like you are populating an email address into the "upn" field. 

Make sure if you are in a non production environment that the underlying Active Directory record actually has the email populated in the standard data element. Often email records aren't populated into non-production directories because it can cause issues.

**Comment by reasonerjt** [comment]
Thanks @bryan-taylor for chiming in!
@larde does that help?

**Comment by larde** [comment]
Hi, I confirm that it was an ADFS Issue.

For allowing the scope "email", the "allatclaims" must be also checked.
![image](https://user-images.githubusercontent.com/30491153/84636002-51738580-aef4-11ea-8a08-aa9e88259f14.png)

Then it works.

**Comment by reasonerjt** [comment]
Thanks for the update @larde

**Comment by CaptAintHere** [comment]
Thanks @larde for your solution, I faced the same issue.
Does anyone managed to populate the first and last name field ?
