### ISSUE TITLE
upgrade failed from v1.9.x to v1.10.3

### ISSUE THREAD

**Issue by david972** [goharbor/harbor#12232]
Hi,
I used https://github.com/goharbor/harbor-helm to upgrade goharbor
But I've got several issue ...
 
Due to the following 
https://github.com/goharbor/harbor/blob/afab4169f6aa6f845f02088f8e3ad9cb05837db9/src/common/dao/pgsql.go#L32
https://github.com/goharbor/harbor/blob/afab4169f6aa6f845f02088f8e3ad9cb05837db9/src/common/dao/pgsql.go#L108
I've got this error
`2020-06-13T19:31:49Z [FATAL] [/core/main.go:185]: failed to initialize database: file does not exist`

To fix this issue I had to fill this env like this `POSTGRES_MIGRATION_SCRIPTS_PATH=/harbor/migrations/postgresql/`
https://github.com/goharbor/harbor/blob/afab4169f6aa6f845f02088f8e3ad9cb05837db9/src/common/dao/pgsql.go#L104

I've got an other issue on my deployment livenessProbe and readinessProbe
I'm raising up an issue on harbor-helm side

**Comment by renmaosheng** [comment]
Yan, could you please take a look at this upgrade issue? thanks.

**Comment by david972** [comment]
Actually, I did not look why but by using the v1.3.2 helm chart version this issue did not raised up

**Comment by reasonerjt** [comment]
@david972
There are changes in regards to the configuration settings of Harbor across different versions.

Please try not to upgrade the helm chart by simply updating the `values.yaml` of the helm chart.  Please try using the same minor version helm chart that maps to Harbor's version.

In your case, as you figured, you should use chart 1.3.x instead of 1.2.x
