### ISSUE TITLE
Push images to harbor parallel very slow

### ISSUE THREAD

**Issue by hantmac** [goharbor/harbor#12243]
Hi, I came cross a problem that  pushing many images to the harbor in the same time (parallel) is 
 slowly, even stuck in the end.
The version of harbor is v1.7.4, there is any way to solve this problem? Or anyone of you had this problem before？
Thank you very much if you would like help me to solve it!

**Comment by hantmac** [comment]
I wanna to know what is the best practice of the flowing field?
```
#Maximum number of job workers in job service
max_job_workers = 10
```
What is the function of `max_job_worker` number?

**Comment by heww** [comment]
The max_job_workers number means how many jobs can be execuated in parallel. Image scanning, replication, tag retention, gc are all execuated in the job service.

**Comment by heww** [comment]
The performance of the image pushing depends on the network between the docker client and harbor, depends on the network between the harbor and the storage used to store the image, and also depend on the storage used to store the image.

To improve the performance of the image pushing, you can try to increase the instances of the core component so that harbor can accept more blob pushing when network bandwidth is enough.

When the storage used to store the image is the local system, the higher the performance of the disk, the better.

When the storage used to store the image is object storage like s3, you can try to increase the instances of the registry component so that harbor can transfer more data in parallel to the storage.

Of course, increasing the memory is welcome because hold the blob data during the pushing will eat memory.

**Comment by hantmac** [comment]
@heww Thank you for your patient reply and it's very helpful to solve my problem , thank you again !
