### ISSUE TITLE
Azure Replication still not working after 2.0.1 Upgrade

### ISSUE THREAD

**Issue by phin1x** [goharbor/harbor#12367]
**Expected behavior and actual behavior:**
Harbor should successfully ping an Azure Registry with authorization data. In harbor 2.0.1 the ping request fails with unauthorized:

> Jul  1 07:47:25 172.27.0.1 core[1581]: 2020-07-01T05:47:25Z [ERROR] [/replication/adapter/native/adapter.go:126]: failed to ping registry https://edearegistry.azurecr.io: http status code: 401, body: {"errors":[{"code":"UNAUTHORIZED","message":"authentication required, visit https://aka.ms/acr/authorization for more information.","detail":null}]}

The bug should actually be fixed with PR #11978 

**Steps to reproduce the problem:**

1. Setup Harbor 2.0.1 with debug logging enabled
2. Setup ACR
3. Configure Endpoint with https
4. Press "test connection"

**Versions:**
Please specify the versions of following systems.

- harbor version: 2.0.1
- docker engine version: 19.03.5
- docker-compose version: 3.7.0

**Additional context:**

- **Harbor config files:** You can get them by packaging `harbor.yml` and files in the same directory, including subdirectory.
- **Log files:** You can get them by package the `/var/log/harbor/` .

**Comment by phin1x** [comment]
initial bug report #11974

**Comment by reasonerjt** [comment]
@phin1x I think this means the credentials you set for the ACR endpoint was incorrect.

**Comment by phin1x** [comment]
@reasonerjt that was also my first thought. We double checked the credentials, but they are correct. If I specify the endpoint with http instead of https, the ping and image replication works.

http://myregistry.azurecr.io -> works
http**s**://myregistry.azurecr.io -> don't work

I configured the registry in Harbor 1.10 and it worked as expected. The registry was marked as unhealthy after the upgrade to 2.0.

**Comment by bitsf** [comment]
This is quite weird, http and https should not behave different, we'll check again.

**Comment by fredgate** [comment]
I have same problem. Since Harbor 2.0 replication to ACR does not work anymore (I tested 2.0.1 rc1 and it is not fixed). I am sure of the credentials : it works fine using `docker login` in a shell.
ACR does not support http. Pinging ACR with HTTP protocol in Harbor seems work, but this is because Harbor does not check the content of the response : it only checks the HTTP status code. When calling http protcol, ACR return a 301 and 302 redirecting to https://azure.microsoft.com/fr-fr/services/container-registry/ with a 200. So ping in Harbor is ok, but next running replication produces no image uploads (ACR remains empty).

**Comment by fredgate** [comment]
Pinging ACR with HTTPS protocol (the only supported protocol), produces these lines in `core.log` file
```
Jul 16 06:48:45 172.18.0.1 core[11288]: 2020-07-16T06:48:45Z [ERROR] [/replication/adapter/native/adapter.go:126]: failed to ping registry https://contoso.azurecr.io: http status code: 401, body: {"errors":[{"code":"UNAUTHORIZED","message":"authentication required, visit https://aka.ms/acr/authorization for more information.","detail":null}]}
Jul 16 06:48:45 172.18.0.1 core[11288]: 2020/07/16 06:48:45.257 #033[1;44m[D]#033[0m [transaction.go:62]  |     10.80.1.12|#033[97;43m 400 #033[0m| 355.835201ms|   match|#033[97;46m POST    #033[0m /api/v2.0/registries/ping   r:/api/v2.0/registries/ping
```
I am sure that credentials are valid.

**Comment by bitsf** [comment]
this issue is actually fixed by PR https://github.com/goharbor/harbor/pull/11978, but not cherry-pick to v2.0.x

**Comment by fredgate** [comment]
However release page and closed issues for version 2.0.1 indicate that the fix is included in the 2.0.1 version : 
https://github.com/goharbor/harbor/releases/tag/v2.0.1
https://github.com/goharbor/harbor/issues?page=2&q=is%3Aissue+label%3Atarget%2F2.0.1+is%3Aclosed

This bug, introduced in 2.0 version, is really critical : it broke all our CI pipelines.

**Comment by ywk253100** [comment]
The fix https://github.com/goharbor/harbor/pull/12505 is merged into 2.0.x branch and will be available in release 2.0.2

**Comment by phin1x** [comment]
Is there a release date for 2.0.2?

**Comment by bitsf** [comment]
yes, harbor is trying release new version monthly.
