### ISSUE TITLE
Prevent retagging in limited storage capacity environments

### ISSUE THREAD

**Issue by Purushotham233** [goharbor/harbor#12377]
What can we help you?
How to ensure a Tag is mapped to a single digest of the image.

Tag immutability can be used but that forces us to retain the image forever. This wont work in limited storage capacity environments.

Is there any other way we can achieve this?

**Comment by reasonerjt** [comment]
@Purushotham233 
Do you mean you want the tag be immutable but it can be removed?

**Comment by Purushotham233** [comment]
@reasonerjt,
Yes. May be by retaining the tag to digest mapping even when a particular digest(image-version) is deleted from the repository in the system.

We believe this is a kind of guard-rails to prevent users from adding a Tag to different version/digest at different times that potentially can lead indeterministic deployments. 

We like to have this check sooner than later. Let us know if this is a desirable new feature that needs significant work, we can work on raising a detailed change proposal.

**Comment by reasonerjt** [comment]
@Purushotham233 
Technically I don't think it requires a lot of effort.  But IMO the immutability policy is for protecting the tag, and it should include protecting tags from being deleted by mistake.

That said, I don't really understand why this is a very high priority feature you can always adjust the immutability policy if you want some of the tags to be removed.

**Comment by Purushotham233** [comment]
@reasonerjt 
> That said, I don't really understand why this is a very high priority feature you can always adjust the immutability policy if you want some of the tags to be removed.

We are fine tweaking immutability and removing images as required. But **We are concerned about the possibility of a tag being re-used.** 

Sequence of steps to elaborate the scenario. Say for a repository Repo1, with immutability enabled.
1. digest1 is tagged with Tag1.
2. Disable tag immutability. Delete digest1 and tags associated.
3. Now digest2 can be pushed with Tag1. **This possibility we want to be blocked.**

In the above scenario, a K8s deployment using Repo1:Tag1 can fetch different version of Repo1:Tag1 at different times. In combination with k8s auto-scaling feature this can result in multiple versions of code deployed at a given point of time.

**Regarding the priority**
In our organisation, our team plan to manage Harbor centrally and provide a Project to each dev-team. And there will be multiple k8s deployment relying on the images from Harbor. 

As a team responsible for serving all the container images, knowing the adverse possibilities, we wish to have this guard-rail in the system.

We would be happy even if this coming in the next 1 or 2 months.

**Comment by xaleeks** [comment]
I'm going to say this is not the right approach for us.  The scenario you drew out doesn't make sense from the registry's POV.  There is no way for us to know what took place from the the time the image was deleted to when it's ready to be repushed again, and it may very well have been changed and a different digest has been generated now.  It's not our position to interpret intent and disallow that.  

The immutability feature, however, makes sense because it's strictly within the image's lifetime on the registry.  Just as you would like that tag:digest to be bound together forever, there are other users who would like the ability to push a new image with that old tag, ie. anything 'nightly', 'latest' etc.  But I would overwhelmingly lean in favor of Harbor being stochastic, or memoryless with regard to what happens off-Harbor.  Once it's deleted off the registry, it's fair game.  We don't track what gets deployed in the wild.
