### ISSUE TITLE
HTTP 500 returned for invalid service token requests

### ISSUE THREAD

**Issue by xtreme-conor-nosal** [goharbor/harbor#12614]
**Expected behavior and actual behavior:**
When a user makes an invalid service token request (e.g. omitting the service, or a malformed repository path) harbor logs an [ERROR] and returns an HTTP 500 Internal Server Error.

I believe HTTP 400 Bad Request would be more appropriate (https://tools.ietf.org/html/rfc6750#section-3.1), as the error is caused by the client, not a server bug. This change would help operators filtering logs to distinguish between harbor issues to investigate vs user error.

**Steps to reproduce the problem:**
curl -v https://registry.pivotal.io/service/token without `service=harbor-registry`, or with a malformed scope

**Versions:**
Please specify the versions of following systems.

- harbor version: [2.0.1]

**Logs**
`"GET /service/token?account=myemail&scope=repository%3Aprojectrepo%3Apull&service=harbor-registry HTTP/1.1" 500`
`[ERROR] [/core/service/token/token.go:40]: Unable to handle service:`

**Comment by reasonerjt** [comment]
@xtreme-conor-nosal Thanks for the issue, agree refinement is needed for error statuses

**Comment by reasonerjt** [comment]
1. If the service is not recognized the service will return 400 not 500:
https://github.com/goharbor/harbor/blob/release-2.0.0/src/core/service/token/token.go#L39

2. When the scope contains a repository that cannot be parsed currently it returns 500, I think we can consider this requested resource is not verifiable in Harbor, so it can be treated as the resource not found, I'll clean the requested actions instead of returning any error.

**Comment by reasonerjt** [comment]
Fixed in #12790
