### ISSUE TITLE
use robot login (to get it into a k8s secret later)

### ISSUE THREAD

**Issue by fireba11** [goharbor/harbor#13116]
I'm trying to get a robot account token into a k8s secret.
Since it didn't work i tried to figure out how a working config.json with the robot token needs to look like ...
https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
describes how to get that into a secret then.

How do i need to format that?
I can't seem to get it working :-(

**Comment by xaleeks** [comment]
you're on the right track! I would also suggest reaching out to the kubernetes community for some guidance.

**Comment by u0324020** [comment]
I have the same problem...
create a secret (robot account and token)
when I deploy pods will get the status "ErrImagePull"
It seems not to work when I used robot account and token...

**Comment by MugenTwo** [comment]
To use the Harbor robot account

I think you need to put quotes when creating the docker registry secret:

kubectl create secret docker-registry harbor-registry-secret \
--docker-server=<HARBOR-URL>
--docker-username='robot$project+dev-cluster'
--docker-password=<SOME-PASSWORD>
--docker-email=<SOME-EMAIL>
-n default

Because I think the "$", "+", "-" is being treated as special characters and harbor robot accounts comes with at least a "$" and a "+".

**Comment by fireba11** [comment]
Note the single quotes needed for the username due to $
