### ISSUE TITLE
push big image harbor 1.9.1

### ISSUE THREAD

**Issue by minxiaogang** [goharbor/harbor#13339]
hello,gays!
i want know when i push image to harbor, this image has size limit? 
when i push image size 1G is succesd, and i push 2G successd，but i push 5G is faild。
Is there a mirror upload size limit or configuration item?  we use storage S3.
thanks everyone!

**Comment by minxiaogang** [comment]
i try push on the harbor v2.0.2, the image size 5.5G,it is failed!  so  is there upload size limit?

**Comment by xaleeks** [comment]
@heww @wy65701436  do we have upper bounds image pushes? I remember this is no such restriction on the distributino isde

**Comment by sharkymcdongles** [comment]
@xaleeks @miaoshixuan There are no limits within Harbor outside of overall quota.

The problem likely stems from using ingress controller in front of Harbor in Kubernetes. For ingress nginx you have several proxy size limitations since the ingress controller reverse proxies all requests to the Harbor service.

You can change these settings with these annotations on the ingress:

```
nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
nginx.ingress.kubernetes.io/proxy-max-temp-file-size: 10000m(might be redundant with the above setting)
nginx.ingress.kubernetes.io/proxy-body-size: "0"
ingress.kubernetes.io/proxy-body-size: "0"
```

**Comment by zkking** [comment]
@minxiaogang Is there any related failure log description in harbor core? What is the largest blob size contained in the image?

**Comment by wy65701436** [comment]
no limition on Harbor side, you probable should enlarge the http timeout value. And please provide the proxy.log.

How did you install Harbor?

**Comment by danielzhanghl** [comment]
FYI, I met one similar issue, that was caused by token expires, after increase the token expiration(default 30min) to 90 min, it works fine.
