### ISSUE TITLE
 Multiple domin Configure

### ISSUE THREAD

**Issue by papioyue** [goharbor/harbor#13348]
Can you configure multiple hostnames in the harbor.yml file?

**Comment by ninjadq** [comment]
Not support that yet

**Comment by mothershipper** [comment]
Will add a plus one here -- LB doesn't quite work for us. 

We're using OIDC auth with a multi-region deployment. Each region has a regional domain (harbor.east.domain) and global domain (harbor.domain). Since the OIDC auth flow uses the configured hostname for the `redirect_url`, we can't login using regional endpoints with individual user accounts using the regional domains.
