### ISSUE TITLE
why not use photon:3.0 as the base image for Dockerfile.base in harbor

### ISSUE THREAD

**Issue by zhangwenlong8911** [goharbor/harbor#13370]
What can we help you?
Hello, I have a question. I checked the dockerfile.base in the source code of harbor. All the basic images use photon: 2.0, but I went to check the photon official website. This version is very old, why not switch to photon:3.0, is it because there are some features that are incompatible, or other reasons?

**Comment by xaleeks** [comment]
The short answer is because harbor is used by multiple commercial products within different companies and we really need to have a concerted dialogue to upgrade the base image.  It is unfortunately a slow process and we've begun exploring upgrading to photon 3 or even considered canonical base images in 2021.  I'll keep this open and send updates here as well

**Comment by zhangwenlong8911** [comment]
ok，got it,thank you

**Comment by morlay** [comment]
With photon 3.0, the pg version upgrade to 10.15 (9.6 with photon 2.0)

this block to add support for multi-arch image https://github.com/goharbor/harbor/pull/13788

**Comment by tianon** [comment]
This can be closed (it was bumped to Photon 4.0 in https://github.com/goharbor/harbor/pull/14551). :tada:

**Comment by wy65701436** [comment]
Yes, let’s close it. @tianon thanks.
