### ISSUE TITLE
failed to fetch artifacts: json: cannot unmarshal object into Go value of type []*jfrog.repository JFrog Artifactory replication

### ISSUE THREAD

**Issue by dbaskakov** [goharbor/harbor#13457]
Failed JFrog Artifactory replication

Artifactory Version: 7.7.3
Harbor Version: v2.1.1

Nov  5 11:00:44 172.31.0.1 core[1039]: 2020-11-05T11:00:44Z [ERROR] [/replication/operation/controller.go:103]: the execution 5 failed: failed to fetch artifacts: json: cannot unmarshal object into Go value of type []*jfrog.repository

In Version v2.0.0-87602132 replication to artifactory works well

**Comment by chlins** [comment]
Hi, @dbaskakov , can you provide your sample replication rule?

**Comment by dbaskakov** [comment]
![Снимок экрана 2020-11-05 в 16 54 33](https://user-images.githubusercontent.com/29972823/98250286-4d6e0000-1f88-11eb-81b6-8dc75460d528.png)
![Снимок экрана 2020-11-05 в 16 57 41](https://user-images.githubusercontent.com/29972823/98250297-51018700-1f88-11eb-8106-bbdf53603f4f.png)

**Comment by chlins** [comment]
@dbaskakov I think you can try to edit your registry configuration, remove the endpoint url suffix '/artifactory/api/docker/infra', just input your jfrog domain.

**Comment by dbaskakov** [comment]
tnx, thats work.
But how can i specify specific endpoint ?

**Comment by chlins** [comment]
@dbaskakov Maybe it can not specify specific endpoint because the replication mechanism needs access all repos under your jfrog artifactory(example: in order to be able to create namespace/repo under jfrog automatic), but if you really want to configure  specific endpoint, maybe adapter of docker registry type can meet your requirement, configure your registry endpoint to 'http://your-jforg-domain/artifactory/api/docker/infra' and adapter type to 'docker registry'.

**Comment by dbaskakov** [comment]
tnx, its work 👍
