### ISSUE TITLE
How do I backup / restore harbor db?

### ISSUE THREAD

**Issue by peterjc85** [goharbor/harbor#13536]
How do I backup harbor db?

We are operating 2 harbor servers.
I want to backup and restore the harbor-db of each server.
What should I do? (I want to back up project user rights, information, labels, etc.)

Does it work normally even if I back up harbor01 DB and restore it to harbor02?
 
Can I make a full backup of the registry image?

**Comment by minxiaogang** [comment]
harbor use db is postgresql !  if you wang to backup all table or db ,you can use postgresql  pg_dumpall do it.
if you want use harbor01DB to the harbor02,you must hava same version these,and what the storage you use?

**Comment by stonezdj** [comment]
There are two types data need to backup:
1. The database data, if backup/restore on same version postgres database, just copy the /data/database folder is ok, else you might need to use the pg_dump to backup databases following:
registry 
```
postgres -- if clair is used
notarysigner -- if notary is enabled
notaryserver -- if notary is enabled
```
The notary can not be retored because the signed information is also stored in local filesystem and bind to hostname.

2. Some password configuration is encrypted with key, you need to backup/restore the key file
`/data/secret/keys/secretkey`
