### ISSUE TITLE
Replicat harbor helm.hub.sh

### ISSUE THREAD

**Issue by nico0olas** [goharbor/harbor#13541]
After helm replication configuration I have this error 

Nov 18 16:41:16 172.19.0.1 core[1335]: 2020-11-18T15:41:16Z [ERROR] [/replication/operation/controller.go:103]: the execution 59 failed: failed to fetch charts: unmarshal chart list response error: invalid character '<' looking for beginning of value

I use Harbor v2.1.1

![Capture d’écran 2020-11-18 à 16 42 19](https://user-images.githubusercontent.com/65987283/99553196-279c1e80-29be-11eb-8efa-dd65ab29a370.png)

![Capture d’écran 2020-11-18 à 16 42 57](https://user-images.githubusercontent.com/65987283/99553212-2e2a9600-29be-11eb-9618-f4786ffa03df.png)

**Comment by discreet** [comment]
I am experiencing the same error when trying to replicate charts

**Comment by xaleeks** [comment]
helm hub recently migrated to artifact hub and broke our adaptor. Artifact hub will be supported in the next v2.0.4 release later next week

**Comment by discreet** [comment]
@xaleeks I see that v2.0.4 has a couple release candidates published. I'm a bit confused on the versioning though. I am running Harbor v2.1.1 right now. This would seem like a downgrade based on the version number.

**Comment by xaleeks** [comment]
So the latest _minor_ release is v2.1, or you can think of it as v2.1.x , and v2.1.1 is the first patch release since v2.1.  

In addition to this latest minor, we also maintain two older minor releases which would be v2.0.x and v1.10.x with their own patch releases until EOL or until the next minor releases (whereupon the 1.10 would be retired), so that's why you're seeing a 2.0.4 after the 2.1.1 because the 2.0 has been out for much longer.  They have no particular relationship between them and we usually try to port all major bug fixes and vulnerability patches to the actively maintained minor releases so this happens quite often.  But the v2.1.2 will also have the fix you're looking for

**Comment by steven-zou** [comment]
@discreet @nico0olas 

Post some clarifications here:

- hub.helm.sh has been sunset and we'll remove the corresponding adapter from the list in the next patch release (probably v2.1.2)
- artifact hub is a new artifact registry and we're trying to develop a new adapter to handle the replication between it and Harbor. The adapter will be available at V2.2.

**Comment by steven-zou** [comment]
Check issue: https://github.com/goharbor/harbor/issues/13365
