### ISSUE TITLE
GC doesn't seem to work.

### ISSUE THREAD

**Issue by peterjc85** [goharbor/harbor#13558]
GC doesn't seem to work.

Is it correct that GC deletes unrelated layer files in harbor?
I made a project and pushed an image of about 1G.
And I deleted the image from the harbor.
Also, GC was done after deleting the project.
However, a log of 0M deleted remains.

Are there any conditions for GC to operate?
GC doesn't seem to work.

**Comment by heww** [comment]
GC in v2.1 has a window time which is 2 hours by default, the images pushed in the window time will not be GC in v2.1 has a window time which is 2 hours by default, the images pushed in the window time will not be deleted in GC.

**Comment by peterjc85** [comment]
> GC in v2.1 has a window time which is 2 hours by default, the images pushed in the window time will not be GC in v2.1 has a window time which is 2 hours by default, the images pushed in the window time will not be deleted in GC.

Thank you.
What information does gc erase?
Images pushed 2 hours ago are not deleted,
Can images pushed before that time be deleted?
For example, you pushed the image 3 days ago,
Deleted / Deleted the project.
And if I run GC after that, will the layer of the pushed image be deleted?

**Comment by wy65701436** [comment]
you can get details from https://goharbor.io/docs/2.1.0/administration/garbage-collection/

`To avoid damaging the uploading artifact, the garbage collection introduces a time windows(2 hours) to reserve the recent uploaded layers. Garbage collection does not sweep the manifest & blob files that have a timestamp in the time window.`

Any layer with the update time within the time window, it will not be in the GC candidate, otherwise it will be in.
