### ISSUE TITLE
Tag retention policy doesn't work for Helm charts

### ISSUE THREAD

**Issue by eugentius** [goharbor/harbor#13564]
It seems like it is designed for Docker images only.
Any plans to include this feature to the future releases?

**Comment by heww** [comment]
I think we will not implement this feature in the future because the chartmuseum will be deprecated soon.

Suggest migrating your helm charts from chartmuseum to OCI registry which is supported by harbor from version 2.0. As an OCI artifact tag retention works well with it.

@ninjadq Can you share the way to migrate the helm chart in chartmuseum to OCI registry for us?
