### ISSUE TITLE
2ea harbor ui servers -> external DB -> ad authentication error (code 49)

### ISSUE THREAD

**Issue by peterjc85** [goharbor/harbor#13569]
2ea harbor ui servers -> external DB -> ad authentication error

There are 2 harbors.
Each harbor is connected to the same external DB, redis.
1. After setting ldap in harbor1, click test / save -> login to ad account in harbor1 server succeeded / failed in harbor2 (error 49)
2. After setting ldap at harbor2, click test / save -> login to ad account at harbor2 server succeeded / failed at harbor1 (error 49)

What is the problem?  
error >> Error occurred in UserLogin: Can not bind search dn, error: LDAP Result Code 49 "Invalid Credentials
Is the connection setting of ldap config wrong?
Is it a harbor bug?

**Comment by heww** [comment]
After setting ldap in one harbor, try to restart another harbor instance may fix this issue.

This issue happened may due to the limitation of the configuration manager.   @stonezdj

**Comment by stonezdj** [comment]
Harbor doesn't store password with encrypt, the harbor1 and harbor2 have different /data/secret/keys/secretkey, it makes the ecrypt failed on the other instances.

**Comment by peterjc85** [comment]
> 암호화를 사용하는 Harbor 저장소 비밀번호, harbor1 및 harbor2는 다른 / data / secret / keys / secretkey를 가지며 다른 인스턴스에서는 ecrypt가 실패합니다.

Yes, the secretkeys between the two servers are the same
Thank you

**Comment by stonezdj** [comment]
Sorry, the path of the secretkey might different for different Harbor version, what is your Harbor version?

**Comment by bienkma** [comment]
My harbor is version: v1.10.6; Docker version 19.03.13; docker-compose version 1.24.1, build 4667896b. We had installed harbor with nortary, clair and users authenticated by freeipa (ldap). My users got an issue, sometimes user login sucessful but cant push image to registry. core.log has error log bellow:
`Dec  1 00:01:18 172.26.0.1 core[1544]: 2020-11-30T17:01:18Z [ERROR] [/core/filter/security.go:439]: failed to authenticate autobuild: Failed to authenticate user, due to error 'LDAP Result Code 49 "Invalid Credentials": '
Dec  1 00:01:18 172.26.0.1 core[1544]: 2020/11/30 17:01:18.986 #033[1;44m[D]#033[0m [server.go:2774]  |   10.110.76.19|#033[97;42m 200 #033[0m| 1.542978568s|   match|#033[97;44m GET     #033[0m /service/token   r:/service/token
Dec  1 00:01:19 172.26.0.1 core[1544]: 2020/11/30 17:01:19.041 #033[1;44m[D]#033[0m [server.go:2774]  |   10.110.76.19|#033[97;43m 401 #033[0m|    31.9589ms|   match|#033[97;44m GET     #033[0m /v2/devops/sentry/manifests/latest   r:/v2/*
Dec  1 00:01:30 172.26.0.1 core[1544]: 2020/11/30 17:01:30.445 #033[1;44m[D]#033[0m [server.go:2774]  |   10.120.80.49|#033[97;43m 401 #033[0m|   7.122679ms|   match|#033[97;44m GET     #033[0m /v2/   r:/v2/*
Dec  1 00:01:30 172.26.0.1 core[1544]: 2020/11/30 17:01:30.519 #033[1;44m[D]#033[0m [server.go:2774]  |   10.120.80.49|#033[97;42m 200 #033[0m|  53.122996ms|   match|#033[97;44m GET     #033[0m /service/token   r:/service/token
Dec  1 00:01:30 172.26.0.1 core[1544]: 2020/11/30 17:01:30.572 #033[1;44m[D]#033[0m [server.go:2774]  |     172.26.0.6|#033[97;42m 200 #033[0m|   1.342187ms|   match|#033[97;46m POST    #033[0m /service/notifications   r:/service/notifications`
