### ISSUE TITLE
What's the relationship between artifact and tag?

### ISSUE THREAD

**Issue by duyanghao** [goharbor/harbor#13863]
![artifact1](https://user-images.githubusercontent.com/12867714/103256130-0835df80-49c7-11eb-9204-b243b9a294bf.png)
![artifact2](https://user-images.githubusercontent.com/12867714/103256138-0ec45700-49c7-11eb-8b0c-d888ed869da8.png)

I am confused about the relationship between artifact and tag for this [swagger api docs](https://editor.swagger.io/?url=https://raw.githubusercontent.com/goharbor/harbor/master/api/v2.0/swagger.yaml). It seems that artifact equals with tag, could someone help to explain it in detail?

Q2: Where is chart relevant apis?
This is the previous chart apis(harbor v1.7.0):
![chart1](https://user-images.githubusercontent.com/12867714/103256826-8d21f880-49c9-11eb-895c-25939d80771c.png)
Why these apis removed in the latest harbor v2.1.2?
![chart2](https://user-images.githubusercontent.com/12867714/103256857-acb92100-49c9-11eb-995b-23165b9f7bb3.png)

Q3: Where is /repositories/top apis?

**Comment by duyanghao** [comment]
![Uploading chart1.png…]()

**Comment by sluetze** [comment]
AFAIK:

Artifact vs Tag:
One Artifact may have multiple tags. You can upload an artifact and tag it with i.e. "latest", "v2", "v2.1", "v2.1-23asd52". So all this tags reference the same artifact.
Artifacts are identified by their digest (a sha256).

Chartrepo API:
I'm not a 100% sure about the following:
Since v2.0.0 Harbor is a OCI compliant Registry. Charts are OCI Artifacts. They are handled in the same way as i.e. images. there are no need for a seperate API for that, because one API can handle all artifacts.
In v.2.1.1 (i used this to take a look) the API is still there.


 /repositories/top API:
I don't know what this was for but there are some APIs which might help you here:
`/api/v2.0/statistics` delivers statistics to the repositories for the logged in user
`/api/v2.0/projects/{project_name}/repositories` might help you to get the repositories and metadata and create a toplist on your own
