### ISSUE TITLE
Vulnerabilities detected by "Trivy" image scanner 

### ISSUE THREAD

**Issue by gabrilabs75** [goharbor/harbor#13960]
Hi all,
these vulnerabilities were detected on latest argocd image present on docker hub by "Trivy" enabled on our Harbor installation:

CVE-2020-29362
Critical
libp11-kit0 0.23.15-2

CVE-2020-29363
Critical
libp11-kit0 0.23.15-2

When I pushed the latest image of argocd from docker hub to our registry "Trivy" detected the vulnerabilities above marked as "Critical".

The same vulnerabilites are marked "Medium" by vendors as we can see here:

https://ubuntu.com/security/CVE-2020-29363

Could you let us know something about this different result?

Thanks in advance.
Regards,
Gabriele

**Harbor Versions:**
Chart version : harbor-1.5.0
App version:    2.1.0

**Comment by danielpacak** [comment]
:wave: @gabrilabs75 Would you provide the image reference with image digest (e.g. `argoproj/argocd@sha256:abcdedf...` instead of `argoproj/argocd:latest`). The `latest` tag is mutable and therefore **not suitable** for reproduction.

The indicated version of Harbor is using Trivy v0.9.2. I did run a quick test on argoproj/argocd:v1.8.2 tag, which has the CVE mentioned, but it's reported that CVE-2020-29362 has MEDIUM severity whereas CVE-2020-29363 is HIGH (using CVSS v3.x).

Do you happen to run in air-gapped environment? Please **confirm when was the last update of vulnerabilities database** used by Trivy. You can check that in Harbor interface under Interrogation Service.

Note also that https://nvd.nist.gov/vuln/detail/CVE-2020-29362 has modification date of 01/11/2021 which might change the severity from CRITICAL to MEDIUM or HIGH. Please rescan the image and see if there's any change.

**Comment by danielpacak** [comment]
Closing as we cannot troubleshoot without requested info. If the issue persists please file an issue with enough details so we can generate vulnerability report and reproduce.
