### ISSUE TITLE
some scan report not found

### ISSUE THREAD

**Issue by bitsf** [goharbor/harbor#14158]
build: v2.2.0-rc1
1. enable auto scan
2. replication group goharbor from dockerhub
3. some scan report missing
![image](https://user-images.githubusercontent.com/188115/106754157-960c8680-6667-11eb-9151-bc1dc288b2ac.png)

![image](https://user-images.githubusercontent.com/188115/106754355-d79d3180-6667-11eb-819d-e6288b520c10.png)

**Comment by heww** [comment]
This happens when the artifact scanned again after we get the log link in the portal.
> We access the artifacts in the portal and get a link to the scan log for a specific scan report.
>
> Then the artifact scanned by the scheduled scan all job or by others, the existing scan report will be removed and a new report will be created.
>
> Now we will get a 404 when clicking the log link in the portal.

There are two methods to fix this issue:
1.  Always keep the scan report of the artifact, so we can always access the log of a specific report.
2. Introduce a new API of the scan log of the artifact which is scan report uncorrelated.

Both of them are not very perfect.
