### ISSUE TITLE
Unable to delete project 

### ISSUE THREAD

**Issue by gabrilabs75** [goharbor/harbor#14243]
Hi all,
I tried to delete project via api with helm chart charged on it but seems i can't  

``
$ curl -k -X DELETE https://<my_registry>/api/v2.0/projects/<project_id> -u "<admin_user>:"<admin_password> | jq -r
 
  "errors": [
    
      "code": "PRECONDITION",
      "message": "precondition failed: the project contains helm charts, can not be deleted"
``

Chart version: harbor-1.5.0                    
App version: 2.1.0

Is there a way to perform the action above?

Regards,
Gabriele

**Comment by sluetze** [comment]
You need to delete the helm charts in the repo first.

**Comment by gabrilabs75** [comment]
Hi,
In order to automate the process of decommission of user or tenant i supposed that existed other way to perform this action via DELETE API method.
Could you confirm that the only way should be delete helm chart from the Harbor console first?

**Comment by sluetze** [comment]
you can delete the artifacts in the project via API:
this is not only true for helm charts but also for images etc.

# get all artifacts
GET /projects/{project_name}/repositories/{repository_name}/artifacts
# loop over artifacts and delete them 
DELETE /projects/{project_name}/repositories/{repository_name}/artifacts/{reference}

IIRC you may need other endpoints when using chartmuseum.

**Comment by gabrilabs75** [comment]
Hi,
I need to delete the object present in "Helm Chart" section (not the images in repositories section) and I haven't found the correct syntax to GET what i need

Have you any further suggestion?

**Comment by sluetze** [comment]
Helm Charts can be saved in chartmuseum or as OCI Artifacts. 
OCI Artifacts are behind the endpoint I wrote. This artifacts can be Helm-Charts, Images, CNAB-Bundles... but that doesnt matter for your deletion, since you must delete ALL of them before deleting the project.

Im not sure, if repositories allow a direct deletion without deleting the artifacts. As far as i remember that's not the case. So to delete a project it must be "empty" (think of it like using `rmdir` in commandline on a directory. It will always fail, unless you removed everything in this directory).

So the safest way IMO would be:
1. List all Repositories in the project (`GET ​/projects​/{project_name}​/repositories`)
2. For each Repository
    1. List all Artifacts (`GET /projects/{project_name}/repositories/{repository_name}/artifacts`) 
    2. Delete the Artifacts (`DELETE /projects/{project_name}/repositories/{repository_name}/artifacts`)
    3. Delete Repository (`DELETE /projects/{project_name}/repositories/{repository_name}`)
3. If using chartmuseum, delete all charts of the repo too (i don't see any endpoint for that in current demo.goharbor.io, so it may be deprecated / unneeded)
1.  Delete Project (`DELETE /projects/{project_id}`)

**Comment by biomassa7x** [comment]
Hi,
So, if I have understood correctly, is not possible to delete an helm chart by API calls without using Chartmuseum, right?
