### ISSUE TITLE
Documentaition bug for upgrade to to major version and then rollback 

### ISSUE THREAD

**Issue by mohitsharma-in** [goharbor/harbor#14509]
Hi team,

We recently Upgraded to harbor 2.2.0 and we found out we cannot roll back to the previous version that is 2.1.3.

We would like to raise that it should be documented in a release note or something in the readme file so that we don't land up in issue the proper steps that involve the DB backup before the upgrade of the Harbor instance if it's on-prem DB and possibly add a script to backup data for Container based DB before upgrading and store it on Persistance storage.

**Comment by reasonerjt** [comment]
In the documentation, it's mentioned that backing up data is a must:
https://goharbor.io/docs/2.2.0/administration/upgrade/

do you have any suggestion to clarify that point?

**Comment by mohit94614** [comment]
Hey Daniel,

This Document [Upgrade Document](https://goharbor.io/docs/2.2.0/administration/upgrade/#upgrading-harbor-and-migrating-data) seems to more for the docker-compose installation. I would be more interested in Kubernetes deployment of harbor providing similar steps for migrating DB Backup or some script to backup and migrate data. If we can document steps for on-prem and pod Based HarborDB .

Moreover, if we can add the same in the release note also if this can be expected behavior, I couldn't find this as breaking change if we need to roll back to the last stable version due to any reason 

![image](https://user-images.githubusercontent.com/17672906/113095604-5b5f3e80-9211-11eb-91ee-9862b00b5aa1.png)
