### ISSUE TITLE
failed to authenticate harbor_registry_user

### ISSUE THREAD

**Issue by ghost** [goharbor/harbor#14605]
We have setup harbor(v2.2.1) on AWS ECS. 
We are able to login into Harbor portal with default admin/Harbor12345 credentials.
However when we try to login to harbor from docker using below command, we are getting "**Error response from daemon: login attempt to https://harbor.company.com/v2/ failed with status: 401 Unauthorized**".
**_Command: docker login https://harbor.company.com_**
 
When we check the harbor core logs, it says that "**failed to authenticate harbor_registry_user: Failed to authenticate user, due to error 'Invalid credentials'"**

Note: We have changed below harbor service URL's to our company specific URL's. (eg: **https://harbor-jobservice.company.com**)
(core, registry, jobservice, registryctl, portal, trivy-adapter) 
We are using AWS RDS and AWS Redis.

We can even see the Trivy-Adapter health check as Passed on Harbor Portal. (meaning harbor services are able to communicate internally.)

**Comment by AlverezYari** [comment]
Buddy and I are also seeing this on new helm install. We don't see anywhere to generate a token to use either. A bit confused on what we are missing or if its a  bug?

**Comment by welborntellis** [comment]
I wonder what encryption/logic is used to stored **harbor_registry_use**r in **/common/config/registry/passwd**. 
If we can find a way to change it, then it might work because the error is clearly saying _**harbor_registry_user has invalid credentials.**_ 
Also the values for variables **REGISTRY_CREDENTIAL_USERNAME(harbor_registry_user)** and **REGISTRY_CREDENTIAL_PASSWORD** in env file of core is different. 
I am wondering how the two i.e. **harbor_registry_user in commom/config/registry/passwrd and REGISTRY_CREDENTIAL_USERNAME in core env files are related**.

**Comment by heww** [comment]
Hi, @welborntellis can you check your configuration of the proxy to ensure that the https://harbor.company.com/v2/ request to the core component of the harbor not to the registry component?

The clients must never access the `/v2` of the registry component, they must access the `/v2` of the core component.

**Comment by heww** [comment]
Hi, @AlverezYari could you share the values.yaml with us to investigate your problem?

**Comment by welborntellis** [comment]
@heww we are using AWS Load Balancer for routing the traffic. I checked in the Load Balancer rules, we are routing the https://harbor.company.com/v2/ to core component and not to the registry component.

**Comment by heww** [comment]
Does `harbor_registry_user` is the username to login by the docker cli?
If so, please check your password, `Invalid credential` in the log means the username or password not match the record in the database. Could you try to use this credential to login the portal?

**Comment by welborntellis** [comment]
No, we are using the default admin/Harbor12345 credentials to login via the docker cli.
The same admin/Harbor12345 is working fine when trying to login to the harbor portal. bt if we try through the docker cli, we get: **Error response from daemon: login attempt to https://harbor.company.com/v2/ failed with status: 401 Unauthorized**
When we check the core logs, we find below:
**[ERROR] [/server/middleware/security/basic_auth.go:40][requestID="1d0f11c9-f89e-4daf-b9af-5a474ddf3306"]: failed to authenticate harbor_registry_user: Failed to authenticate user, due to error 'Invalid credentials'**

No idea why it is trying to login with harbor_registry_user when we enter admin/Harbor12345 in docker cli

**Comment by welborntellis** [comment]
@heww @reasonerjt i guess if we concentrate on the **harbor_registry_user** here, we might find something. 
The core logs clearly says Invalid credentials for **harbor_registry_user.**
Is there a way where we can modify the **harbor_registry_user** credentials and then try?

**Comment by welborntellis** [comment]
@heww @reasonerjt any updates?

**Comment by welborntellis** [comment]
I noticed something interesting. 
When I hit this api: _https://harbor.company.com/api/v2.0/systeminfo_

I get below response:

{auth_mode: "db_auth", external_url: "https://harbor.company.com",…}
auth_mode: "db_auth"
external_url: "https://harbor.company.com"
harbor_version: "v2.2.1-b0d63082"
has_ca_root: false
notification_enable: true
project_creation_restriction: "everyone"
read_only: false
registry_storage_provider_name: "s3"
**_registry_url: "harbor.company.com"_**
self_registration: false
with_chartmuseum: false
with_notary: false

Note the registry_url is same as my main harbor url. However i have configured my registry url as **_harbor-registry.company.com_**
I am assuming this might be the reason when i try docker login, harbor internally tries to login to registry url (which actually should be **_https://harbor-registry.company.com_**) with harbor_registry_user credentials and since the harbor registry url is configured as **_https://harbor.company.com_**(as in the above response) it is giving me invalid credentials error,

**Comment by AlverezYari** [comment]
> Hi, @AlverezYari could you share the values.yaml with us to investigate your problem?

@heww I asked about it this AM and sounds like the guy figured it out. Sounds like an issue with the helm chart is what ended up being the issue. This was his feedback:

> The helm chart requires htpasswd formatted registry credentials, not the raw password, that could be documented better shrug
> it was just so confusing that everything was working, but the harbor front-end couldn't talk to the registry at all as any user
> 

So sounds like we are good but perhaps this might help other folks out who also get stuck.

**Comment by welborntellis** [comment]
@AlverezYari can you help me with how to get the htpasswd formatted registry credentials?

**Comment by AlverezYari** [comment]
@welborntellis  again from my buddy who is working this problem...

> yeah i used a thing to bcrypt the password, then did a echo "user:bcrypt_password" | base64

> then replaced what the helm chart put in the REGISTRY_CREDENTIALS secret or w/e for the core with that

**Comment by reasonerjt** [comment]
@welborntellis 
please look for `registry.credentials.htpasswd` in the readme.md of harbor-helm repo:
https://github.com/goharbor/harbor-helm

The way it is configured is a bit confusing, I think there is an enhancement in sprig that is adopted by helm3 to support bcrypt, so once we drop the support for helm 2, the configuration may be easier. I need to doublecheck though.

**Comment by welborntellis** [comment]
@reasonerjt we are not using harbor helm. 
However we tried to create new credentials by using the command: `htpasswd -nbBC10 $username $password`. 
We used the username password from core's env file **REGISTRY_CREDENTIAL_USERNAME & REGISTRY_CREDENTIAL_PASSWORD**. We then placed the newly generated password in the config.yml

**Comment by welborntellis** [comment]
@reasonerjt we are not using harbor helm.
However we tried to create new credentials by using the command: `htpasswd -nbBC10 $username $password`.
We used the username password from core's env file **REGISTRY_CREDENTIAL_USERNAME & REGISTRY_CREDENTIAL_PASSWORD**. 
We then placed the newly generated password in the registry's config.yml: 
```
auth:
  htpasswd:
    realm: https://harbor-registry.company.com
    path: /etc/registry/passwd
```
still when we try to login through docker cli with **admin/Harbor12345**, we are getting the same error: **_failed to authenticate harbor_registry_user: Failed to authenticate user, due to error 'Invalid credentials'_**. 

When we try through portal, we are able to login successfully using **admin/Harbor12345**, its not clear why is it checking for harbor_registry_user when trying to login through docker cli using **admin/Harbor12345**.

**Comment by reasonerjt** [comment]
@welborntellis 
harbor-core see registry as a storage service, and they communicate via the`REGISTRY_CREDENTIAL_USERNAME`, `REGISTRY_CREDENTIAL_PASSWORD` and they must match the file `/etc/registry/passwd` in registry container.

Are you using the offline installer?
The install script should generate the passwd file automatically, see:
https://github.com/goharbor/harbor/blob/19e8527cc19b3bcd08363054d8797eecc0c67dc5/make/photon/prepare/utils/registry.py#L82

**Comment by welborntellis** [comment]
@reasonerjt we are using online installer. 
We tried with the default passwd file, no luck. 
We even tried to generate a new passwd using this command: `htpasswd -nbBC10 $username $password`
Still we are getting the same error.
Before deploying on ECS, we hade done harbor poc on an EC2 instance. There we were able to login via docker cli using admin/Harbor12345.

**Comment by reasonerjt** [comment]
@welborntellis 
Based on your description it's hard to tell which step is wrong.

But I think based on my comment, you are able to check if the env var in `harbor-core` matches the `passwd` file that is mounted to `registry` container?

**Comment by welborntellis** [comment]
@reasonerjt 
I tried below commands to generate the `passwd` file:
1. `htpasswd -nbBC10 $username $password`
2. `htpasswd -bcB /passwrd $username $password`
every time i execute the above commands, i get a different `passwd` file

**Comment by reasonerjt** [comment]
@welborntellis 
Sorry for the late response

You can use `htpasswd -v $file $user` to verify

**Comment by welborntellis** [comment]
@reasonerjt we identified a new thing...
If we point **/v2/** to **harbor-portal**, we are able to login to Harbor UI and through docker-cli.
However, when we point **/v2/** to **harbor-core**, we are able to login to Harbor UI but not able to login through docker-cli.
below are our harbor portal and harbor core URLs:
Harbor Portal URL: https://harbor.company.com 
Harbor Core URL: https://harbor-core.company.com

**Comment by dcherman** [comment]
I ran into this when trying to do the same thing yesterday, and I think I've figured out what's going on, at least in my situation.  The author (and myself) are both using reverse proxies / load balancers that route HTTP traffic based on the `Host` header in order to identify what backend it should send it to.

The biggest hint for what's been going wrong that I could find is that when this problem occurs, you see two attempts to authenticate - first would be a successful one from the username that you're using on the CLI, and the second would be a failed one with the username configured for the internal registry.  I checked and  re-checked my config to make sure I did not have something set incorrectly.  That led me to assuming that the traffic was not being routed to the service that I thought it was which ended up being a correct assumption.

Internally, Harbor proxies traffic to the registry via [`httputil.NewSingleHostReverseProxy`](https://golang.org/pkg/net/http/httputil/#NewSingleHostReverseProxy) (https://github.com/goharbor/harbor/blob/d1426fb0c5400bbff05c0a5c7eca2eff17dbabd5/src/server/registry/proxy.go#L35).

Looking at the documentation, it states that `NewSingleHostReverseProxy does not rewrite the Host header. To rewrite Host headers, use ReverseProxy directly with a custom Director policy.`. That led me to believe that event though my registry is on a completely different domain, the `Host` header was not being changed for proxied requests which meant that we were basically looping traffic back into the core service that was intended for the registry, and then auth was subsequently failing.

I confirmed that theory and have this fixed locally by running nginx in front of the core service with the following config (only including the interesting bits, not the full config):

```
    upstream server {
        server 127.0.0.1:8080;
    }

    upstream registry {
        server harbor-registry.mycompany.com:443;
    }

    server {
        location / {
            proxy_pass http://server/;
            proxy_pass_header       Authorization;
            proxy_set_header Host   $host;
        }

        location /__internal/registry/ {
            proxy_pass https://registry/;
            proxy_set_header Host harbor-registry.mycompany.com;
            proxy_pass_header       Authorization;
        }
    }
```

And then I've configured the `REGISTRY_URL` environment variable to be `https://harbor-core.mycompany.com/__internal/registry`.

NGINX takes care of routing the traffic to the registry that was intended to go there by setting the correct host header and proxying to to that service, and `docker login` subsequently succeeded.

Longwinded explanation, but hopefully this is helpful.  I'd suggest that maybe Harbor look at the URL that was passed in for the registry URL and set the `Host` header appropriately in that reverse proxy code which should fix this.

**Comment by welborntellis** [comment]
@dcherman Thanks for your answer. 
We are trying the same approach as yours. 

We have set proxy in front of core, where only the requests to **/v2/** and **/internal/registry** will be routed via the nginx proxy service to core service.

However our proxy is giving us below error:
`*1 ignoring stale global SSL error (SSL: error:25066067:DSO support routines:DLFCN_LOAD:could not load the shared library:filename(libz.so): libz.so: cannot open shared object file: No such file or directory error:25070067:DSO support routines:DSO_load:could not load the shared library) while SSL handshaking to upstream, client: 172.20.53.214, server: localhost, request: "GET / HTTP/1.1", upstream: "https://10.11.21.24:443/", host: "10.20.50.74:33111"`

Can you help us with this?

**Comment by dcherman** [comment]
Unfortunately I can't debug your specific scenario.  We terminate HTTPS/TLS at the Load Balancer, so our Harbor components themselves listen on plain old HTTP internally for the moment.

**Comment by ashish1099** [comment]
the problem would be the core pod has a diff credentials as compared to registry (/etc/registry/htpasswd)

I had the same issue, after fixing the htpasswd, it worked fine.
