### ISSUE TITLE
replication job unnormal sheduled sometime in 2.2.1

### ISSUE THREAD

**Issue by bitsf** [goharbor/harbor#14683]
release 2.2.1
replication job should be scheduled run once in an hour, however it sometimes start many same jobs in short time
1. normal regular job
![image](https://user-images.githubusercontent.com/188115/115195973-f87f0a00-a121-11eb-9d7f-8529d0dac28b.png)
2. after a failed at 9:01, there're 20 jobs started in 9:00 to 10:00, and running slowly
![image](https://user-images.githubusercontent.com/188115/115196076-18163280-a122-11eb-90ca-1ab5cb7b4596.png)
![image](https://user-images.githubusercontent.com/188115/115196453-7fcc7d80-a122-11eb-9428-b2de69f614dd.png)
3. at 15:01, it get even worse, more jobs started at once
![image](https://user-images.githubusercontent.com/188115/115196680-c6ba7300-a122-11eb-8c5e-d0baa5f406b2.png)
![image](https://user-images.githubusercontent.com/188115/115196800-e6519b80-a122-11eb-9a5c-d2036fc98c57.png)

**Comment by bitsf** [comment]
there're a lot of webhook resend logs in jobservice.log
it seems when one job failed accidentally, like jobservice container connect core container timeout, it would do retry, and if the network and cpu is still slow, it may trigger several jobs again.
we should avoid same job be triggered again.

**Comment by bitsf** [comment]
I try to recovery my env by
1. set all schedule job to manually
2. wait for some time before jobs done, or manually cancel them
3. enter redis container
docker exec -it redis bash
4. clean all running jobs
redis-cli -n 2 keys "{harbor_job_service_namespace}:executions*" | xargs redis-cli -n 2 del
redis-cli -n 2 keys "{harbor_job_service_namespace}:job_stats*" | xargs redis-cli -n 2 del
redis-cli -n 2 del "{harbor_job_service_namespace}:hook_events"
5. docker restart harbor-jobservice
6. config the schedule job again

**Comment by ywk253100** [comment]
The scheduled replication/retention/gc/scan-all are all triggered by the scheduler which is implemented by the underlying jobservice periodical job. When the scheduled time up, a checkin hook is sent to the scheduler(running in core) by jobservice and the scheduler calls the pre-registered callback function.  

The root cause of this issue is that if the scheduler receives the checkin request but doesn't response to the jobservice within 30 seconds, the jobservice considers the checkin operation failed because of timeout, and it sends it again later. This causes the scheduler receives multiple checkin requests for one schedule and creates duplicated execution records.
