### ISSUE TITLE
Guest users should not be able to see the list of all the project users and their roles.

### ISSUE THREAD

**Issue by lcastellano** [goharbor/harbor#1486]
Docker: 1.12.6
Compose: 1.11.1
Harbor: 0.5.0

**Comment by reasonerjt** [comment]
@lcastellano this is current design, we consider a "guest" in a project has "read" permission, this "read" permission includes reading other members and their roles in the project.

May I know you suggestion?

**Comment by mvdbr4nd** [comment]
To me it sounds bad that a guest user can see all the other users. imagine you give a customer pull rights by creating that customer as a guest. One option is to disable the viewing of those details for the guest role. (since that role is purely meant for pulling and updating passwords). Or we create an new role which only has pull rights and can no longer user the web-interface.
I might consider make this change (its pretty trivial) my self if you want to pull it when implemented that would be great. H

Hiding the users / roles and Logs would suffice as well btw still enabling the guest to make password changes.

**Comment by markvl** [comment]
We would like to use Harbor to distribute our Docker images to our customers. These customers would then have the guest role primarily to be able to pull the images. What we do not want is for them to be able to see all other users (customers) that have access to a project.

Related to the list of users, is the logs of a project. For our use case, we would not want guests to be able to see actions of other users.

**Comment by reasonerjt** [comment]
Thanks for the valuable feedback!

@mvdbr4nd could you please clarify what is "make password change"  does it mean the guest user can login to UI and change his own password?

**Comment by mvdbr4nd** [comment]
Well from a guest perspective i can image you want these type of users to be able to do that. Nevertheless I guess adding a role type that cannot use the UI at all would also solve the issue.  As what MarkvL mentioned it makes sense to be able to create users that can only pull images on certain projects and nothing else.

**Comment by akshayl** [comment]
It sounds like the proposal is to add a new role with permissions that only allow pull access to images and the ability to change password. What about listing images? Perhaps we could call such a role "Guest (Restricted)"?

**Comment by markvl** [comment]
I think listing images would be useful. I also like the name you suggested, "Guest (Restricted)".

**Comment by markvl** [comment]
This would still be a useful feature to have.
