### ISSUE TITLE
Documentation for harbor webhook replication notifications

### ISSUE THREAD

**Issue by aandvalenzuela** [goharbor/harbor#14865]
Hi!

On the CernVM team we want to use Harbor's webhook notification system together with one of our components. 

I am currently parsing the JSON notifications, and I was wondering if you have more information regarding the tags involved in the replication notification and their mandatory or optional presence. I have found documentation related to the pushed artifacts (https://goharbor.io/docs/2.2.0/working-with-projects/project-configuration/configure-webhooks/), but the replication notifications are slightly different.

Thank you for deploying such useful system,
Andrea.

**Comment by drehpehs** [comment]
Hi, we are also using webhook notification of the replication to trigger some afterwards tasks.

Sometimes the replication (event_based) could be failed even after its retry due to temporary network issue. We would like to log the Failed replications and replicate them in some other time. But currently the webhook json only has the **name_tag** in event_data.successful_artifact/failed_artifact. And we need to compare the execution_timestamp to figure it out the target artifact. I think it will be helpful if we can have the **tag** information.

Besides, we found if there are multiple layers(paths) of the artifact, it just returns the first layer, instead of whole artifact.
- project/dummy  =>  `"name_tag": dummy [1 item(s) in total]`
- project/bar/dummy =>  `"name_tag": bar` (expectation: bar/dummy)
- project/foo/bar/dummy => `"name_tag": foo` (expectation: foo/bar/dummy)

Can we also have the full path of the artifact in the replication webhook json?
Thank you.

**Comment by drehpehs** [comment]
Excuse me, any update on this?

**Comment by aandvalenzuela** [comment]
Still waiting for the documentation

**Comment by wy65701436** [comment]
we should have the doc to describe for each kind of webhook.

**Comment by batusekerci** [comment]
We are also waiting for this.

**Comment by for-code-sake** [comment]
Still waiting for the documentation
