### ISSUE TITLE
Webhook cannot notify "docker pull" event with docker 20.10.5

### ISSUE THREAD

**Issue by t-matsuo** [goharbor/harbor#15068]
**Expected behavior and actual behavior:**

Webhook notifies "docker pull" event.

**Steps to reproduce the problem:**

1. enable webhook
2. docker pull my-image    <- First pull is OK
3. docker pull my-image    <- Second pull is NG

**Versions:**

harbor version: [2.2.1]
docker engine version: [20.10.5]

**Additional context:**

It seems  root cause is same as #15035

**Comment by wy65701436** [comment]
@t-matsuo good catch, thanks. I'll fix it in v2.3.

**Comment by reasonerjt** [comment]
@wy65701436 
I'm a little confused about how it can be fixed, the audit record is added if the content is "served" but in docker's case, it sends a HEAD request, and stops if it exists locally.  
From the registry's perspective, it should not add an audit log if it handles a HEAD request

I wish to suggest we have more discussion over this and very likely it can't be fixed in v2.3

**Comment by t-matsuo** [comment]
I found a bug that it can't be output pulling log.
Should I file another issue ?
