### ISSUE TITLE
OIDC code to token exchange failure after C-NAME change

### ISSUE THREAD

**Issue by Cyben** [goharbor/harbor#15103]
Hey, 
I configured my harbor to work with an identity provider (Keycloak) with the Authorization Code Flow,
The identity provider has a C-NAME record for DR and sometimes the C-NAME is getting changed.
The C-NAME record is configured in a DNS out and DNS in servers.
When doing a switchover there is a mismatch between the two DNS servers for about a minute due to the time it takes the changes to propagate to the DNS servers.
We can see that right after the DNS switchover the "code to token" exchange in the OIDC flow is failing with the next error:
```
{"errors":[{"code":"BAD_REQUEST","message":"oauth2: cannot fetch token: 400 Bad Request\nResponse: {\"error\":\"invalid_grant\",\"error_description\":\"Code not valid\"}"}]}
```
The problem is that this error is shown for more than 1 minute after the switchover, and most times takes at least 5 minutes and even more when both DNS servers are already synced.

Seems that it fails here:
https://github.com/goharbor/harbor/blob/896327a8454e92f8ca9b426542d6d8fb4fcbbec7/src/vendor/golang.org/x/oauth2/internal/token.go#L239https://guides.github.com/features/mastering-markdown/

We have recreated a similar issue by changing the /etc/hosts on a local machine and back to the original record, by doing this, we created a mismatch between both DNS servers, in this case we could see the same issue but it was easily solved by clearing the browser cache.

> Changing the /etc/hosts on the local machine is analogous to changing the DNS out record

We wonder if there is any cache mechanism in harbor that could cause this issue? Or is it something else entirely.
Also we would like to know if you have an idea of how can we reproduce the issue by controlling the DNS resolution inside the harbor containers.

**Comment by aofekiko** [comment]
> We wonder if there is any cache mechanism in harbor that could cause this issue? Or is it something else entirely.
Also we would like to know if you have an idea of how can we reproduce the issue by controlling the DNS resolution inside the harbor containers.  

Any comment from the devs about these questions so we could try to reproduce the problem better?

**Comment by reasonerjt** [comment]
Hi, this error:
```
400 Bad Request\nResponse: {\"error\":\"invalid_grant\",\"error_description\":\"Code not valid\"}"}]}
```
Seemed to have been returned by the OIDC provider, could you please check why the server returns 400?

**Comment by aofekiko** [comment]
> I tried updating the /etc/hosts but did not reproduce this error. 

Did you change the /etc/hosts on your local machine (using the browser) or did you change it on the machine running the harbor instance? you need them to be 2 different machines for this to work.  
Also make sure you first connect using "Login via OIDC" before editing the /etc/hosts, then try logging in the same way.
This should reproduce the same result but instead of a mismatch from the harbor side, this time we are recreating it from the browser side using its caching mechanisms.  
For a full reproduction you will need 2 OIDC providers and do a real C-NAME change between them.

  
> Did click the "Login via OIDC" button after the DNS switch?

Yes, i also made sure to clear any cookies and used incognito.


> could you please check why the server returns 400?

This is because Harbor tries to access the old DNS record even after the switchover is made (Which is why we suspect a caching mechanism), while the browser is trying to access the new DNS record, this means that the browser returns to harbor an authorization code that is not valid inside the old OIDC provider.   

We expect to see both requests from harbor and the browser reach the same OIDC provider for a correct authorization code flow.


> Also we would like to know if you have an idea of how can we reproduce the issue by controlling the DNS resolution inside the harbor containers.

We'd still like to know if there is a way to control the DNS resolution inside the harbor container, if we have that capability then we'd easily be able to find a fool-proof reproduction of the issue.

**Comment by reasonerjt** [comment]
> We'd still like to know if there is a way to control the DNS resolution inside the harbor container.
I don't think Harbor's code controls DNS resolution.  Could you double-check by running commands inside the `harbor-core` container to check if the same DNS name is resolved to the new IP address after you do the switch?  
I currently have limited bandwidth, could you please confirm that via the command line the same DNS name points to the new IP address, while the code in `harbor-core` container still tries to connect the old OIDC provider?  If we can narrow down the issue on your side that the problem does happen in the code of Harbor.  I will set up 2 OIDC instances and try to reproduce again.
