### ISSUE TITLE
Log rotation of pulls and replication over a period of time 

### ISSUE THREAD

**Issue by mohitsharma-in** [goharbor/harbor#15179]
This is a feature request to make sure that older logs are deleted after a period of time that can be defined from harbor UI or automatically.

This is specifically needed when the harbor footprint is huge and multiple replication jobs are configured. 
So that logs are very high and can slow down the harbor performance

**Comment by yanji09** [comment]
There is a ticket for your reference https://github.com/goharbor/harbor-helm/issues/792

**Comment by yanji09** [comment]
What kind of logs do you want to delete?

**Comment by mohit94614** [comment]
i am looking docker pull/create operation logs along with replications logs 
For example below logs are very hugs and it's difficult to search and find specific logs since it covers all the logs and it will take lot of time to load as well.  
![image](https://user-images.githubusercontent.com/17672906/123610001-cc68bf00-d81d-11eb-8688-3adc6178f537.png)

**Comment by yanji09** [comment]
This seems a new requirement for rotating these kind of log from database.

**Comment by stonezdj** [comment]
see https://github.com/goharbor/harbor/pull/16914
https://github.com/goharbor/harbor/pull/16833
