### ISSUE TITLE
Concurrent performance very bad - 3000 concurrent push

### ISSUE THREAD

**Issue by lovelly** [goharbor/harbor#15299]
![image](https://user-images.githubusercontent.com/13118848/125065697-b6dc7a80-e0e4-11eb-80f7-de101877396d.png)

I simulate 3000 clients push 5M size image at the same time, the PG database is blocked.
I got a 500 error on the client
![image](https://user-images.githubusercontent.com/13118848/125066028-1dfa2f00-e0e5-11eb-9811-3d79e5c65446.png)

**Comment by heww** [comment]
Try the following steps if you want to test the pushing in 3000 concurrent:
1. Increase the `max_connections` of the Postgres so that it can accept 3000 connections at the same time.
2. Increase the `max_open_conns` of the core if you have only one core component instance, otherwise increase the instances of the core component.

BTW, the core component will be blocked when the DB requests more than the `max_open_conns` at the same time.

**Comment by lovelly** [comment]
@heww 
I configured 
```
max_connections=10000
max_open_conns=0
```
before this
