### ISSUE TITLE
Replication to Cross-account AWS ECR 

### ISSUE THREAD

**Issue by Axory** [goharbor/harbor#15388]
Hi, I'm not sure if this is a bug or a misconfiguration

**Version:**
v2.2.1-b0d63082
Running on kubernetes 1.18 with helm chart installation

**Problem Description**
I'm using Harbor to replicate docker images to AWS ECR. But the ECR that I'm using now is a cross AWS account to another AWS account ECR. For example, my AWS Account ID (111111111111) will login to AWS Account ID (222222222222) ECR. So, I configred the Harbor endpoints to https://222222222222.ecr.aws.com using AWS account ID (111111111111) ACCESS_KEY and SECRET_KEY. Here is the error that I got when I run the replication

![image](https://user-images.githubusercontent.com/42871652/128361362-7a4ccd21-691a-4043-97db-b79fd39e94e9.png)

It says that **RepositoryNotFoundException: The repository with name core/migration does not exist in the registry with id 111111111111**

If I run the aws cli manually, I'm able to access to the cross account ECR registry using my own AWS Account ID. 

> aws sts get-caller-identity
> {
>     "UserId": "AAAAAAAAAAAAAAAAAA",
>     "Account": "111111111111",
>     "Arn": "arn:aws:iam::111111111111:user/ecr-user"
> }

> aws ecr get-login-password | docker login --username AWS --password-stdin 222222222222.dkr.ecr.ap-southeast-1.amazonaws.com
> WARNING! Your password will be stored unencrypted in /home/xxxx/.docker/config.json.
> Configure a credential helper to remove this warning. See
> https://docs.docker.com/engine/reference/commandline/login/#credentials-store
> 
> Login Succeeded

**Expected behaviour**
The replication rule should honor the registry endpoints that I entered (222222222222.dkr.ecr.ap-southeast-1.amazonaws.com) instead the harbor is looking at my own AWS Account ID (111111111111) ECR.

**Comment by phin1x** [comment]
this is a bug.

the root cause is that the ecr uri is only used to get the region. the actual ecr endpoint is a return paramter from the [getAuthorization](https://github.com/goharbor/harbor/blob/28596c3ffb04edebb39ce56b1b8f1d2b1f44ec65/src/pkg/reg/adapter/awsecr/auth.go#L127) function. this method uses the go aws sdk to get the authorization data for ecr (endpoint and token) but the aws sdk only returns the ecr endpoint for the current account. so you are not able to push to a cross account ecr at the moment.

one fix could be to pass the ecr url from the database model to the [getAwsSvc](https://github.com/goharbor/harbor/blob/77b44a62e71d21866711760be075abe2635974bb/src/pkg/reg/adapter/awsecr/adapter.go#L51) function. the other fix would be to set the RegistryId Paramter in every aws sdk call.

**Comment by bitsf** [comment]
Is this a common case that you need to use such cross-account of AWS ?

**Comment by msjo66** [comment]
Yes, AWS recommends multi-account strategy for Enterprise.

**Comment by geowalrus4gh** [comment]
We are also having this requiement as per our operations standards following AWS Multi account architecture. We have a central AWS Management account and different organisational accounts for different units. Harbor is installed in management account.  For production use Container images are replicated to a SaaS acount which is not permitted to use ACCESS ID and Secret. So we have to replicate images to SaaS account from Harbor using instance profile itself. Replication works with remote account with only Access ID and Secret. We are unable to use replication at the moment due this issue.
