### ISSUE TITLE
Projects admins can't add groups to projects when using LDAP

### ISSUE THREAD

**Issue by squashedlime** [goharbor/harbor#15432]
We are using Harbor 2.3.0 together with LDAP for authentication. We are finding that project admins can't add groups to projects and only Harbor admins can add groups. 
When a project admin clicks the group button only a spinning circle appears as if there is no response or time out. When performing the same procedure as a harbor admin the popup works as expected.

<img width="858" alt="Screenshot 2021-08-16 at 09 31 44" src="https://user-images.githubusercontent.com/8925667/129527281-894a3777-ac34-4d5d-99fb-dd2ad3aaba32.png">

Looking at the browsers developer console we can see that a call to /usergroup fails with a 403.
Manually calling the usergroup function from the API-helper results in the same 403.
 
We are not seeing any errors in the Harbor logs, or any kind of logging related to the action.
Is this by design or is it a possible misconfiguration on our side?

**Comment by pashcan** [comment]
Seeing the same issue in our setup. For us it also doesn't allow Harbor admin users to add Project Admins via `Add a group from LDAP to project member` option. Providing full DN and submitting just gets you `internal server error` via UI and `Failed to load resource: the server responded with a status of 500 ()` from `/api/v2.0/projects/<projectid>/members:1` end point.

**Comment by stonezdj** [comment]
Yes, it is as-design, user groups is a system-level resource and cannot assign to project admin.

**Comment by squashedlime** [comment]
Thanks for the response, I guess that this can be classified as a bug as users that shouldn't have access can click the add "group member button"?

**Comment by stonezdj** [comment]
Yes, base on the current privilege check, the "Add an existing user group to project member" should be available for sys admin user.

**Comment by stonezdj** [comment]
> Seeing the same issue in our setup. For us it also doesn't allow Harbor admin users to add Project Admins via `Add a group from LDAP to project member` option. Providing full DN and submitting just gets you `internal server error` via UI and `Failed to load resource: the server responded with a status of 500 ()` from `/api/v2.0/projects/<projectid>/members:1` end point.

It returns the status of 403

**Comment by pashcan** [comment]
@stonezdj I am getting a 500 reply to the POST on `api/v2.0/projects/<id>/members` and the harbor log has: 
`2021-08-17T07:15:17Z [ERROR] [/lib/http/error.go:54]: {"errors":[{"code":"UNKNOWN","message":"unknown: a LDAP user group with same DN already exist"}]}`
Harbor version v2.3.0-047b122c. I am an admin user through a dedicated `LDAP Group Admin DN`.

Possibly this should be a separate issue altogether and is not just related to error message not propagating to the UI. Users should be able to add Group membership via explicit DN even if the Group has already been ingested into Harbor.

Regardless of these issues, Harbor should have functionality to allow non-admin users or at least users with Project Admin role within a project they created to add Project Admin Group membership. Not having this ability creates a huge bottleneck for admin users who should be focusing on managing overall Harbor configurations instead of micromanaging hundreds of individual project. Maybe this should be a separate issue as well, please advise.
