### ISSUE TITLE
Project quota smaller that actual size of image 

### ISSUE THREAD

**Issue by mohitsharma-in** [goharbor/harbor#15615]
Project quota smaller that actual size of image
harbor v 2.1.3 
![image](https://user-images.githubusercontent.com/17672906/133884605-f4420136-2dca-4090-b652-0c5f2f2a0155.png)

**Comment by Vad1mo** [comment]
This is not enough information to reproduce the error?

**Comment by mohit94614** [comment]
@Vad1mo I'm not sure how to reproduce it but i see similar output in summary api call

`{"developer_count":11,"guest_count":1,"limited_guest_count":1,"maintainer_count":1,"project_admin_count":8,"quota":{"hard":{"storage":1610612736000},"used":{"storage":1623012883806}},"repo_count":251}`

Ideally, this should not be allowed in any case 
used storage can't be greater that hard storage limit defined.

**Comment by heww** [comment]
> @Vad1mo I'm not sure how to reproduce it but i see similar output in summary api call
> 
> `{"developer_count":11,"guest_count":1,"limited_guest_count":1,"maintainer_count":1,"project_admin_count":8,"quota":{"hard":{"storage":1610612736000},"used":{"storage":1623012883806}},"repo_count":251}`
> 
> Ideally, this should not be allowed in any case
> used storage can't be greater that hard storage limit defined.

The system admin can modify the hard storage less than the used storage for a project, the result is that no images can be pushed to the project. This is by design.

**Comment by mohit94614** [comment]
I totally understand this is by design but it should not allow admin to scale quota lesser that used quota.

I hope this makes sense.

**Comment by Vad1mo** [comment]
No it make no sense, Why not? What should happen in the case if the admin can't set the quota below the size? 

1. Remove alls images in order to get to 1 TB?
2. Don't allow to set the value and talk to the project owner to eventually do the cleanup. (Which never happens) to find out weeks later that the project is already 2TB over the 1 TB the admin wanted to set and can't?

All you proposals are limiting the power of the admin and the admin can't do anything about them. 

In the current approach, the admin has the power to set the limit, and the user has to clean up the project in order to continue to push images or talk to the admin and figure out an exception. 

What you are proposing sounds noble in theory, but does not work in practice.   

I hope this makes sense.

**Comment by wy65701436** [comment]
And BTW, you can see it as a shortcut for admin to disable push(upload) for a specific project.

**Comment by mohit94614** [comment]
This makes sense. It's a feature rather than saying as a issue or bug. 

But can this allow admin to push images even if the quota is full? 

as originally reported we are seeing this and I'm pretty sure that none of the admin would have downsized the quota.
We are replicating the image from the Primary harbor instance (having retention jobs )to the secondary same quota is maintained on primary and secondary harbor instances.  Can replication do this 

![image](https://user-images.githubusercontent.com/17672906/134541215-ba6f48d1-25bb-4f6d-9046-c3f42ad7e779.png)
