### ISSUE TITLE
Document process for building binary for `registry-photon`

### ISSUE THREAD

**Issue by marcin-je** [goharbor/harbor#16036]
What can we help you?
It's not clear how the binary for `registry-photon` is built. At the moment, when running a build it fetches a binary from an online location: `REGISTRYURL=https://storage.googleapis.com/harbor-builds/bin/registry/release-${REGISTRYVERSION}/registry`. It's not clear from the documentation and Makefile how this is being built and published. This may raise a supply chain attack questions for potential users.

**Comment by wy65701436** [comment]
The binary is built in each PR merge, rather than fetching from the google storage. The URL is stored a fixed version, and no longer used. Generally, it was built base on source code and fix patches.

We will add more coments for Makefile, and the [BUILDBIN](https://github.com/goharbor/harbor/blob/main/Makefile#L85) is the swticher to indicate whether to build binary from source.

**Comment by marcin-je** [comment]
Thank you @wy65701436 that helps greatly, much appreciated 👍

**Comment by wy65701436** [comment]
PR to doc or update comments is welcome. @marcin-je
