### ISSUE TITLE
Retention : undesired tags are deleted when repositories matching filter is too large

### ISSUE THREAD

**Issue by yogeek** [goharbor/harbor#16065]
**Expected behavior and actual behavior:**

These 2 rules :

- `For the repositories matching **, retain the most recently pushed 20 artifacts with tags matching ** with untagged`
- `For the repositories matching **, retain always with tags matching PREFIX1_*,PREFIX2_*,latest`

lead to some `PREFIX1` deletion, which should be prevented by the 2nd rule.

However, if I add 2 additional rules with a more restricted repo filter, by executing these 4 rules :

- `For the repositories matching **, retain the most recently pushed 20 artifacts with tags matching ** with untagged`
- `For the repositories matching **, retain always with tags matching PREFIX1_*,PREFIX2_*,latest`
- `For the repositories matching repo1/**, retain the most recently pushed 20 artifacts with tags matching ** with untagged`
- `For the repositories matching repo1/**, retain always with tags matching PREFIX1_*,PREFIX2_*,latest`

all `PREFIX1` are retained, as desired

It seems that the `**` is causing the rules to be badly executed and delete some undesired tags.

Additional information : the project contains around 75 repositories, some of them with more than 2000 artifacts.

**Versions:**

- harbor version: [2.2.2]
(deployed with helm on EKS cluster 1.20.7)

**Comment by bitsf** [comment]
Hi, I didn't reproduce your issue with harbor 2.2.2.
And based the algorithm, repositories filter actually would not affect the tags retention logic, because we split job into concurrent tasks by repositories, each task will filter the tags separately. So if a repository is not matched, it would not run the task at all.

You said `some PREFIX1 deletion`, I'm not sure if this is a typo, as it should be `PREFIX1_`

I didn't hear about others report similar issue yet, so please do check your ENV again.

**Comment by yogeek** [comment]
We are currently trying to reproduce this with a test instance by creating a lot of tags.
I will post the results as soon as possible.

(about your question, yes indeed, it was `some PREFIX1_` deletion).

**Comment by yogeek** [comment]
Update : @bitsf 
in fact, this issue seems to come from the Harbor Terraform provider we use. 
Here is the link to the issue : https://github.com/BESTSELLER/terraform-provider-harbor/issues/182
