### ISSUE TITLE
Trivy adapter ssl handshake error 'unsafe legacy renegotiation disabled'

### ISSUE THREAD

**Issue by geowalrus4gh** [goharbor/harbor#16254]
Am using harbor 2.4.1. while scanning using trivy adapter am getting the following error. Am trying this behind my organization's firewall. I added the firewall CA certificate to the deployment as per the harbor document and I can see the certificate is added to the ca-bundle.crt. 

* Connected to api.github.com port 443 (#0)
* ALPN, offering http/1.1
*  CAfile: /etc/pki/tls/certs/ca-bundle.crt
* TLSv1.0 (OUT), TLS header, Certificate Status (22):
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS header, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (OUT), TLS header, Unknown (21):
* TLSv1.2 (OUT), TLS alert, handshake failure (552):
* error:0A000152:SSL routines::unsafe legacy renegotiation disabled
* Closing connection 0
curl: (35) error:0A000152:SSL routines::unsafe legacy renegotiation disabled

Is it due to the openssl version mismatch between trivy adapter container and the firewall ? I can see openssl installed in the trivy container is 3.0 and assuming its using TLS1.3 by default. is there any way to test it with version 1.2 to confirm if the issue is due to TLS version mismatch ?

**Comment by danielpacak** [comment]
The adapter service is not directly connecting to GitHub to fetch vulnerability database. The only [TLS config](https://github.com/aquasecurity/harbor-scanner-trivy/blob/v0.28.0/pkg/http/api/server.go#L35) that it has is to enable TLS for its HTTP server.

It looks to me like Trivy cannot connect to GitHub through your proxy due to some handshake failure.

I'd start with setting the SCANNER_TRIVY_INSECURE environment variable in the Trivy Adapter container to skip certificate verification. However, I'm not sure if this config is used for vulnerability database downloads as well as for pulling container images.

Another test is to see if you can run Trivy (standalone) binary behind your firewall and confirm that it works:

```
trivy image alpine:3.15
```
