### ISSUE TITLE
Certificate chain issues

### ISSUE THREAD

**Issue by arojojoyea** [goharbor/harbor#16530]
After upgrading from harbor v1 to v2.4.1, we noticed that the SSL certificate we bought and use is not trusted by ubuntu. We tried to create a certificate chain (including the root CA) for harbor to use, but the results never reflect the certificate chain that was set, even after stopping and restarting harbor with docker-compose. Is it possible that harbor caches the certificate in a separate location? What could be the reason for the new certificate chain not reflecting after the change?

**Comment by stonezdj** [comment]
could you please give us the detail steps on how you replace the certificate in Harbor? 
Harbor doesn't cache any certificate. 
AFAIK, the certificate chain means the root ca, and the server.key and server.crt should be generated with this certificate chain, after generated, only server.crt and server.key is used, their path should be placed in the harbor.yaml and run the install.sh again so that it could be applied to the configuration. the certificate chain is not used any more.
For the client-side, it should trust the root ca and the certificate chain.
