### ISSUE TITLE
2.5.0 to 2.5.1 migrate script - no need to upgrade

### ISSUE THREAD

**Issue by calcium90** [goharbor/harbor#17017]
I'm getting this when running the migrate script on my 2.5.0 config when upgrading to 2.5.1, is this expected? The wording implies the upgrade target is 2.5.0.

```
# docker run -it --rm -v /:/hostfs goharbor/prepare:v2.5.1 migrate -i /etc/harbor/harbor.yml
Version of input harbor.yml is identical to target 2.5.0, no need to upgrade
```

Just to confirm this is indeed my config from 2.5.0:

```
# grep "_version" /etc/harbor/harbor.yml
_version: 2.5.0
```

**Comment by MinerYang** [comment]
For patch release, no need to migrate the harbor.yml, (generally speaking, there's no difference between the harbor.yml file of v2.5.0 and v2.5.1, we just doing some updates and issue fix in these patch release which would not affect the harbor.yml file ).
you can use the same `harbor.yml` file for v2.5.0 to install v2.5.1 by downloading the new tarball and install it directly.
BTW, this `_version: 2.5.0` is by design to find the version when you need to migrate. So it is correct and no need for you to modify it.
