### ISSUE TITLE
LDAP login timeout 

### ISSUE THREAD

**Issue by pavanfhw** [goharbor/harbor#17041]
I have an LDAP server for my Harbor installation authentication. I can login to the UI with no problems, although it is slow (around 20 seconds). But I can't login to my resgistry via docker CLI (`docker login harbor.my.company`) so I can push/pull images. I get the following error:

```
Error response from daemon: Get https://harbor.my.company/v2/: Get https://harbor.my.company/service/token?account=felipe.pavan&client_id=docker&offline_token=true&service=harbor-registry: net/http: request canceled (Client.Timeout exceeded while awaiting headers) (Client.Timeout exceeded while awaiting headers)
```
I'm guessing it is an actual timeout error (not other errors I found in other issues), because logging in to my Authentik LDAP server takes more than 15 seconds which appears to be the timeout value. Is there a way to resolve this that is not speeding up the login process?

**Comment by stonezdj** [comment]
What is your installation type docker-compose or k8s?
If the timeout issue is caused by the LDAP login, then we should hit the same issue both the web UI login and cli login.
could you please verify if the admin user could login via docker cli ? because the admin doesn't need to connect to the LDAP server. if it fails with the same error, then it should be a configuration with your Harbor.  please check your external_url variable in harbor-core container.

**Comment by pavanfhw** [comment]
The installation is via docker-compose.
And yes, the only user able to login via CLI is the admin. But all users con login via UI.

**Comment by pavanfhw** [comment]
@stonezdj any ideas to solve this problem?

**Comment by stonezdj** [comment]
How long it takes the timeout? exceed 900 seconds? if yes, then we could try to update the timeout setting in common/config/nginx/nginx.conf 

```
    location /v2/ {
      proxy_pass http://core/v2/;
      proxy_set_header Host $http_host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $x_forwarded_proto;
      proxy_buffering off;
      proxy_request_buffering off;
      proxy_send_timeout 900;
      proxy_read_timeout 900;
    }
```

**Comment by kenyon** [comment]
Related: https://github.com/moby/moby/issues/44350

**Comment by ansromanov** [comment]
I've also experienced a slow UI login, taking about 10-15 seconds, alongside delayed API requests when LDAP authentication mode is on. I've tested this on Harbor v2.9.4-a6d707df both in Docker and Kubernetes installations.
LDAP server querying with `openssl s_client` and `ldapsearch` show no latency problems.
However, this slowdown seems to occur only when LDAP group filtering is activated, and this issue is possibly linked to the issue documented at https://github.com/goharbor/harbor/issues/20038.

I use the following LDAP configuration (some fields are changed by the security reasons)
![image](https://github.com/goharbor/harbor/assets/1626964/acd369d6-d4d7-4f8d-9409-1d2b32f09da2)

**Comment by ansromanov** [comment]
@stonezdj could you kindly reopen this one?

**Comment by g0ha1** [comment]
After several hours of research, I believe the problem is as follows:
Harbor retrieves user data from the LDAP server and then loops through the LDAP server for data for each LDAP group. This works fine if there are two or three groups, but if there are dozens or hundreds of them, until iterates through them all (and it creates a new session for each request, rather than working within an existing one), the user won't be able to log in, resulting in a timeout during docker login and authorization in the web interface.

A solution could be to separate the user authorization process from the process of verifying their group membership. Let's say there's a built-in task for synchronizing groups and checking the membership of existing users in these groups, then this information will always be up-to-date. And there's an LDAP authorization process that doesn't check group membership and there are no timeouts!

A half-measure could be to optimize the process of communication with the LDAP server in such a way that for each new request (creation of a secure connection, bind under a service user, request, connection termination) the harbor does not create a new session, but continues to work in the existing one.
Sorry, fixed in https://github.com/goharbor/harbor/releases/tag/v2.12.0 i tested on 2.10
