### ISSUE TITLE
[tag-retention] keep release and delete RCs

### ISSUE THREAD

**Issue by Pictor13** [goharbor/harbor#17136]
I'm trying to setup Tag Retention policies for a repository.  
The purpose is to:
- always retain (release) tags matching `v*` (e.g. `v1.0.2-1234`)
- remove RC (release candidate) tags matching `v*rc*` (e.g. `v1.0.2rc3-1234`)

The two rules created are:
> For the repositories matching app, retain the most recently pushed 0 artifacts with tags excluding *rc*
> For the repositories matching app, retain always with tags matching v*

The 2 policies work correctly when set independently.
But when used together seems like the first (including) rule overrides the second (excluding) one.
I tried to invert the order of the rules, but the result is the same.

_How can I implement the policies so tagged released are retained & release-candidates are purged?_

**Comment by chlins** [comment]
The logic relationship between the rules is `OR` that means since the tag matches one rule for retention then will be retained, in your case the rc tag like `v1.0.2rc3-1234` also can be matched by `v*` so it will be retained. It's not easy to setup two rules to satisfy your purpose, you can just use one rule to match `v?.?.?[^r][^c]*` which can keep `v1.0.2-1234` and remove `v1.0.2rc3-1234`, but notice here the symbol `?` can only match single char so if your tag like `v11.11.11`, the rule should be modified to `v??.??.??`.
