### ISSUE TITLE
Non-Administrator users cannot export library CVE data

### ISSUE THREAD

**Issue by YangJiao0817** [goharbor/harbor#17185]
**Expected behavior and actual behavior:**
Expected:All users can export library CVE data
Actual:Non-Administrator users cannot export library CVE data

**Steps to reproduce the problem:**
1. Create a user
2. Export library CVE data
<img width="686" alt="图片" src="https://user-images.githubusercontent.com/72076317/179453278-ff955efa-d016-408c-990e-e5a055630eed.png">

**Versions:**
Please specify the versions of following systems.

- harbor version: v2.6.0-f3edb03b

**Comment by prahaladdarkin** [comment]
@AllForNothing @wy65701436  @YangJiao0817 this appears to be by design. Currently, for the export data job to trigger successfully, the user needs to be a member of the project  with `Project Admin` or `Developer` role. I  provided a non-admin user `Developer` role on a project owned by system admin and I was able to run the export job successfully. 
@wy65701436  is there anything special about the `library` project due to which this behavior is exhibited?
Also, I do not think this is a blocker since the system admin can still export CVEs from the `library` project.


<img width="1515" alt="Screen Shot 2022-07-19 at 11 37 39 PM" src="https://user-images.githubusercontent.com/30070908/179820230-b6e3cf4e-242a-483d-8332-8414ca7d81bb.png">

**Comment by AllForNothing** [comment]
@prahaladdarkin @wy65701436 PM's advice: `If you can read the report, you should be able to export it. ` 
@qnetter
