### ISSUE TITLE
Export CVE data is inaccurate

### ISSUE THREAD

**Issue by YangJiao0817** [goharbor/harbor#17184]
**Expected behavior and actual behavior:**
Expected:The exported CVE data is consistent with the UI page
Actual:The exported CVE data is inconsistent with the UI page.Package column displayed incorrectly.Missing CVE data

**Steps to reproduce the problem:**
1. Create a project as test02
2. Push images to this project
    docker push domain/test02/goharbor/harbor-portal:v2.5.3
    docker push domain/test02/goharbor/notary-server-photon:v2.5.3
3. Scan
4. Export CVE And download
<img width="648" alt="图片" src="https://user-images.githubusercontent.com/72076317/179441327-1d58fb22-6121-48c1-884e-677848faccbd.png">

5. Compare CVE data
UI page Projects<test02<goharbor/notary-server-photon

<img width="1155" alt="图片" src="https://user-images.githubusercontent.com/72076317/179441601-4f6fcff1-b4e0-499c-bd2a-e1f4f7155a58.png">

<img width="1335" alt="图片" src="https://user-images.githubusercontent.com/72076317/179441691-4c97fdf0-53f2-4e46-85cb-03b0c33480f0.png">

Package column is not consistent with UI page, there are curl and curl-libs in UI page, only curl-libs in CSV file.
UI page has 8 records in curl + curl-libs and 7 records in CSV file.

**Versions:**

- harbor version: v2.6.0-f3edb03b

**Comment by AllForNothing** [comment]
@prahaladdarkin Please have a look at this

**Comment by YangJiao0817** [comment]
@prahaladdarkin 
goharbor/harbor-portal:v2.5.3:
<img width="1160" alt="图片" src="https://user-images.githubusercontent.com/72076317/179884718-a387a697-f540-48f6-b596-fc92dc755b46.png">

goharbor/notary-server-photon:v2.5.3:
<img width="1154" alt="图片" src="https://user-images.githubusercontent.com/72076317/179884609-326d4c9d-25b2-4a2e-a6e0-4e0d9c01fe50.png">

`goharbor/harbor-portal:v2.5.3` and `goharbor/notary-server-photon:v2.5.3` have some of the same CVEs, maybe this is the reason

**Comment by prahaladdarkin** [comment]
@YangJiao0817 referring to the attached CSV file image for image `harbor-portal` - the CVE data matches the UI.

<img width="1359" alt="Screen Shot 2022-07-25 at 12 36 16 AM" src="https://user-images.githubusercontent.com/30070908/180662154-4b093133-f1bc-4f4a-9144-54d23a668b63.png">

For the `notary-server-photon` image though there is one row less. This is due to presence of a particular CVE (in this case `CVE-2022-27191`) present in two version of the same Go package as shown in below screenshot (the package versions are highlighted).

<img width="1189" alt="Screen Shot 2022-07-25 at 12 42 01 AM" src="https://user-images.githubusercontent.com/30070908/180662422-e511496a-85c2-4465-b203-93428c646d90.png">

As a part of the fix for issue https://github.com/goharbor/harbor/issues/17188, package versions are now being included within the CSV report and this inclusion should help resolve the observation mentioned in the current issue

**Comment by prahaladdarkin** [comment]
Fixed within https://github.com/goharbor/harbor/pull/17232 (under review).
