### ISSUE TITLE
Filter issues under doublestar patterns

### ISSUE THREAD

**Issue by YangJiao0817** [goharbor/harbor#17191]
**Steps to reproduce the problem:**
Please provide the steps to reproduce this problem.
1. Create a project as test02
2. Push images(goharbor/notary-server-photon:v2.5.3, goharbor/harbor-portal:v2.5.3, nginx:latest) to test02
3. Export CVE data
<img width="600" alt="图片" src="https://user-images.githubusercontent.com/72076317/179478140-4db981ab-2f98-478f-a7a0-35cadefac7f2.png">
<img width="1427" alt="图片" src="https://user-images.githubusercontent.com/72076317/179478212-fbcb41c6-0896-450d-b2dd-fc8423fac1a8.png">

Filters Repositories: `goharbor/*,nginx`

**Versions:**
Please specify the versions of following systems.

- harbor version: v2.6.0-f3edb03b

**Comment by AllForNothing** [comment]
@prahaladdarkin Here is the request payload:
<img width="797" alt="image" src="https://user-images.githubusercontent.com/30999793/179479558-9bbd9353-60e8-4f79-badb-4fba766ec080.png">

**Comment by prahaladdarkin** [comment]
@AllForNothing @YangJiao0817  @wy65701436  As per the documentation of [doublestar patterns](https://github.com/bmatcuk/doublestar#patterns), the provided input is a valid input and within the job execution logic we simply perform a `selector.RepoMatches`. It is not immediately evident that the CSV export job is responsible for this failure. I would request @wy65701436 to help here since he has more expertise with the doublestar functionality.

**Comment by zyyw** [comment]
Say we have the following artifacts in Harbor library project:
* library/goharbor/harbor-portal
* library/goharbor/harbor-core
* library/nginx
* library/redis
Regarding the pattern matching of repositories within library project, we currently supporting:
```
1. {nginx,redis}
2. goharbor/{harbor-core,harbor-portal}
```
while currently not supporting pattern `{nginx,goharbor/*}`. Because Harbor underlying uses double-star for pattern matching, which first separate the pattern with the `/` delimiter, which leads to two parts `{nginx,goharbor` and `*}`. The first part is a malformed pattern, and double-star will throw an error with message "syntax error in pattern".
