### ISSUE TITLE
Unable to specify a scheme other than public for the external database

### ISSUE THREAD

**Issue by Razniak** [goharbor/harbor#17316]
**Is your feature request related to a problem? Please describe.**

We are  trying to force Harbor 2.5.0 to use a different schema on the external psql database than public, after searching the internet and documentation, I don't see an option to make it possible.

**Describe the solution you'd like**
Added the ability to indicate the schema used in the harbor.yml to psql

**Comment by wy65701436** [comment]
can you give an example about the `different scheme`?

**Comment by aek-arm** [comment]
Under https://goharbor.io/docs/2.3.0/install-config/configure-yml-file/#optional-parameters the section external_database contains only database name, user and password as mentioned in the original request. But this leads to the usage of the public schema inside the database, which has some caveats. It is recommended and best practice to create explicit schemas per application and refer them when connection. 
According to https://stackoverflow.com/questions/51459170/connect-with-postgresql-schema this reflects in go as search_path set to the schema name in the dataSourceName.

**Comment by aek-arm** [comment]
Hi @wy65701436 - have you seen https://github.com/goharbor/harbor/issues/17316#issuecomment-1297771994?

**Comment by aek-arm** [comment]
The public schema in PostgreSQL is created by default and is available to all users by default. It is not recommended to use the public schema for several reasons:

**Security**: All users have access to the public schema by default. This means that if you store sensitive data in the public schema, any user who can access the database can potentially view or modify it. This can lead to data breaches and compromise the security of your system.
**Clutter**: The public schema is intended to be a general-purpose schema and is often used as a dumping ground for miscellaneous tables, functions, and other objects. This can lead to clutter and make it difficult to find the objects you need.
**Naming conflicts**: Since the public schema is available to all users, there is a greater chance of naming conflicts. If multiple users create objects with the same name in the public schema, it can lead to confusion and errors.

To avoid these issues, it is recommended to create your own schemas and restrict access to them as needed. This can help to ensure that sensitive data is protected, objects are organized and easy to find, and naming conflicts are minimized.

**Comment by aek-arm** [comment]
@wy65701436 and @qnetter - I saw that you both are mentioned in https://github.com/goharbor/harbor/issues/17226 - maybe you can have a look at this topic? Having only public schema as option is also a security concern that makes any dba and security advisor really unlucky
