### ISSUE TITLE
Replication task cannot be stopped

### ISSUE THREAD

**Issue by lengrongfu** [goharbor/harbor#17356]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
I created and run a copy task, the task is running for a long time, during the run I click the stop task button on the page, nothing happens, the task stop fails.

Hope can control the task and stop.

![image](https://user-images.githubusercontent.com/15009201/183460935-9410e828-61fa-4e61-8330-fd9a24486186.png)

**Steps to reproduce the problem:**
1. Create a task that replicates the origin of `https://artifacthub.io/`
2. stop task, and stop faild.

**Versions:**
Please specify the versions of following systems.

- harbor version: [2.5.0]
- docker engine version: [y.y.y]
- docker-compose version: [z.z.z]

**Additional context:**

- **Harbor config files:** You can get them by packaging `harbor.yml` and files in the same directory, including subdirectory.
- **Log files:** You can get them by package the `/var/log/harbor/` .

**Comment by lengrongfu** [comment]
It took an hour or so for the task to stop succeeding.

**Comment by lengrongfu** [comment]
Through my analysis of the code, I found that after calling `post /replication/executions` to execute the create executions logic and then calling `Put /replication/executions` to execute the stop executions logic, if the execution is time-consuming, it will not succeed when the task stops.

**Comment by chlins** [comment]
For all the asynchronous jobs in harbor such as GC/Replication/Scan..., the stop logic is executed by checkpoints, harbor presets multiple check points in the process of jobs, so if the time-consuming process between the last checkpoint and next checkpoint, It does take some time to stop, but this works as the expected. But as you mentioned  `It took an hour or so for the task to stop succeeding.`, it is really not a good user experience, thanks for your pr, I also reviewed the change, but I think we should keep the consistency of different jobs instead of doing any special logic for someone, I suggest you can open a discussion in the harbor repository so that we can collect more user opinions, If we finally need to do this, we can make a completed proposal for the design and implement this as a full feature in the future release. Thanks!

**Comment by lengrongfu** [comment]
OK, we can ask for a discussion to see if there are similar issues.
