### ISSUE TITLE
Scan all fails to scan most images when a cosign signed image is present

### ISSUE THREAD

**Issue by teeram** [goharbor/harbor#17455]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**

Clicking the SCAN NOW button under the Vulnerability tab within Interrogation Services should result in all the container images within Harbor being scanned across each project and repository. This behavior works as expected until a cosign signed image is pushed into a project repository. When the cosign signed image is present, only a small subset of container images are scanned when the SCAN NOW button is clicked. The cosign signed image must be removed from the repository for all images to once again be scanned when clicking the SCAN NOW button.

**Steps to reproduce the problem:**

1. Click the SCAN NOW button before a cosign signed image is pushed into a repository and denote the number of scanned images.
2. Push a cosign signed image to any Harbor project repository.
3. Click the SCAN NOW button again and notice that the scan doesn't find nearly as many images to scan.

**Versions:**
Please specify the versions of following systems.

- harbor version: 2.5.1

**Additional context:**

- Harbor has been deployed via Helm in Kubernetes.

**Comment by zyyw** [comment]
The root cause of this issue might because of this reason: 
```
jobservice called AccessoryManager.List() while accessories are not imported in jobservice
```
similar to this one: 
* https://github.com/goharbor/harbor/issues/17200

ScanAll invokes ar.Iterator()
* https://github.com/goharbor/harbor/blob/v2.5.1/src/controller/scan/base_controller.go#L388

which calls artifact List():
* https://github.com/goharbor/harbor/blob/v2.5.1/src/controller/artifact/helper.go#L36

which calls accessoryMgr.List(): 
* https://github.com/goharbor/harbor/blob/v2.5.1/src/controller/artifact/controller.go#L262

And it should be resolved by this PR, which will be available in harbor v2.6.0:
* https://github.com/goharbor/harbor/pull/17231
