### ISSUE TITLE
Advice about mount a volume

### ISSUE THREAD

**Issue by frit0-rb** [goharbor/harbor#17856]
**Is your feature request related to a problem? Please describe.**
Hello guys, It's my first time installing harbor and I have been many problem with the prequisites

**Describe the solution you'd like**
I was looking to resolve the problem and finally there are two problems.

First, the documentation from Docker to install docker compose is not completed and they don't explain so much well the process, the main problem is when you install docker engine you also install docker compose but when you run the install harbor all time tells there arent docker compose in the system but when you run "docker compose version" appear the version correct. The way to resolve that problem is uninstall docker compose from the docker engine install and install standalone.

Second and more importan, in your documentation neves says is important and necessary to create a volume in /data, and in the config install file you need it to run it.
I have been looking other guides to run properly. 

Finally is working

One more things, the paths from docker in the documentation are not correct, you need to look where is exactly the urls

**Comment by MinerYang** [comment]
Hi @frit0-rb ,

For the first question, which harbor you are using and which doc you are referring? We are now support docker compose v2 as well since v2.6.0
https://goharbor.io/docs/2.6.0/install-config/installation-prereqs/


For the second Q, generally the volume /data would create automatically if not exist. 
Could you provide more info about the env,  such as 
```
- harbor version: [x.x.x]
- docker engine version: [y.y.y]
- docker-compose version: [z.z.z]
- steps to install
```
