### ISSUE TITLE
How to change existing expired harbor CA certificate with new one

### ISSUE THREAD

**Issue by thakar201** [goharbor/harbor#18104]
Hi ,

How to change existing expired harbor CA certificate with new one, If can help with process step.

**Comment by ZrytyADHD** [comment]
It's simple.
First If good understand you need to exchange your own generated Ca you need to generate it again as you do this first time and sign self-signed harbor cert.

If you're uisng SSL certs signed by your company CA you need:
1. Generate key oraz use existing and generate CSR to sign.
2. Stop harbor
3. Reinstall it using new certs or go to <harbor_data_serwer>//secret/cert and the replace server crt and key.
4. Run harbor again.

**Comment by zyyw** [comment]
Maybe you can follow the below steps to replace your expired CA certificate with the new one:
1. Get the new server.key, server.crt, and ca.crt through openssl or through third-party Certificate Authority
2. Stop Harbor: `sudo docker-compose -f docker-compose.yml down`
3. 
3.1. Reinstall harbor using new server.crt, server.key; 
3.2 OR run `./prepare --xxx` with the new server.crt, and server.key; 
3.3 OR, alternatively, replace the the server.crt and server.key under `<harbor_data_dir>/secret/cert`
4. replace with `<harbor_data_dir>/ca_download/ca.crt` with the new ca.crt
5. Restart Habor: `sudo docker-compose up -d` if you are using step 3.2 or step 3.3

How to generate server.crt, server.key and ca.crt using OpenSSL? 
If your harbor instance is installed via docker-compose, please try the following method to generate the certificates for harbor - ca.crt, server.crt, server.key:
```
  ### Create CA certificate
  openssl req \
      -newkey rsa:4096 -nodes -sha256 -keyout harbor_ca.key \
      -x509 -days 3650 -out harbor_ca.crt -subj '/C=CN/ST=PEK/L=BeiJing/O=VMware/CN=HarborCA'
  
  ### Generate a Certificate Signing Request
  openssl req \
      -newkey rsa:4096 -nodes -sha256 -keyout $harbor_hostname_value.key \
      -out $harbor_hostname_value.csr -subj "/C=CN/ST=PEK/L=BeiJing/O=VMware/CN=$harbor_hostname_value"
  
  ### Generate the certificate of local registry host
  if [ -n "$HARBOR_HOSTNAME" ]; then
    echo subjectAltName = DNS.1:$HARBOR_HOSTNAME > extfile.cnf
  else
    echo subjectAltName = IP:$ip_address > extfile.cnf
  fi
  openssl x509 -req -sha256 -days 3650 \
      -extfile extfile.cnf \
      -CA harbor_ca.crt -CAkey harbor_ca.key -CAcreateserial \
      -in $harbor_hostname_value.csr \
      -out $harbor_hostname_value.crt
```
where `HARBOR_HOSTNAME` is the FQDN value if you are using a domain name (if using IP instead of domain name, then `HARBOR_HOSTNAME=""`), `ip_address` is the IP value if you are using IP address instead of domain name to access harbor, and `harbor_hostname_value `is equal to HARBOR_HOSTNAME if domain name is used, otherwise it equals to ip_address.
And then `$harbor_ca.crt`is the `ca.crt`; `$harbor_hostname_value.crt` is the `server.crt`; `$harbor_hostname_value.key` is the `server.key`.
