### ISSUE TITLE
New releases are not pushed to GitHub Packages

### ISSUE THREAD

**Issue by jb-abbadie** [goharbor/harbor#18138]
Releases after `v2.6.2` are missing from GitHub Packages

**Expected behavior and actual behavior:**

expected : Releases with version after `v2.6.2` are available in Github Packages [here](https://github.com/orgs/goharbor/packages )
actual : No releases after `v2.6.2` available

**Versions:**
- All harbor docker images after `v2.6.2`

**Comment by Nageshbansal** [comment]
@jb-abbadie can I work on this issue?

**Comment by Nageshbansal** [comment]
@YangJiao0817  can i work on this issue?

**Comment by YangJiao0817** [comment]
@Nageshbansal Sure, you are welcome to submit a PR.

**Comment by Nageshbansal** [comment]
@YangJiao0817 , do we just need to create a github workflow for publishing packages?

**Comment by YangJiao0817** [comment]
@Nageshbansal  No need to create a new GitHub workflow, you just need to modify [publishImages](https://github.com/goharbor/harbor/blob/901cc17c67971edabd2b1be829ad1554ef781423/tools/release/release_utils.sh#L56), publishImages is called here. https://github.com/goharbor/harbor/blob/901cc17c67971edabd2b1be829ad1554ef781423/.github/workflows/publish_release.yml#L61

**Comment by Nageshbansal** [comment]
hey @YangJiao0817, can't we use [build-and-push-docker-images](https://github.com/marketplace/actions/build-and-push-docker-images) action to publish/push images on docker and github registry rather than using `docker push image commands`? 
let me know if we need to create a function like [publishImages](https://github.com/goharbor/harbor/blob/901cc17c67971edabd2b1be829ad1554ef781423/tools/release/release_utils.sh#L56)
