### ISSUE TITLE
Should update the DOC for the removal for chart museum

### ISSUE THREAD

**Issue by AllForNothing** [goharbor/harbor#18266]
As chart museum has been removed by #17958, we should update the DOC correspondingly

**Comment by udf2457** [comment]
If chart museum has been removed then you probably need to remove it from `vars.yaml` too, no ?

**Comment by zyyw** [comment]
HI @udf2457 which version of harbor-helm you are using?
The chartmuseum should also be remove from harbor-helm (master branch, merged but not released yet). PR:

**Comment by wy65701436** [comment]
@YangJiao0817 please add the comments on upgrade scenario.

**Comment by YangJiao0817** [comment]
When the registry type is artifact-hub or helm-hub, update the registry description to `Chartmuseum has been deprecated in Harbor v2.8.0, please delete this registry`.

When the Source resource filter of the replication rule is `chart(chartmuseum)` or the registry type associated with it is `artifact-hub` or `helm-hub`, set the status to Deactivated, set the description to `Chartmuseum is deprecated in Harbor v2.8.0, because the Source resource filter of this rule is chart(chartmuseum), so please update this rule.`, and set the Source resource filter from `chart(chartmuseum)` set to all .

Remove these permissions when the robot account permissions include `helm-chart helm-chart-version helm-chart-version-label`

Remove these event types when the event types of the Webhook include `UPLOAD_CHART DOWNLOAD_CHART DELETE_CHART`. If the Webhook event types is empty now, set the status to Deactivated and the description to `Chartmuseum is deprecated in Harbor v2.8.0, because this notification policy only has event type about Chartmuseum, so please update or delete this notification policy`.
