### ISSUE TITLE
error manifest blob unknown: blob unknown to registry

### ISSUE THREAD

**Issue by Dundonis** [goharbor/harbor#18432]
**Steps to reproduce the problem:**
Hi, I faced with the problem of docker manifest, when I tried to push image to registry, I got this `error manifest blob unknown: blob unknown to registry`
. Also when I try to check manifest I got this `unsupported manifest media type and no default available: text/html`
My Dockefile example
```
FROM octopusdeploy/tentacle:latest
# utils
RUN apt-get update \
    && apt-get install -y \
        curl \
        wget \
        ca-certificates \
        jq

# Install kubectl
RUN curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.25.3/bin/linux/amd64/kubectl && \
    chmod +x ./kubectl && \
    mv ./kubectl /usr/local/bin/kubectl

RUN curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 && \
    chmod 700 get_helm.sh && \
    ./get_helm.sh
RUN helm plugin install https://github.com/chartmuseum/helm-push`
```

**Versions:**
Please specify the versions of following systems.

- harbor version: 2.7.1
- docker engine version: 20.10.23
- docker-compose version: v2.15.1

**Additional context:**
Harbor are running in k8s cluster with the next changed parameters:
```
helm upgrade harbor harbor/harbor --version=1.11.0 `
    --install `
    --wait `
    --namespace harbor `
    --create-namespace `
    --set registry.relativeurls='true' `
    --set registry.replicas=2 `
    --set chartmuseum.replicas=2 `
    --set expose.ingress.hosts.core='***' `
    --set expose.ingress.hosts.notary='***' `
    --set expose.ingress.annotations."cert-manager\.io/cluster-issuer"='letsencrypt-prod' `
    --set expose.ingress.className="cmn" `
    --set expose.tls.certSource='secret' `
    --set expose.tls.secret.secretName='cmn-harbor-tls' `
    --set expose.tls.secret.notarySecretName='cmn-notary-tls' `
    --set externalURL='***same as host.core ***' `
    --set persistence.imageChartStorage.type='azure' `
    --set persistence.imageChartStorage.azure.accountname='***' `
    --set persistence.imageChartStorage.azure.accountkey='***' `
    --set persistence.imageChartStorage.azure.container='harbor-registry' `
    --set persistence.imageChartStorage.azure.realm='core.windows.net' `
    --set persistence.imageChartStorage.disableredirect='true' `
    --set harborAdminPassword='***' `
    --set secretKey="***" `
    --set database.type='external' `
    --set database.external.host='***' `
    --set database.external.username='***' `
    --set database.external.password='***' `
    --set database.external.sslmode='require' `
    --set database.external.coreDatabase='definely-harbor-registry' `
    --set database.external.notaryServerDatabase='***' `
    --set database.external.notarySignerDatabase='***' `
    --set database.maxOpenConns=0 `
    --set metrics.enabled='true'
```
![2023-03-27 12-45-50 Lens](https://user-images.githubusercontent.com/63404719/227920225-54970639-7557-4c9d-aeda-c2021e569d0e.png)

**Comment by LiuShuaiyi** [comment]
Can you try again by setting the replica of registry to 1: `--set registry.replicas=2`?
This error could be that the registry storage does not provide read-after-write consistency.

**Comment by Dundonis** [comment]
@LiuShuaiyi the same error

**Comment by LiuShuaiyi** [comment]
According to https://github.com/opencontainers/distribution-spec/blob/main/spec.md#push the error `error manifest blob unknown: blob unknown to registry` should be thrown to the registry when the client tries to push a manifest when the referenced blobs do not exist.

Assuming you are using `docker push` to push the image, this shouldn't happen because the implementation of `docker` will make sure it only pushes the manifest when all the blobs are pushed first.

It's hard to tell why given the limited information you provided. If I were faced with this issue, I would collect logs in core and registry (set log level to debug would help), and also check the azure storage to see if blob requested is present or not.

**Comment by Dundonis** [comment]
@LiuShuaiyi I'll check again, it's weird since I was able to push this image to docker hub

**Comment by Dundonis** [comment]
@LiuShuaiyi I have checked logs in debug mode again, nothing new, but root cause can be connected with Azure Storage limits for old type of API, Image has one blob 200+ mb, but limits for blobs in Azure Storage Account is https://learn.microsoft.com/en-us/azure/storage/blobs/scalability-targets , could you check what version does the harbor use for connection  https://learn.microsoft.com/en-us/rest/api/storageservices/versioning-for-the-azure-storage-services ?

**Comment by LiuShuaiyi** [comment]
That's possible.

The registry in [distribution/distribution](https://github.com/distribution/distribution) is the sub-component that uses Azure's blob service: https://github.com/distribution/distribution/blob/a4d9db5a884b70be0c96dd6a7a9dbef4f2798c51/docs/storage-drivers/azure.md

Seems like it's using a somewhat old api version and there's no way to configure it:
1. https://github.com/distribution/distribution/blob/4906c6ee88d8aba34e2b9f6e8e0c8b9fb194ca04/registry/storage/driver/azure/azure.go#L80
2. https://github.com/azure/azure-sdk-for-go/blob/v56.3.0/storage/client.go#L38

I would suggest open an issue in https://github.com/distribution/distribution because if this is the root cause, it cannot be solved here in harbor's source code.

**Comment by Dundonis** [comment]
@LiuShuaiyi Thank you!

**Comment by zyyw** [comment]
could you please share which client you use to push the artifact? 
It seems that the `text/html` is not an OCI-compliant artifact.

**Comment by sahilshahane** [comment]
I'm getting the same issue

**Comment by adamency** [comment]
For people turning up here, FYI, I was having the same issue with a simple and basic [distribution/distribution](https://github.com/distribution/distribution) deployment, but the same can perfectly happen with harbor.

On my end, the issue was in the fact that [`ingress-nginx` has a `proxy-body-size` default value of `1m`](https://github.com/kubernetes/ingress-nginx/issues/4262), which effectively disables the possibility to push blobs larger than 1MB. You have to increase this limit with

```
nginx.ingress.kubernetes.io/proxy-body-size: "<amount_you_want>M"
```

in your corresponding `Ingress` resource.

Hope this helps someone :)
