### ISSUE TITLE
extra_hosts config in harbor.yml

### ISSUE THREAD

**Issue by ffppmm** [goharbor/harbor#18607]
Hello,

I added some extra_hosts configs to every network in docker-compose.yml

If I do a ./prepare they disapear. Is there a way to add "something"/some config in the harbor.yml, so that the extra_hosts are automatically added to the docker-compose.yml? 

Thanks in advance, regards Philipp

**Comment by MinerYang** [comment]
How about try `docker compose up -d` instead of running `./prepare` script after configs been updated

**Comment by ffppmm** [comment]
Hi,
thanks for your answer. I just wanted to know if there is a way to configure the extra_hosts in the harbor.yml and doing a ./prepare will ad the automatically?

Thanks in advance Philipp

**Comment by chlins** [comment]
@ffppmm Hi, currently the generated `docker-compose.yaml` was rendered from https://github.com/goharbor/harbor/blob/main/make/photon/prepare/templates/docker_compose/docker-compose.yml.jinja, so it seems not possible to add the extra_hosts to `harbor.yml` then render it automatically because this needs code change to update the template file.

**Comment by wy65701436** [comment]
No, Harbor doesn't support it. You'll need to edit the YAML directly before launching Harbor and after running the prepare script.
