### ISSUE TITLE
I have to retry so many times when I pull a image from harbor proxy-project (DockerHub)

### ISSUE THREAD

**Issue by LittleNewton** [goharbor/harbor#19067]
If you are reporting a problem, please make sure the following information is provided:

**Expected behavior and actual behavior:**

**I wish**: when I download/pull from a local Harbor registry, it will 1) report dockerhub (sth. else) has no related image or 2) give me the requested image. However, now I have to retry so many times can I succeed.

``` bash
(base)  newton@epyc-debian  ~  docker pull app-registry.proxy.littlenewton.cn/dockerhub/sharelatex/sharelatex:latest
Error response from daemon: unknown: artifact dockerhub/sharelatex/sharelatex@sha256:77dce64de0d78f9d5830cdeaf251b28d32a36777630404ef935ae21979377f56 not found
(base)  ✘ newton@epyc-debian  ~  docker pull app-registry.proxy.littlenewton.cn/dockerhub/sharelatex/sharelatex:latest
Error response from daemon: unknown: artifact dockerhub/sharelatex/sharelatex@sha256:77dce64de0d78f9d5830cdeaf251b28d32a36777630404ef935ae21979377f56 not found
(base)  ✘ newton@epyc-debian  ~  docker pull app-registry.proxy.littlenewton.cn/dockerhub/sharelatex/sharelatex:latest
Error response from daemon: unknown: artifact dockerhub/sharelatex/sharelatex@sha256:77dce64de0d78f9d5830cdeaf251b28d32a36777630404ef935ae21979377f56 not found
(base)  ✘ newton@epyc-debian  ~  docker pull app-registry.proxy.littlenewton.cn/dockerhub/sharelatex/sharelatex:latest
latest: Pulling from dockerhub/sharelatex/sharelatex
7c3b88808835: Pull complete
6ea0e81b1046: Pull complete
2cdac9582559: Pull complete
d85cf572b4d7: Pull complete
fe9158273c22: Pull complete
d38417397511: Pull complete
6deeaa2c056d: Pull complete
41a4eeecff9e: Pull complete
0bc715d70cae: Pull complete
6778c3853747: Pull complete
e26889067ea1: Pull complete
4c56917c4ffb: Pull complete
c55d69dbb251: Pull complete
32433fbc38c3: Pull complete
```

**Steps to reproduce the problem:**

Just have a try with my Harbor 2.8.

**Versions:**
Please specify the versions of the following systems.

- harbor version: [2.8.0]
- docker engine version: [24.0.5]
- docker-compose version: [2.20.2]

**Additional context:**

I am using NginxProxyManager (a third-party reverse proxy tool). Which can provide HTTPS access for harbor.

**Comment by LittleNewton** [comment]
![image](https://github.com/goharbor/harbor/assets/17793356/a529f38f-3218-4a5b-a51b-551fb34e9831)

I don't know why.

- I have login
- I have the privilege
- My network works

**Comment by chlins** [comment]
Did you configure the credentials for the `DockerHub` registry? Please also checks the harbor core logs and confirm that your account or environment not reached the rate limit of `DockerHub`.

**Comment by stonezdj** [comment]
Please upload the harbor core logs when it retry

**Comment by conclusionlogic** [comment]
I for one have seen this issue occur when for whatever reason DockerHub responds with a 503 error.
Excerpt from Harbor Core logs:
```
2023-10-02T21:12:34Z [ERROR] [/controller/registry/controller.go:234]: failed to check health of registry 2: login to dockerhub error: login to dockerhub error: <html><body><h1>503 Service Unavailable</h1>
No server is available to handle this request.
</body></html>
```
Obviously, DockerHub can sometimes have problems which is when Harbor cannot check from DockerHub whether the pulled image has any updates in the target registry.

The documentation describes Harbor's behaviour as follows:
> - If the target registry is not reachable, the proxy cache project serves the cached image.
> - If the image is no longer in the target registry, no image is served.

How does Harbor interpret this situation when DockerHub responds with a 503?
Is in that case the target registry not reachable or is the image no longer in the target registry?

Since, the following response is returned to the client while in reality both DockerHub and Harbor have that image...
```
Error response from daemon: unknown: artifact dockerhub/library/postgres@sha256:78a275d4c891f7b3a33d3f1a78eda9f1d744954d9e20122bfdc97cdda25cddaf not found
```
...Harbor must be thinking that "the image is no longer in the target registry" and refuses to service the client.
I would much prefer if Harbor returned the requested image from its cache rather than respond with "artifact not found" because while a 503 error code is returned from the backed server, the target registry could not be reached ...

Thoughts?
