### ISSUE TITLE
Can't add credentials for Docker Hub registry (invalid key size 20) - v2.8.2

### ISSUE THREAD

**Issue by ex12is** [goharbor/harbor#19159]
Hi,

I'm trying to add credentials for Docker Hub registry to increase rate limit. If i press "TEST CONNECTION" button everything looks fine - "Connection tested successfully". At the same time if i press "OK" UI will show the error - "internal server error". In the harbor-registry-core logs i can see the only one error:

`[ERROR] [/lib/http/error.go:57]: {"errors":[{"code":"UNKNOWN","message":"unknown: crypto/aes: invalid key size 20"}]}`

I have tried to add the same via the REST API and got the same response - "internal server error".

To reproduce this problem either you need to create new Docker Hub registry with credentials or try to add credentials to the existing Docker Hub registry and press OK.

- harbor version: [2.8.2]

**Comment by chlins** [comment]
Is the credential you provided can login and pull/push images successfully from docker CLI?

**Comment by chlins** [comment]
Which key type did you use for DockerHub client?

**Comment by chlins** [comment]
Please consider referring https://github.com/goharbor/harbor/issues/12158 for further exploration.

**Comment by chlins** [comment]
Could you exec into your harbor core pod and check the key path `/etc/core/key` to double check the length of the key?

**Comment by rivolity** [comment]
I recently ran into the same issue while trying to configure Harbor, where I was getting an error related to an invalid key size for AES encryption:

```
2024-10-22T12:35:20Z [ERROR] [/lib/http/error.go:57]: {"errors":[{"code":"UNKNOWN","message":"unknown: crypto/aes: invalid key size 18"}]}
```

This error occurred because the encryption key located in `/etc/core/key` had an invalid size. Harbor requires AES encryption keys to be exactly 16, 24, or 32 bytes (128, 192, or 256 bits). My original key was 18 bytes, which caused the error.

## Solution:
Here’s how I fixed it:

1. **Check the Key Size**:
   I found that the key in `/etc/core/key` was 18 bytes long, which is not a valid size for AES encryption.

2. **Generate a Correct Key**:
   You need to generate a raw (binary) 16, 24, or 32-byte key. Initially, I used a base64-encoded key, which caused another error due to the incorrect size (45 bytes instead of 32). To fix this, I generated a raw 32-byte key:

   ```bash
   openssl rand 32 > /etc/core/key
   ```

3. **Verify the Key Size**:
   After generating the key, you can verify the size using:

   ```bash
   wc -c /etc/core/key  # This should return 32
   ```

4. **Restart Harbor**:
   Finally, I restarted Harbor Core Pod.


This resolved the error for me, and Harbor was able to use the key correctly without any issues.
