### ISSUE TITLE
Compatibility with different docker registry versions

### ISSUE THREAD

**Issue by tianouya-db** [goharbor/harbor#19200]
Hi, I'd like to find out Harbor's compatibility support on different docker registry versions. I see in [install-config](https://goharbor.io/docs/2.4.0/install-config/) it lists the versions of the components, e.g. `Docker/distribution | 2.7.1`. If we want to use a different version of docker registry (e.g. [2.8.2](https://hub.docker.com/layers/goharbor/registry-photon/v2.8.2/images/sha256-0883d973994970336e6fb187e342b874aa86964665c8f77c905f90c97b85b11a?context=explore)) with Harbor 2.4.0, is it going to work out of the box?

**Comment by tianouya-db** [comment]
Another question is - is the [goharbor/registry-photon:v2.8.2](https://hub.docker.com/layers/goharbor/registry-photon/v2.8.2/images/sha256-0883d973994970336e6fb187e342b874aa86964665c8f77c905f90c97b85b11a?context=explore) built from [docker registry 2.8.2](https://github.com/distribution/distribution/tree/v2.8.2)?

**Comment by tianouya-db** [comment]
Found out that [goharbor/registry-photon:v2.8.2](https://hub.docker.com/layers/goharbor/registry-photon/v2.8.2/images/sha256-0883d973994970336e6fb187e342b874aa86964665c8f77c905f90c97b85b11a?context=explore) is built from docker registry 2.7.1. And there's a recent change https://github.com/goharbor/harbor/commit/982ff0aeea9b6e07612ac02d69e165ee9223c8a8 to upgrade to docker registry 2.8.2 and is included in harbor 2.9.0-rc1. 

Now our question is, can we use [goharbor/registry-photon/v2.9.0-rc1](https://hub.docker.com/layers/goharbor/registry-photon/v2.9.0-rc1/images/sha256-481c233ebef9a5b977175d58728c12ac1c6228215fe823a84c1ab2d08737c8c5?context=explore) with harbor-core [goharbor/harbor-core/v2.4.0](https://hub.docker.com/layers/goharbor/harbor-core/v2.4.0/images/sha256-b5e1bf10c22df2b59a7a79623e6f857a797b4c7ca32326611b3c707f0a4e6e22?context=explore) (and other components) on 2.4.0?

**Comment by wy65701436** [comment]
Currently, Harbor follows a specific pattern for picking up the latest patch release of distribution v2.8 within the current release timeframe.

- In Harbor v2.8.*, we use distribution v2.8.0.
- In Harbor v2.9.*, we use distribution v2.8.2.

Moreover, Harbor goes beyond simply selecting the latest patch release. We also backport necessary PRs from the upstream repository and build the registry using our custom script.

And when updating Harbor, it is recommended to update the entire Harbor as a whole, rather than updating the registry component alone. Updating only the registry component in isolation may result in unforeseen issues and complications.
