### ISSUE TITLE
registry health check bug

### ISSUE THREAD

**Issue by lengrongfu** [goharbor/harbor#19240]
https://github.com/goharbor/harbor/blob/dd90313c727448db28728233276062d254594102/src/controller/registry/controller.go#L232-L234

When a connection refused error occurs when connecting to the registry, the registry should be considered unhealthy, but the current processing is to filter the error.

```
2023-08-25T01:47:06Z [ERROR] [/controller/registry/controller.go:234]: failed to check health of registry 20: Get "https://test/api/version": dial tcp 10.6.232.5:30010: connect: connection refused
```

**Comment by lengrongfu** [comment]
@AllForNothing What do you think about this issue？

**Comment by AllForNothing** [comment]
@lengrongfu 
@chlins will have a look at this

**Comment by chlins** [comment]
From the previous design, when errors occurred here, we considered it to be an internal error, possibly caused by internal call exceptions or database exceptions, etc., which prevented the health check from being completed smoothly. Therefore, the previous implementation did not consider this as repository unhealthiness but rather as an inability to complete a normal check, but we can open this issue for further discussion.

**Comment by lengrongfu** [comment]
Should health check errors be updated to unhealthy because we are not sure what caused them?

**Comment by achambok** [comment]
I'm facing the same issue on Harbor 2.0. Error is Unauthorized credentials.

From investigations, we managed to narrow it down to the API not parsing the access key (which is the Harbor username Admin) but only parses the access secret, therefore failing to authenticate.

I hope this helps.

Which file has the code for this function?
