### ISSUE TITLE
OIDC Login failing with unknown internal server error

### ISSUE THREAD

**Issue by msturge** [goharbor/harbor#19255]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
A clear and concise description of what you expected to happen and what's the actual behavior. If applicable, add screenshots to help explain your problem.

Up until last Friday users could login to our Harbor.io instance without issue. Now when authenticating with OIDC they are redirected from AAD SAML auth back to Harbor with a unknown internal server error as follows:

```
{
    "errors": [
        {
            "code": "UNKNOWN",
            "message": "internal server error"
        }
    ]
}
```

Within the logs for harbor-core I can see an SQL error:

```
2023-08-30T11:43:32Z [ERROR] [/lib/http/error.go:56]: {"errors":[{"code":"UNKNOWN","message":"unknown: ERROR: cannot execute UPDATE in a read-only transaction (SQLSTATE 25006)"}]}
```

I have tried restarting the pods running harbor, but the issue persists. Any assistance would be appreciated.

**Versions:**
Please specify the versions of following systems.

- Image:          goharbor/harbor-core:v2.7.2
- Running in Microsoft AKS

Thanks.

**Comment by wy65701436** [comment]
are you using the internal or external DB?

**Comment by msturge** [comment]
This system was configured by someone else, so we didn't have full docs on the setup. We ended up rolling out ACR to get around the auth issues.

**Comment by ztvc** [comment]
Hello, I'm experiencing the same issue as the original poster. 
Running version: Harbor version v2.7.1-6015b3ef

Expected behavior and actual behavior:
A clear and concise description of what you expected to happen and what's the actual behavior. If applicable, add screenshots to help explain your problem.

Now when authenticating with OIDC they are redirected from AAD SAML auth back to Harbor with a unknown internal server error as follows:

{
    "errors": [
        {
            "code": "UNKNOWN",
            "message": "internal server error"
        }
    ]
}

**Comment by ztvc** [comment]
Any update?

**Comment by ztvc** [comment]
Any update? or responses?
