### ISSUE TITLE
Does harbor supports Prismacloud scanner adapter?

### ISSUE THREAD

**Issue by rekha-prakash-maersk** [goharbor/harbor#19338]
According to this Prismacloud doc, Harbor supports prismacloud integration - https://www.paloaltonetworks.com/blog/prisma-cloud/harbor-plugin-from-prisma-cloud/

But I don't find any relevant information on Harbor documentation - https://goharbor.io/docs/2.9.0/install-config/harbor-compatibility-list/#scanner-adapters

**Comment by zyyw** [comment]
Harbor v2.x.x only officially supports Trivy as the default scanner, while any 3rd-party scanner that implements this [spec](https://github.com/goharbor/pluggable-scanner-spec) can be theoretical added to Harbor as an external Scanner.

**Comment by rekha-prakash-maersk** [comment]
@zyyw I have tried enabling the Prisma cloud scanner in Harbor and making it default for one of the test project. But noticing that all scan related functions within Harbor taking longer time though its just a tiny alpine image.

For Trivy , `v2_blob_upload` operation takes under 1sec for the weekly scans, but with Prisma it takes more than 6 mins and harbor postgres DB connection limits gets exhausted pushing the db resource to restart loop.  

Is there any documentation to understand the operations happens within harbor while adding the pluggable 3rd party scanner to troubleshoot this issue?

**Comment by wy65701436** [comment]
If Prisma implements their adapter based on the specifications provided in the pluggable-scanner-spec repository (https://github.com/goharbor/pluggable-scanner-spec), Harbor can support it. Once all the functionalities have been verified and are working correctly, the owner of the scanner can submit a pull request to add the scanner to the Scanner Adapters List. Additionally, it would be helpful to provide a demo or environment for us to review during the process.


@rekha-prakash-maersk  For troubleshooting the issue, since I am not familiar with the specific implementation details of the Prisma Cloud scanner, it would be beneficial to provide the scanner log and core log for further analysis and debugging.
