### ISSUE TITLE
Update to DB and harbor lost images in DB

### ISSUE THREAD

**Issue by brtduvally** [goharbor/harbor#19382]
Not filing as a bug because I doubt it can be reproduced, and I have no idea why it happened.

Harbor v2.8.0 on K8S via Helm, external PostgreSQL v12, PV filesystem NFSv3. Service has been providing images since v1.7.2. 

We updated the DB server to v15 without issue. 3 weeks later we updated Harbor to v2.8.4 seemingly without issue (images pushed and pulled as validation).

5 days later we discovered images missing that were pushed during those 3 weeks. Registry files were still in place, but the DB entries for them were missing, as well as logs for that period. This was tracked down through external logging of the K8S cluster. 

I am completely baffled as to what in the Harbor update could delete only 3 weeks of DB entries.

**Comment by zyyw** [comment]
Instead of independently upgrading PG DB to an arbitrary version, such as v15, could you please try to align the pg db version with the one that was shipped as internal PostgreSQL? In your case, the Harbor version is from v2.8.0 to v2.8.4, therefore please try to use external PG db v13, which is the version of internal DB for v2.8.x.

cc: @YangJiao0817

**Comment by wy65701436** [comment]
I figure you need to check this problem locally, especially in your DB side. There is no such action within harbor to remove things only 3 weeks.
