### ISSUE TITLE
The artifact sha256 shown in proxy cache project does not match digest sha256 shown in 'docker inspect'

### ISSUE THREAD

**Issue by jessehu** [goharbor/harbor#19806]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
The artifact sha256 in proxy cache project does not match digest sha256 shown in `docker pull`

**Steps to reproduce the problem:**
Create a proxy cache project for Docker Hub.
docker pull registry.mydomain.com/docker.io/busybox:1.35
```
1.35: Pulling from busybox
e55fd4b1deb1: Pull complete
Digest: sha256:c4c67b37cc42396b8a6f6829e3379e86364f642ce6a40604ea4f7c695db0e695
Status: Downloaded newer image for registry.mydomain.com/docker.io/busybox:1.35
registry.mydomain.com/docker.io/busybox:1.35
```
The artifact sha256 ab4b shown in proxy cache project is the same as [the sha256 shown in docker hub](https://hub.docker.com/layers/library/busybox/1.35/images/sha256-ab4b55974af84ec0338b3b721db01931d3231115742e2dda607b7fdd6a23f925?context=explore&tab=vulnerabilities), but it's different with the digest sha256 c4c6 shown in docker pull and docker inspect
![图片](https://github.com/goharbor/harbor/assets/10006/ba913a15-4433-425d-960d-7fc9aed9632d)

**Versions:**
Please specify the versions of following systems.

- harbor version: [2.9.1]
- docker engine version: [24.0.5]

**Additional context:**

- **Harbor config files:** You can get them by packaging `harbor.yml` and files in the same directory, including subdirectory.
- **Log files:** You can get them by package the `/var/log/harbor/` .

**Comment by jessehu** [comment]
Also found related issues:  

1. Seems only after the image is pulled again from another machine, the image repo tag can show up in Harbor UI.   
2. What does the unknown arch come from ?

![图片](https://github.com/goharbor/harbor/assets/10006/b3a00817-6682-4afd-9428-1799cf30a27b)

**Comment by stonezdj** [comment]
Work as designed.
The busybox is an image index. (content-type: application/vnd.oci.image.**index**.v1+json)
sha256:c4c67b37cc42396b8a6f6829e3379e86364f642ce6a40604ea4f7c695db0e695 is the image index digest.
The image index has a digest that contains the manifest of all architecture. and for each arch, it has its own manifest. (sha256:ab4b...) (content type: application/vnd.oci.image.**manifest**.v1+json)

Harbor proxy cache is a pull-through cache, when you pull an image under arm64, it will pull the image index first, then the manifest for current platform. Because each manifest pushed to the Harbor needs to be integral manifest,  the full content of the image index can't pushed to Harbor because other platforms, such as amd64, x86, ppc are not pulled and cached. its content is only stored in redis cache. only the arm64 image manifest is cached in Harbor,  it is the (sha256:ab4b...) 

Although 'digest' isn't displayed in the proxy-cache, it doesn't prevent users from pulling the correct image.

For the image index, you can refer to this picture:
https://github.com/opencontainers/image-spec/blob/v1.1.0-rc3/img/media-types.png

**Comment by stonezdj** [comment]
The second question:
The "unknown" arch might be the sbom or other artifact accessory, could you please cat the content of the blob with sha256:3f9c... ?
It can be located in /data/registry/docker/registry/v2/blobs/sha256/3f/3f9c.../data

**Comment by jessehu** [comment]
Thanks @stonezdj 
```
$ cat data/registry/docker/registry/v2/blobs/sha256/3f/3f9cd2f6ba1403532d27d835834dbd0fbabaf25b093264a242854c08501b9b57/data
{
  "schemaVersion": 2,
  "mediaType": "application/vnd.oci.image.manifest.v1+json",
  "config": {
    "mediaType": "application/vnd.oci.image.config.v1+json",
    "digest": "sha256:5ee9e41796b517da1a3ed6b8d193152aff043325ed72013fea39fb8cf53044fc",
    "size": 241
  },
  "layers": [
    {
      "mediaType": "application/vnd.in-toto+json",
      "digest": "sha256:17c159bdd9092a2a53034f3c9d5062c96f1f565242a53a106f37c1438a3458cb",
      "size": 2018,
      "annotations": {
        "in-toto.io/predicate-type": "https://spdx.dev/Document"
      }
    },
    {
      "mediaType": "application/vnd.in-toto+json",
      "digest": "sha256:2e7c86493e090b59ca44486a4a31e2415c6597740e20a9795c09d013ab0df491",
      "size": 5575,
      "annotations": {
        "in-toto.io/predicate-type": "https://slsa.dev/provenance/v0.2"
      }
    }
  ]
}
```

**Comment by stonezdj** [comment]
It is an artifact accessory generated under busybox, and was proxied through proxy cache.
