### ISSUE TITLE
Cloud Postgres and Redis resource sizing recommendation

### ISSUE THREAD

**Issue by josephlim75** [goharbor/harbor#19835]
We are planning to migrate our AWS ECR Registry to the self-hosted Harbor registry in AWS EKS.  We would like to know what would be the best instance type if we are going with `AWS Aurora Postgres` (Multi-AZ) and `AWS Elasticache`.   Currently, we are hosting around 1500 image repositories in ECR.   

What other considerations or fine-tuning that we need to be aware of?  I read about the issue of the number of open connections in Postgres, just wondering if there be any issue with Aurora?  

Thank you

**Comment by MinerYang** [comment]
Hi @josephlim75 ,

Thanks for connecting with us. Although we are not well know about `AWS Aurora Postgres` and `AWS Elasticache`. Here's some tips that come up right now
 - For better HA usage experience, we do recommend to using [harbor-helm ](https://github.com/goharbor/harbor-helm) instead of offline-installer for community users.
 - Could you help to check if `AWS Elasticache` support regular  auth method instead of TLS, since I do remember issues reported that Elastic cache propose to use redisTLS to do connections While Harbor's still nor supported yet.

We will keep update or learn more experiences about using harbor on AWS.
