### ISSUE TITLE
Question regarding  CVE-2022-46463

### ISSUE THREAD

**Issue by Suppi123** [goharbor/harbor#20259]
Hello,

We operate a publicly accessible harbor server. I have been informed by our security department that the current Harbor version on our instance is affected by the vulnerability CVE-2022-46463 is affected.

As far as I understand it, the security vulnerability consists of the fact that a list of all repositories can be accessed via the URL https://demo.goharbor.io/api/v2.0/search?q=/

I have updated the Harbor version to the latest version 2.10.2. The CVE states that the vulnerability was fixed with version 2.5.3. However, it still seems to exist.

I have not found any further information on how bad this vulnerability really is, whether there is a technical necessity for this list to be publicly accessible, or whether it is a feature as described in the CVE.

My question now is whether further action is necessary on my part?

**Comment by wy65701436** [comment]
It's a by designed behavior, which the public project can be accessed by the anonymous user. And please aware that the CVE was marked as Disputed.

My question now is whether further action is necessary on my part?
- No, and we recommend user to use the latest version since the n-2 support policy, v2.5 is not in the support scope.
