### ISSUE TITLE
Issues related to image proxy

### ISSUE THREAD

**Issue by youdian-xiaoshuai** [goharbor/harbor#20701]
**Expected behavior and actual behavior:**
I use the Harbor image proxy function to pull images from Dockerhub, but the problem I encounter is that sometimes it cannot cache the pulled images properly

**Steps to reproduce the problem:**
Firstly, I deployed the Harbor machine to pull other images, and it successfully cached the images in the proxy project I added each time. However, when I used other machines to pull images through this proxy project, I was unable to cache them correctly in my proxy project

**Versions:**
- harbor version: [v2.8.6-c090df90]
- docker engine version: [26.1.4]
- docker-compose version: [v2.28.1
- ]

**Additional context:**

- **Harbor config files:** You can get them by packaging `harbor.yml` and files in the same directory, including subdirectory.
- **Log files:** You can get them by package the `/var/log/harbor/` .
[harborlog.tar.gz](https://github.com/user-attachments/files/16097575/harborlog.tar.gz)

**Comment by teimyBr** [comment]
Which type of Image are you using ? 

How to you pull the image ? Via the tag or the sha digest ? If sha digest which one ? 

I have faced such an Issue in the past with the offiziell Redis image. Issue was fixed by using the Tag + sha digest by the amd64 image and not from the multi arch image. Something in the multi arch was broken, but what i never find out.
