### ISSUE TITLE
Stop stripping curly braces from tag retention policies

### ISSUE THREAD

**Issue by sebhoss** [goharbor/harbor#20806]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**

I'm trying to implement a somewhat semver compatible tag retention policy. I've tried the one from https://github.com/goharbor/harbor/issues/12877#issuecomment-2093283017 but removed the `v` in front since our versions do not use such a prefix. The Harbor UI then stripped the curly braces in front and end of the expression.

**Steps to reproduce the problem:**

1. Paste `{[0-9],[0-9][0-9],[0-9][0-9][0-9],[0-9][0-9][0-9][0-9]}.{[0-9],[0-9][0-9],[0-9][0-9][0-9],[0-9][0-9][0-9][0-9]}.{[0-9],[0-9][0-9],[0-9][0-9][0-9],[0-9][0-9][0-9][0-9]}` into tag retention UI
2. Observe that Harbor strips the first and last curly braces but leaves all others in there resulting in a wrong expression

**Versions:**
Please specify the versions of following systems.

- harbor version: Version v2.11.0-70255684
- docker engine version: not relevant
- docker-compose version: not relevant

**Additional context:**

- **Harbor config files:** You can get them by packaging `harbor.yml` and files in the same directory, including subdirectory.
- **Log files:** You can get them by package the `/var/log/harbor/` .

**Comment by zyyw** [comment]
<img width="1753" alt="Screenshot 2024-08-05 at 11 06 24 AM" src="https://github.com/user-attachments/assets/b8cbdc8c-89f8-4196-b268-32519ea09bbe">

<img width="1419" alt="Screenshot 2024-08-05 at 11 06 47 AM" src="https://github.com/user-attachments/assets/c77d257d-9437-4060-9948-773c6f7729eb">

It seems that the Harbor UI does indeed remove the first and the last curly braces from the tag retention policy, while the http request payload sent to the backend API does contains a valid tag patten. And it does select the artifacts matching the tag patten. Please check the above attached images.

**Comment by stonezdj** [comment]
It is a by design behavior.

**Comment by MinerYang** [comment]
Hi @sebhoss ,

Thanks for reaching out to us and we are aware that this design would made some confusion at your side. Since initially we are trying to simplify this `{}` pattern when creating rules on UI by auto stripping curly braces. However it is indeed cause some viewing trouble here when complex patterns like yours  were showing. Since it is by design and do not affect the filter function, we will not decide to change this behavior immediately, but will put in the backlog if there's more complaining from  community hope this design get changed. Let's keep collecting the feedback from community!

Best,
Miner

**Comment by mtt0** [comment]
Can't believe that such a demand was raised 4 years ago but there is still no change until now.
Obviously, regular expressions are extremely flexible and customizable, and can solve various needs once and for all.

**Comment by raweber42** [comment]
Hi, I just wanna ask a clarifying question regarding the curly braces here. I am using harbor via Crossplane (which uses Terraform). I ran into issues when defining multiple tags in one rule.

So this does not enforce the rules correctly:
`spec.forProvider.tagExcluding = "release-*,review-*,e2e-*,latest,nightly"`

But this does:
`spec.forProvider.tagExcluding = "{release-*,review-*,e2e-*,latest,nightly}"`

Does this mean that the curly braces are _required_ when using multiple tags? Because I never saw that mentioned anywhere in the docs.
I am happy to contribute a fix for the docs.
