### ISSUE TITLE
Login to Harbor reports password error

### ISSUE THREAD

**Issue by CCTV-six** [goharbor/harbor#20869]
**Expected behavior:**
Resolve occasional login authentication failures
**CurrentBehavior**
After changing the authentication mode on the Harbor management page and changing the admin password, occasional login authentication failed

**Comment by ainy0293** [comment]
Hi, I have the same problem.

Pushing the image, it returns unauthorized. After multiple attempts, it succeeds once.

My Harbor version v2.11.1.

**Comment by MinerYang** [comment]
Login may locked up while you entering false auth several times. However, we do need your logs and more details for triage...

**Comment by szofar** [comment]
could be related to #17041

I see the same intermittent issue due to timeout. Harbor has a very long response delay here which exceeds the timeout. This is making my GH automations fail intermittently (so I can assure you the password is being provided correctly every time through automation).

I don't think "loop any docker login/push/pull command until it passes" is an acceptable solution. Can we increase the timeout?
