### ISSUE TITLE
harbor cann't manager dockerfile 

### ISSUE THREAD

**Issue by qianyong2005** [goharbor/harbor#2563]
docker.com can manager dockerfile, user can view dockerfile by image. But harbor no this function，only
manager image，docker file need  other manager tools such as git. Very inconvenient,can increase this function, thank you

**Comment by clouderati** [comment]
Hi @qianyong2005 – thanks for the feedback. This is a bit outside of the scope of what we're planning to do right now, but would love to have you hop on our community call so that we can discuss in greater detail.

I'm going to close this issue for now, but please feel free to speak up again if you have any strong objections. 👍
