### ISSUE TITLE
Harbor should support windows docker image.

### ISSUE THREAD

**Issue by reasonerjt** [goharbor/harbor#3201]
This is more of a verification.
If it doesn't we'll investigate what work is needed.

Need to verify on Windows Docker client.

**Comment by reasonerjt** [comment]
Set the priority to low as the VIC engine may not support Windows in v1.3

**Comment by mdubya66** [comment]
removing the 1.3.

**Comment by stonezdj** [comment]
Tested with docker image : microsoft/windowsservercore in windows 10, 

Update configuration file: C:\ProgramData\docker\config\daemon.json add a line:
"allow-nondistributable-artifacts": ["<harbor-domain>:<harbor-port>"]

Restart docker daemon.

Then docker push works 
**Limitation:**
Then the windows image can be push and pull, but the image size in registry always display the manifest size instead of the real image size.
It is the limitation of registry
