### ISSUE TITLE
use project name in url?

### ISSUE THREAD

**Issue by kapilt** [goharbor/harbor#3203]
having the database sequence number in the url, feels a bit unsightly from a content perspective, preference would be as a name vs the database sequence thats current there, not sure if that's problematic with i18n url spaces.

**Comment by steven-zou** [comment]
@kapilt 
Seems your suggestion is reasonable, we'll discuss this proposal.

**Comment by reasonerjt** [comment]
> having the database sequence number in the url...
@kapilt do you mean url of API?

**Comment by kbusekist** [comment]
The UI page.

For projects, you currently present a URL similar to the following:
`https://harbor/harbor/projects/2/repositories`

When you navigate to the repositories for a given project, the project name does show up.  However, it is displayed as part of the repository name with a url encoded / (%2F) separator.
`https://harbor/harbor/tags/2/myproject%2Fmyrepo`
`https://harbor/harbor/projects/2/repositories/myproject%2Fmyrepo/tags/latest`

What would be ideal is to drop the database sequence number and show the project name as Kapil suggested along with showing only the repo name instead of the encoded project/repo.
`https://harbor/harbor/projects/myproject/repositories`
`https://harbor/harbor/tags/myproject/myrepo`
`https://harbor/harbor/projects/myproject/repositories/myrepo/tags/latest`

**Comment by kapilt** [comment]
another state implementation detail i found leaking is the use of beego session id as the auth token, which leaves downstream clients in a rather unfortunate position if the project makes an implementation change on session management.

**Comment by steven-zou** [comment]
@kapilt 
  For the session id leaking issue, you can open another issue to track. Thanks

**Comment by steven-zou** [comment]
@kapilt @kbusekist 

  We'll consider the improvement of the UI url in later releases, thanks for the suggestions.

**Comment by reasonerjt** [comment]
We don't think of strong enough reason to remove ID from the url on UI.
Closing as won't fix.
