### ISSUE TITLE
Block image push when Clair severity is High

### ISSUE THREAD

**Issue by vasartori** [goharbor/harbor#3211]
Is possible block push of images when severity on clair is High and the issue has "fixed version"
I have found this environment variables on ui:

PROJECT_CONTENT_TRUST=1
PROJECT_VULNERABLE=1
PROJECT_SEVERITY=high

What this variables does?

**Comment by reasonerjt** [comment]
Hi 
Do you mean block image "pull" or "push"? 
It can't be scanned before it's pushed.
But if you mean pull, we added some code but it's now controlled by env variable of the "ui" container.

**Comment by vasartori** [comment]
Push. But is possible block pull of "unsecure" images?
In my case, I want block push images with high security issue with corrections. I want prevent new images with critical issues.

**Comment by helgi** [comment]
Blocking on pull seems like the right approach here, that however would require Harbour to not make an image available to pull until it has been scanned and meets the criteria; effectively quarantines the image.

**Comment by vasartori** [comment]
Block pull is not good on Auto scaling environments.
Imagine the scenario: 
The user has been pushed a OK image, after a time, this image comes insecure, I'll block the scaling of application... 
On pull I think it needs to be handled in a diferent layer...

**Comment by helgi** [comment]
That's exactly how it could work and it would break the application; that can be part of a policy. For example, it is detected as having high CVEs, the user has X days to update and beyond that time it is blocked, a critical one could be a full block.

Having an option where you can pull the API for "bad" images based on policy without blocking anything could help feed into other tools (ASGs, other security tools, etc)

A `push` (while I would also like that) would only block the problem at this point in time, not help protect against images that are basically bit-rotting.

All of that depends on each person taste and security teams perspective. That's why it can be a configurable policy, I would think.

**Comment by vasartori** [comment]
@helgi Let's make this pull request together? Did you have time for this?

**Comment by helgi** [comment]
@vasartori I do not, sorry. Not actively using Harbour. Evaluating it still.

**Comment by vasartori** [comment]
@helgi no problem :)
