### ISSUE TITLE
How to call the docker registry Rest API

### ISSUE THREAD

**Issue by paulohleal** [goharbor/harbor#3274]
Hi,

I am running a private registry with harbor, and most of my images are overwritten via image:tag format.
My registry is constantly growing bigger, and I believe it is because of what is described on this link: https://github.com/mortensteenrasmussen/docker-registry-manifest-cleanup
So I believe I need to run a Manifest Cleanup on my private registry. To do so I need to access the docker registry Rest API to call the "/v2/_catalog" path and discover which images I can delete.
How can I access this API?

Ps. I tried to use the habor API (like calling the path: api/repositories/aplicacoes%2Fcontrole-acesso/tags) but it only returns the images with an actual tag, not the ones accessible only by the image@digest format)

Best Regards,

Paulo Leal

**Comment by ezeteze** [comment]
Hello,

I am facing the exact same issue described here. 
There is an MR on docker gc to handle this here https://github.com/docker/distribution/pull/2302 .
Unfortunately since we can not directly access the registry API solutions like this one https://github.com/mortensteenrasmussen/docker-registry-manifest-cleanup don't work.
For the time being i have not found any other solution than to expand the registry storage but can't continue doing this forever. 

Best Regards,
Chris
