### ISSUE TITLE
[Longevity] Get 504 when to call "GET /api/policies/replication?project_id=*"

### ISSUE THREAD

**Issue by wy65701436** [goharbor/harbor#4113]
I tried to click Replication under project, but get this error.

Proxy Log:

Jan 24 02:36:31 172.18.0.1 proxy[662]: 2018/01/24 02:36:31 [error] 8#0: *258520 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 10.166.17.41, server: , request: "GET /api/policies/replication?project_id=27 HTTP/1.1", upstream: "http://172.18.0.6:8080/api/policies/replication?project_id=27", host: "*****.vmware.com", referrer: "https://******.vmware.com/harbor/projects/27/replications"

![image](https://user-images.githubusercontent.com/2841473/35311748-ec8e4ed0-006c-11e8-9573-e0a92ce0c8c3.png)

**Comment by ywk253100** [comment]
Cannot reproduce this issue, defer it.

**Comment by GYICN** [comment]
I had the same problem.
For a certain period of time, the connection times out and then returns to normal.I guess it is the problem of docker's network.
However, I could not find the cause of the problem, and it could not be repeated. The time of the problem was uncertain, and it appeared several times.
Please excuse my poor English.Here is the proxy log:
`May 29 10:58:07 172.18.0.1 proxy[30556]: 172.18.0.1 - "GET / HTTP/1.1" 200 810 "-" "curl/7.29.0" 0.010 0.010 .
May 29 10:58:07 172.18.0.1 proxy[30556]: 172.18.0.1 - "GET /api/systeminfo HTTP/1.1" 200 365 "-" "curl/7.29.0" 0.210 0.210 .
May 29 10:58:27 172.18.0.1 proxy[30556]: 172.18.0.1 - "GET /api/repositories/top HTTP/1.1" 499 0 "-" "curl/7.29.0" 19.729 - .
May 29 10:58:37 172.18.0.1 proxy[30556]: 172.18.0.1 - "GET / HTTP/1.1" 200 810 "-" "curl/7.29.0" 0.010 0.010 .
May 29 10:58:37 172.18.0.1 proxy[30556]: 172.18.0.1 - "GET /api/systeminfo HTTP/1.1" 200 365 "-" "curl/7.29.0" 0.008 0.008 .
May 29 10:58:45 172.18.0.1 proxy[30556]: 10.16.43.191 - "GET /v2/quay.io/kubernetes-ingress-controller/nginx-ingress-controller/blobs/sha256:fb88f11f887afa8eecafe037f4565b559c74c63aba9b30d9d1d2718774837985 HTTP/1.1" 504 176 "-" "docker/17.03
.0-ce go/go1.7.5 git-commit/60ccb22 kernel/3.10.0-957.el7.x86_64 os/linux arch/amd64 UpstreamClient(Go-http-client/1.1)" 60.008 60.008 .
May 29 10:58:45 172.18.0.1 proxy[30556]: 10.16.43.191 - "GET /v2/quay.io/kubernetes-ingress-controller/nginx-ingress-controller/blobs/sha256:c22b7a5a8190ae74c5bee9e0a8ca51316a7f16f94f7fba4dea423ad6c1d85f44 HTTP/1.1" 504 176 "-" "docker/17.03
.0-ce go/go1.7.5 git-commit/60ccb22 kernel/3.10.0-957.el7.x86_64 os/linux arch/amd64 UpstreamClient(Go-http-client/1.1)" 60.009 60.009 .
May 29 10:58:45 172.18.0.1 proxy[30556]: 10.16.43.191 - "GET /v2/quay.io/kubernetes-ingress-controller/nginx-ingress-controller/blobs/sha256:22ebbdddfabb1cdcb6b7b562533d7624e555a05f62f0f3f7e81b7c4b34a0e12d HTTP/1.1" 504 176 "-" "docker/17.03
.0-ce go/go1.7.5 git-commit/60ccb22 kernel/3.10.0-957.el7.x86_64 os/linux arch/amd64 UpstreamClient(Go-http-client/1.1)" 60.009 60.009 .
May 29 10:58:45 172.18.0.1 proxy[30556]: 2019/05/29 02:58:45 [error] 13#0: *460231 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 10.16.43.191, server: , request: "GET /v2/quay.io/kubernet
es-ingress-controller/nginx-ingress-controller/blobs/sha256:fb88f11f887afa8eecafe037f4565b559c74c63aba9b30d9d1d2718774837985 HTTP/1.1", upstream: "http://172.18.0.5:8080/registryproxy/v2/quay.io/kubernetes-ingress-controller/nginx-ingress-co
ntroller/blobs/sha256:fb88f11f887afa8eecafe037f4565b559c74c63aba9b30d9d1d2718774837985", host: "acaas-registry.agree:80"
May 29 10:58:45 172.18.0.1 proxy[30556]: 2019/05/29 02:58:45 [error] 12#0: *460227 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 10.16.43.191, server: , request: "GET /v2/quay.io/kubernet
es-ingress-controller/nginx-ingress-controller/blobs/sha256:c22b7a5a8190ae74c5bee9e0a8ca51316a7f16f94f7fba4dea423ad6c1d85f44 HTTP/1.1", upstream: "http://172.18.0.5:8080/registryproxy/v2/quay.io/kubernetes-ingress-controller/nginx-ingress-co
ntroller/blobs/sha256:c22b7a5a8190ae74c5bee9e0a8ca51316a7f16f94f7fba4dea423ad6c1d85f44", host: "acaas-registry.agree:80"
May 29 10:58:45 172.18.0.1 proxy[30556]: 2019/05/29 02:58:45 [error] 14#0: *460226 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 10.16.43.191, server: , request: "GET /v2/quay.io/kubernet
es-ingress-controller/nginx-ingress-controller/blobs/sha256:22ebbdddfabb1cdcb6b7b562533d7624e555a05f62f0f3f7e81b7c4b34a0e12d HTTP/1.1", upstream: "http://172.18.0.5:8080/registryproxy/v2/quay.io/kubernetes-ingress-controller/nginx-ingress-co
ntroller/blobs/sha256:22ebbdddfabb1cdcb6b7b562533d7624e555a05f62f0f3f7e81b7c4b34a0e12d", host: "acaas-registry.agree:80"
May 29 10:58:47 172.18.0.1 proxy[30556]: 2019/05/29 02:58:47 [error] 14#0: *460239 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 10.16.43.190, server: , request: "GET /v2/quay.io/kubernet
es-ingress-controller/nginx-ingress-controller/manifests/0.19.0 HTTP/1.1", upstream: "http://172.18.0.5:8080/registryproxy/v2/quay.io/kubernetes-ingress-controller/nginx-ingress-controller/manifests/0.19.0", host: "acaas-registry.agree:80"
May 29 10:58:47 172.18.0.1 proxy[30556]: 10.16.43.190 - "GET /v2/quay.io/kubernetes-ingress-controller/nginx-ingress-controller/manifests/0.19.0 HTTP/1.1" 504 176 "-" "docker/17.03.0-ce go/go1.7.5 git-commit/60ccb22 kernel/3.10.0-957.el7.x86
_64 os/linux arch/amd64 UpstreamClient(Go-http-client/1.1)" 60.002 60.002 .`
