### ISSUE TITLE
how to login via token ?

### ISSUE THREAD

**Issue by momobou** [goharbor/harbor#4227]
Hi,

Can we now login to harbor registry using token?

Thanks

**Comment by wanghaiqing2015** [comment]
yes, we need this function

**Comment by kumy** [comment]
@reasonerjt We are also interested with this functionality, in our use case, we would like to use them via `docker login`.

**Comment by reasonerjt** [comment]
Let me put this into backlog, but based on the description, it's extremely unclear to me what's the requirement.

**Comment by cartyc** [comment]
@reasonerjt We have a similar need for the use of a token or service account for pushing images.

The use case for us is that we have  are looking to use Jenkins to auto-build our images and push to our Harbor registry. We could use our accounts to login to Docker via jenkins, this could cause issues for tracking and those accounts probably have more permissions than a service account needs.

Being able to create a token or service account (bound to a specific project) to do those automated builds would be a great help.

This issue seems to be working toward something similar. https://github.com/goharbor/harbor/issues/4581

**Comment by reasonerjt** [comment]
@cartyc for your scenario, we are working on robot account, 
Please see:
https://github.com/goharbor/harbor/issues/6565
