### ISSUE TITLE
What about adding a quota feature for repository list and tag list

### ISSUE THREAD

**Issue by KeepCaim** [goharbor/harbor#6271]
Hello，I use the harbor 1.5.1 as private container-image repository. it‘s very good. But it has no restrictions on repository and tag quotas，For example: how many repositories can be created per project and how many tags can be created per repository. And This quota should be set by the user. The problem it caused，When a repository has many tags, the query is slow.

**Comment by clouderati** [comment]
Quotas are on our roadmap, timing TBD.

**Comment by KeepCaim** [comment]
Thanks，I look forward to that day coming soon.

**Comment by KeepCaim** [comment]
> Quotas are on our roadmap, timing TBD.

Thanks，I look forward to that day coming soon.

**Comment by danielzhanghl** [comment]
i did a prototype for two enhancement based on stable release 1.6: project quota and connection to keycloak .
code is under:
https://github.com/goharbor/harbor/compare/release-1.6.0...danielzhanghl:release-1.6.0

for keycloak connection, most of the code are common to UAA:
1.  add a new configuration for realm,
2.  and the links to query user/ get token are different,
3.  the return structure from keycloak and UAA is different,.
so in this prototype I did not separate them, just change the UAA(so it's prototype only....)
it's using keycloak direct grant access type, and the client service token need query user capability.

for qutoa, the idea are:
1. project quota could be set/modified when create/modify project, it is used to limit the images that user could push, for example, 1024M(it's default value).

2. image size is queried from image manifest file: size of all layers and manifest file size.
when user upload a layer or manifest, project usage will be checked with quota, if it's going to exceed, the load will be blocked, otherwise, the project usage will be counted.

3. when image is pushed, the usage will be re-calculated by reading all the images manifest in the project, therefore, there maybe "usage" great than "quota", but it's not the real storage situation,  as docker client did not upload the layer but only refer it in the images manifest file. and the next upload attempt will be blocked as the usage is great than quota.

4. if user push two images, with part of or all the layers are same, the total size used is counted twice though the layers are shared.

there is no limitation for helm chart now, as I see there is "counter"  introduced in chart repo in the latest code, guess you are going to use that to limit the number of chart allowed to load.

hope these could help on qutoa related change.
