### ISSUE TITLE
replication job pending

### ISSUE THREAD

**Issue by louyiping** [goharbor/harbor#6415]
If you are reporting a problem, please make sure the following information are provided:

in our production env，the harbor's replication job is pending all the time for nearly one day，and it‘s ok after restart harbor.

**Versions:**
Please specify the versions of following systems.
- harbor version: 1.6.0
- docker engine version: 1.12.6
- docker-compose version: 1.13.0

**Additional context:**
And I check the log，and only jobservice.log had some strange like:  

![image](https://user-images.githubusercontent.com/9589048/49418856-26688b80-f7bf-11e8-8c0b-5d9ab35a0a34.png)
It seems has Receive the event but can't do the job

**Comment by wy65701436** [comment]
@louyiping please upload full logs.

**Comment by louyiping** [comment]
@wy65701436   here, thanks.
[jobservice.zip](https://github.com/goharbor/harbor/files/2642667/jobservice.zip)

**Comment by louyiping** [comment]
And the phenomenon seems start from 
“Nov 29 11:51:29 172.18.0.1 jobservice[913]: 2018-11-29T03:51:29Z [INFO] Receive event 'register_hook' with data(unformatted): map[string]interface {}{"job_id":"9ca1d01c2b7da09580f7358b", "hook_url":"http://ui:8080/service/notifications/jobs/replication/120714"}”

**Comment by lf1029698952** [comment]
+1
and when stop replication job, ui errors:
```
failed to stop job id-7252 uuid-7ddd6512cdc0e0b338bb35d1: http error: code 500, message {"code":10008,"message":"Stop job failed with error","details":"job '7ddd6512cdc0e0b338bb35d1' is not a running job"}
failed to stop job id-4818 uuid-af6215e44309754ad9003fe9: http error: code 404, message {"code":10013,"message":"object is not found","details":"job 'af6215e44309754ad9003fe9'"}
```

**Comment by louyiping** [comment]
@wy65701436  hi，anything update？
I think we should enhance the reliability of replication at first. Today I have met another question about replicating. I find few replication job have pending for a week. And I can't stop it or delete it by Restful API. 
And in the process of using harbor , almost all of the problems I encountered were replication. Such as, replication error because of network and other things , but sometimes it will not  restart replication again. If someone told me that he can't pull the image and I must munually click the replication button.
Sometimes it happened frequently.
I really hope harbor could enhance this part. If I can help, I'd love to.
Thank you very much.

**Comment by steven-zou** [comment]
Mark it with label bug to start doing some investigation work and then locate the root cause.

**Comment by louyiping** [comment]
@steven-zou Thanks.

**Comment by steven-zou** [comment]
Let's move the issue to SP52 as we still need more time to locate the root cause.

**Comment by steven-zou** [comment]
Status webhook is enhanced, the status will be correctly switched.

**Comment by SchoIsles** [comment]
I have ran into the same problem, all new replication job's status is pending, and stop job action faild, with log err `object is not found`

harbor version: 1.7.6
docker version: 19.03

Clean those pending jobs from db failed to solve the problem，
After restart the jobserver, problem solved, 
by analyze logs, it looks like made a fully replication

But I'm not sure it's jobserver's initiate work or has relation with my cronjob？
I created a replication role for each project with trigger mode manual, triggered by script running at 04:00，has been running for two months，the fully repliccation work is not within my schedule

Does this problem's root cause has been located in version 1.8?
If not, I wish my situation can provide some help
