### ISSUE TITLE
"Sign up" button is missing in the home page

### ISSUE THREAD

**Issue by wy65701436** [goharbor/harbor#6474]
A user has no way to create a new account。

![image](https://user-images.githubusercontent.com/2841473/49581829-2c609700-f98e-11e8-8177-c44776c95fdc.png)

**Comment by steven-zou** [comment]
@wy65701436 

If the auth_type is 'localdb', this will be valid. For other auth types like LDAP etc., there should no `SignUp` link if I'm not mistaken.

**Comment by wy65701436** [comment]
It’s db auth, still no sign up button.

**Comment by reasonerjt** [comment]
@wy65701436 also there's a flag to disable user sign up:
https://github.com/goharbor/harbor/blob/master/make/common/templates/adminserver/env#L5

**Comment by zhoumeina** [comment]
@wy65701436 ， could you please check if config self_registration?

**Comment by zhoumeina** [comment]
I found all the setting in harbor.cfg is good. auth mode is db and self_registration = on, but in the system info api it returns self-registration false to frontend. 
I think this is the root cause for this issue. 
![image](https://user-images.githubusercontent.com/4946616/49624406-3e811a80-fa0c-11e8-8dd9-dafe7a4d5f1d.png)
![image](https://user-images.githubusercontent.com/4946616/49624417-4b9e0980-fa0c-11e8-83e3-4e7618ba5f61.png)

**Comment by wy65701436** [comment]
close it as not a bug.
