### ISSUE TITLE
Error occured when to retag a image with special character

### ISSUE THREAD

**Issue by wy65701436** [goharbor/harbor#6540]
The UI should block this input, and give user the tips about the naming convention of tag.

**Comment by wy65701436** [comment]
<img width="1321" alt="image" src="https://user-images.githubusercontent.com/2841473/50074201-1f596880-0216-11e9-977a-6c52c19a333c.png">

**Comment by zhoumeina** [comment]
@cd1989 , I think the backend api still has something not correct. It need to always returns a json format. This is because backend returns a html page. However, the frontend still think it is a string message. don't returns a redirect page in one api. Because harbor is a SPA application. 

I think fix this issue need to 
1 Modify the backend api to return in json format. 
2 block the special chars in frontend using Regex。 
3 After the dialog closed , the input value in the dialog should be cleared. 
4 Should add tooltip to show users only can input 26 chars and numbers in the input

**Comment by zhoumeina** [comment]
![image](https://user-images.githubusercontent.com/4946616/50076168-e4f2ca00-021b-11e9-9cae-7313e791f290.png)
The value still there when reopen the dialog.

**Comment by zhoumeina** [comment]
![image](https://user-images.githubusercontent.com/4946616/50076232-18355900-021c-11e9-8d71-2782ea91e000.png)
the request expect backend to return a json. but backend returns a html actually.

**Comment by cd1989** [comment]
I will fix it today

**Comment by zhoumeina** [comment]
fixed by:#6553
