### ISSUE TITLE
A bug happened whern call delete tag api

### ISSUE THREAD

**Issue by lycclsltt** [goharbor/harbor#6679]
I only want to delete tag A, but after I call /repositories/{repo_name}/tags/{tag} to delete a tag A, tag A , B all be removed.  I think it is a bug.

**Comment by steven-zou** [comment]
@lycclsltt 

Tag A and Tab share the same layers, right?

The current behavior is caused by the limitation of the upstream registry.

If you want to change one tag, you can directly overwrite that tag with new content.
If you want to totally delete that tag and keep other tags which share the same layers, so far, no way provided to do that.

**Comment by vasicvuk** [comment]
I would call this a critical bug that needs to be solved. If i tag tested development image into production version and delete development version both production and development images will be gone.
