### ISSUE TITLE
Is there a way to force stop the online garbage collection?

### ISSUE THREAD

**Issue by louyiping** [goharbor/harbor#6719]
As we all know, In the process of online garbage collection, we can not push image to harbor. If I click the button "gc now", I can not stop the gc task actually, even restart the harbor.
I think it's a important function. In our env , the gc task will take two or three hours. And if I click the button by mistake or other things happen, I want to stop the online gc. Or I must wait a few hours and that's terrible. It will influence all our company's engingeers if it is a working day.

**Comment by louyiping** [comment]
And  I have  another question.
Our env is fully containerization. If engineers can not push image, it will be greatly affected. So I must execute the online gc in the small hour.
But the timed task of gc can not indicate the precise hour, I dare not use it.

**Comment by louyiping** [comment]
I have found that there is a button named cancel "read-only" mode. But If the harbor is in the process of gc and I cancel the "read-only" mode , it will be risky.
So I still want to stop the online gc manually.

**Comment by wy65701436** [comment]
As the solution of GC, there is no way to cancel it. Even we provide a button to stop it, it actually continues running in the backend, that's because the GC job calls the registry GC command to do the garbage collection, and no way to stop it besides killing the process -- this is more dangerous. For the details, you can refer to the docker official document.

To resolve your issue, you can wait for the cron task in the next release, you can do the GC with high frequency.

**Comment by louyiping** [comment]
@wy65701436  Thanks. I will do some research about it.

**Comment by louyiping** [comment]
And thanks a lot to Harbor group. Online gc saves my life :)

**Comment by reasonerjt** [comment]
@louyiping I'm closing this issue as once the GC starts theres no way to stop it.

**Comment by ysicing** [comment]
The GC process hasn't ended since 0? Is there a way to cancel it? Looks like restarting the service won't work either
