### ISSUE TITLE
Integration testing against CockroachDB

### ISSUE THREAD

**Issue by heww** [goharbor/harbor#6942]
Test using CockroachDB as database for harbor.

**Comment by KarstenSiemer** [comment]
well, how did this go?

**Comment by KarstenSiemer** [comment]
okay, it does not work for several reasons.
1. You can't correctly set up ssl, since you can only configure the sslmode but not the verifycation and client cert settings
2. The connectory are running non compatible postres native functions like 
`panic: migrate: pq: unknown function: pg_advisory_lock()`
since it is doing locking it will also have problem with the transaction isolation levels and retry mechanisms etc.
I am puzzled why there is a notion of cockroachdb inside of [binary.Dockerfile](https://raw.githubusercontent.com/goharbor/harbor/master/make/photon/notary/binary.Dockerfile) 

Would be amazing to support cockroachdb since it is the most robust and secure way of running a database inside of kubernetes.

**Comment by HubertBos** [comment]
Another distributed postgres DB is yugabyteDB, apparently, they run faster than CockroachDB and use pg_advisory_lock in tests:

https://github.com/yugabyte/yugabyte-db/blob/master/src/postgres/src/test/regress/expected/advisory_lock.out
