### ISSUE TITLE
Allow ignoring some CVE when pulling the image

### ISSUE THREAD

**Issue by symgryph** [goharbor/harbor#6999]
I love ❤️ the clair integration, but would really like to see the ability to choose ‘high with known vendor solutions ‘ rather than just high for running prevention.

**Comment by reasonerjt** [comment]
I understand the problem you are facing, however, I don't think it's the right thing to do.  
A vulnerability without a known solution is not less harmful than a vulnerability with solution.

If you want to unblock pulling the vulnerable image you can:
a) Rebuild the image to use a package without vulnerability
b) Turn off the policy, so you ignore all vulnerabilities.

**Comment by symgryph** [comment]
I liked the idea of 'blacklisting' or embargoing a particular vulnerability that I choose to accept the risk for. "Whitelist" or blacklist would work great.

**Comment by michmike** [comment]
yes absolutely, the idea of a whitelist (not a blacklist) of particular vulnerabilities will allow the image to be unblocked with possibly a warning in the logs

so from a feature perspective, what we need is
1. allow specific CVEs to be white listed so that images are not blocked on them
2. when an image is scanned it would have been blocked otherwise, log it in the log that a whitelist was applied to allow this CVE

In future, we can associate the whitelist with a time interval, but let's not consider this for an MVP
We can plan for this for post 1.8 release of Harbor

**Comment by reasonerjt** [comment]
An example of the white list yaml:
https://github.com/arminc/clair-scanner#example-whitelist-yaml-file

**Comment by reasonerjt** [comment]
This will be implemented in v1.9.0 and I'll use #7942 to track the work.
