### ISSUE TITLE
Clair  doesn't report Vulnerability errors

### ISSUE THREAD

**Issue by abhishek-kumar0409** [goharbor/harbor#7048]
Team,

I tried to pull a golang:1.7.1 image and was trying to scan it. I know that there are certain vulnerabilities in the image but I'm unable to view it in the Harbor. The result says "No vulnerability found". I've installed harbor with clair and chartmuseum. 

Can someone suggest what could be the issue and how to proceed ? 

![clair_vulnerability](https://user-images.githubusercontent.com/8438638/53577300-6ad7ad80-3b9b-11e9-8372-6ec259b530d2.png)

**Comment by hasonhai** [comment]
I think you can try to upload some other images to narrow down where the problem is. Maybe that your image is clean do it does not generate any warning or critical vulnerabilities.

Clair downloaded the databases (as I remember) of vulnerabilities from 5 different sources based on the OS of the images. It's often that scanning an Ubuntu-based image will report a few warning and critical vulnerabilities, while an simple alpine images will generate none.

Just read the logs of Clair to see  whether it can download the database, then check whether the image is clean or Clair cannot scan the vulnerabilities of the image.

**Comment by abhishek-kumar0409** [comment]
Hi @hasonhai ,

I have a different environment where the images are being scanned perfectly. I'm not sure what special I did to bring Harbor up, couple of weeks ago. However, I'm facing issues while setting-up the harbor in a different environment. I tried multiple times but failed each time.  The installation is successful but image scanning completes in 10 secs. Even for ubuntu image, I don't see any vulnerabilities being reported by harbor-clair. So, I think there is something wrong with the installation or possibly DB-population. I will try to analyze the logs tomorrow and (if required) will share it with you for further help.

![screenshot from 2019-02-28 23-21-40](https://user-images.githubusercontent.com/8438638/53587177-b85e1580-3baf-11e9-9f61-ff01e38ca2aa.png)

**Comment by abhishek-kumar0409** [comment]
@hasonhai ,

This time I pushed an ubuntu image to harbor's registry and tried scanning it from the Harbor portal. I see few errors in the log files. But, I'm able to access these  URL's in the browser. There is no proxy issue.

Can you please suggest some troubleshooting steps?

**Sample Response from**: https://nvd.nist.gov/feeds/xml/cve/2.0/nvdcve-2.0-2007.meta
lastModifiedDate:2019-03-02T04:08:57-05:00
size:26238718
zipSize:2036584
gzSize:2036450
sha256:F86F5DD4006D1EA1922377CA6C2417CDEB3F81121976983C92449F8E0C1B45F8


-------------------------------------------------
Clair Log File Output (while scanning the ubuntu image)
--------------------------------------------------

Mar  2 17:11:32 172.27.0.1 clair[32260]: {"Event":"could not get NVD data feed hash","Level":"warning","Location":"nvd.go:137","Time":"2019-03-02 11:41:32.369711","data feed name":"2007","error":"Get https://nvd.nist.gov/feeds/xml/cve/2.0/nvdcve-2.0-2007.meta: dial tcp: lookup nvd.nist.gov: Temporary failure in name resolution"}
Mar  2 17:11:34 172.27.0.1 clair[32260]: {"Event":"Handled HTTP request","Level":"info","Location":"router.go:57","Time":"2019-03-02 11:41:34.081895","elapsed time":875085,"method":"POST","remote addr":"172.29.0.6:34222","request uri":"/v1/layers","status":"201"}
Mar  2 17:11:34 172.27.0.1 clair[32260]: {"Event":"Handled HTTP request","Level":"info","Location":"router.go:57","Time":"2019-03-02 11:41:34.083280","elapsed time":1051595,"method":"POST","remote addr":"172.29.0.6:34222","request uri":"/v1/layers","status":"201"}
Mar  2 17:11:34 172.27.0.1 clair[32260]: {"Event":"Handled HTTP request","Level":"info","Location":"router.go:57","Time":"2019-03-02 11:41:34.084259","elapsed time":679624,"method":"POST","remote addr":"172.29.0.6:34222","request uri":"/v1/layers","status":"201"}
Mar  2 17:11:34 172.27.0.1 clair[32260]: {"Event":"Handled HTTP request","Level":"info","Location":"router.go:57","Time":"2019-03-02 11:41:34.093856","elapsed time":885532,"method":"POST","remote addr":"172.29.0.6:34222","request uri":"/v1/layers","status":"201"}
Mar  2 17:11:34 172.27.0.1 clair[32260]: {"Event":"Handled HTTP request","Level":"info","Location":"router.go:57","Time":"2019-03-02 11:41:34.098339","elapsed time":4113966,"method":"GET","remote addr":"172.29.0.6:34222","request uri":"/v1/layers/a890d8fa03187fa0d3650609b16a2b8938f3677e8cf5e153b0fbd4d0d5d31fff?features\u0026vulnerabilities","status":"200"}
Mar  2 17:11:42 172.27.0.1 clair[32260]: {"Event":"could not get NVD data feed hash","Level":"warning","Location":"nvd.go:137","Time":"2019-03-02 11:41:42.377053","data feed name":"2008","error":"Get https://nvd.nist.gov/feeds/xml/cve/2.0/nvdcve-2.0-2008.meta: dial tcp: lookup nvd.nist.gov: Temporary failure in name resolution"}
Mar  2 17:11:52 172.27.0.1 clair[32260]: {"Event":"could not get NVD data feed hash","Level":"warning","Location":"nvd.go:137","Time":"2019-03-02 11:41:52.381100","data feed name":"2009","error":"Get https://nvd.nist.gov/feeds/xml/cve/2.0/nvdcve-2.0-2009.meta: dial tcp: lookup nvd.nist.gov: Temporary failure in name resolution"}
Mar  2 17:12:02 172.27.0.1 clair[32260]: {"Event":"could not get NVD data feed hash","Level":"warning","Location":"nvd.go:137","Time":"2019-03-02 11:42:02.389047","data feed name":"2010","error":"Get https://nvd.nist.gov/feeds/xml/cve/2.0/nvdcve-2.0-2010.meta: dial tcp: lookup nvd.nist.gov: Temporary failure in name resolution"}
Mar  2 17:12:12 172.27.0.1 clair[32260]: {"Event":"could not get NVD data feed hash","Level":"warning","Location":"nvd.go:137","Time":"2019-03-02 11:42:12.393027","data feed name":"2011","error":"Get https://nvd.nist.gov/feeds/xml/cve/2.0/nvdcve-2.0-2011.meta: dial tcp: lookup nvd.nist.gov: Temporary failure in name resolution"}
Mar  2 17:12:22 172.27.0.1 clair[32260]: {"Event":"could not get NVD data feed hash","Level":"warning","Location":"nvd.go:137","Time":"2019-03-02 11:42:22.402178","data feed name":"2012","error":"Get https://nvd.nist.gov/feeds/xml/cve/2.0/nvdcve-2.0-2012.meta: dial tcp: lookup nvd.nist.gov: Temporary failure in name resolution"}
Mar  2 17:12:32 172.27.0.1 clair[32260]: {"Event":"could not get NVD data feed hash","Level":"warning","Location":"nvd.go:137","Time":"2019-03-02 11:42:32.412811","data feed name":"2013","error":"Get https://nvd.nist.gov/feeds/xml/cve/2.0/nvdcve-2.0-2013.meta: dial tcp: lookup nvd.nist.gov: Temporary failure in name resolution"}
Mar  2 17:12:42 172.27.0.1 clair[32260]: {"Event":"could not get NVD data feed hash","Level":"warning","Location":"nvd.go:137","Time":"2019-03-02 11:42:42.422265","data feed name":"2014","error":"Get https://nvd.nist.gov/feeds/xml/cve/2.0/nvdcve-2.0-2014.meta: dial tcp: lookup nvd.nist.gov: Temporary failure in name resolution"}
.........
..........

**Comment by hasonhai** [comment]
> Can you please suggest some troubleshooting steps?

Hi @abhishek-kumar0409, the problem is not related to Harbor. The logs said that it cannot resolve the URL. The reason maybe your pod cannot connect to the DNS server.
- If you have network policies in your k8s cluster, make sure it allow traffic to kubedns or coredns pod.
- Check if other pod in same namespace can resolve the dns
- Check if the dnsserver not hangs (normally, I just delete the dns server pod to let k8s re-create it)
- You can log into the pod, check the routing table inside the pod to see if it routes traffic correctly. In some clusters that have compute nodes not identical in network interfaces, the network plugin may pick the wrong interface to listen, it create a situation in which only identical compute nodes can talk to each other and are seperated from other compute node group (it's like a multiple sub-VLAN inside a VLAN).
- If your company uses a private dns server, check that also

**Comment by abhishek-kumar0409** [comment]
Hi @hasonhai 

The issue still persists. I understand that the problem is not related to harbor. Although I'm able to access the URL's in the browser. I'm experiencing some weird environment issues. 

I'll request you to close this bug for the time-being. I temporarily suspended my work on this because of  this issue, probably if I face this issue in another environment then I'll re-open it.

**Comment by Amit-Thawait** [comment]
I faced the same issue where when I used to upload a docker image (say redis:4.0.9) to https://demo.goharbor.io/ it used to show vulnerabilities where when I deployed Harbor in my cluster it was showing as "**No vulnerability**".

The strategy I used to debug was to first check the harbor-database pod and see if there are vulnerabilities populated in the postgres DB. 
Not to my surprise, it was empty. Hence it was showing 'No vulnerability' upon image scanning.

Next thing I investigated was harbor-database pod restarts which was around 7.
Upon describing the harbor-database pod I checked the exit code of 'Last State' section and found out that the exit code was 137 (which represents Out of memory error).
It means my harbor-database pod used to run for say 30 mins then it used to restart and was doing the same loop because it didn't had sufficient memory **because the nodes of my kubernetes cluster(2 nodes with 2 vcpu and 2 GB RAM) were too small for clair to run along with other components of Harbor**.

I created a new cluster with increased size(4 vCPU and 8 GB RAM) and everything worked fine.

**Please note that it takes from around 40 mins to 90 mins depending upon your internet speed to fully populate the vulnerability DB in postgres.**
