### ISSUE TITLE
Support external CA cert config on Harbor Helm chart

### ISSUE THREAD

**Issue by ericvmw** [goharbor/harbor#7069]
Since Harbor supports external cert / key for SSL cert in Harbor Helm chat, configuring external CA cert on Harbor Helm chart would be needed since such external cert is signed by external CA cert. We'll need this for a complete external SSL cert configuration.

**Comment by reasonerjt** [comment]
@ericvmw 
Does it mean you need helm to **sign** the certificate using the external CA during deployment?

I hope we don't need to do this because relying helm to sign the certificate is not a good practice, the reason we add some code to support it is to simplify the process for user to play with the chart.

For serious use, IMO, user should have an external process to manage the certificate of Harbor, i.e. user should integrate with his own certificate management tools to generate the cert and have the cert configured in `values.yaml`

**Comment by ericvmw** [comment]
@reasonerjt No, we don't expect to use helm to sign cert, instead we need to be able to pass the external CA cert to Harbor so that developers can download the CA cert from Harbor. Both the CA cert and the signed SSL cert are generated outside Harbor. Currently Harbor helm chart doesn't allow passing external CA cert.

**Comment by reasonerjt** [comment]
@ericvmw thanks for the clarification.
