### ISSUE TITLE
False positive in Vulnerability check

### ISSUE THREAD

**Issue by isas2** [goharbor/harbor#7073]
We have compiled our image based on debian:9-slim and installed updated packages from the distribution sid. But after scanning, these packages are still labeled as containing vulnerabilities, although in the CVE description these packages are marked as fixed.
Our image on Docker Hub: isas21/debian:update-slim
![image](https://user-images.githubusercontent.com/48231479/53780770-6bc06480-3f38-11e9-81d9-d69d640f82df.png)
![image](https://user-images.githubusercontent.com/48231479/53780833-9e6a5d00-3f38-11e9-87ee-12774b458978.png)

**Comment by reasonerjt** [comment]
Reproduced this issue in my env, looks like something wrong in Clair, looking into it..

**Comment by reasonerjt** [comment]
Hi, checked the code of clair:
https://github.com/coreos/clair/blob/release-2.0/ext/featurens/aptsources/aptsources.go

It seems the the file `/etc/apt/sources.list` in your image, this line:
`deb http://deb.debian.org/debian stretch main contrib non-free`

makes Clair thinks the image is built based on `debian:stretch` rather than `sid` so it cannot find the fixedin version of glibc in release `debian:stretch`

**Comment by reasonerjt** [comment]
Closing this issue, please reopen, if there's further questions.
