### ISSUE TITLE
Fail to get v2 manifest: strconv.ParseInt: parsing: "" invalid syntax

### ISSUE THREAD

**Issue by jeffweilee** [goharbor/harbor#7349]
**Expected behavior and actual behavior:**
There is "Internal Error" when browsing detail page (build history tab) on Harbor GUI. Error message is found in the "core" module log: [ERROR] [repository.go:633] Fail to get v2 manifest: strconv.ParseInt: parsing: "" invalid syntax. Thus, no information is shown on the detail page (build history tab). Only "Internal Error" alert is shown on Harbor GUI.  (But image can be push/pull normally)

This problem happened when using S3 as registry. No problem when using NFS.

According to "core" log,
``[transport.go:51] 200 | GET https://xxxx/registry/v2/blobs/sha256/xxxxxx``
``[ERROR] [repository.go:633] Fail to get v2 manifest: strconv.ParseInt: parsing: "" invalid syntax.``

I have checked that manifest json file is well formatted, so the problem should not be storage or network issue. I believe the bug comes from ``repository.go:633`` PullManefiest() pass an empty string to the parser which leads to strconv.ParseInt: parsing: "" invalid syntax when using S3 registry.

**Steps to reproduce the problem:**
Use S3 as registry storage. Push a image to Harbor. Browse detail page and build history tab. "Internal Error" alert on GUI.

**Versions:**
Please specify the versions of following systems.
- harbor version: [1.7.0]
- Registry storage: [S3]

**Comment by gunboe** [comment]
Also here. Same issue with Harbor 1.7.4 and S3 driver.

**Comment by kofj** [comment]
Lgtm, try to reproduce later.

**Comment by kofj** [comment]
@gunb
I can not reproduce this issue with s3 storage. But if there is a illegal image with 0 byte we will get error message like below:
```json
{"errors":[{"code":"MANIFEST_UNKNOWN","message":"manifest unknown","detail":{"Name":"library/alpine","Revision":"sha256:5c40b3c27b9f13c873fefb2139765c56ce97fd50230f1f2d5c91e55dec171907"}}]}
```

**Comment by wohlfrom** [comment]
We had the same issue with Harbor version 1.10.1 and a local S3 backend (&rarr; [NetApp StorageGRID](https://www.netapp.com/us/products/data-management-software/object-storage-grid-sds.aspx)) and were able to resolve it. Problem seems to not exist with other S3 backends, e.g. *Minio* or *AWS*.

*Background*
The exception is thrown in [line 752](https://github.com/goharbor/harbor/blob/v1.7.0/src/core/api/repository.go#L752). This is caused by the missing `Content-Length` in the response header (see [Line 346](https://github.com/goharbor/harbor/blob/v1.7.0/src/common/utils/registry/repository.go#L346)). The preceding request is the [Fetch Blob](https://docs.docker.com/registry/spec/api/#blob) to the image registry which responds with a redirect to the S3 backend. Following the redirect, the response of the S3 backend does not provide the `Content-Length` in the response header which causes the exception. One reason for the missing `Content-Length` is a [chunked response](https://en.wikipedia.org/wiki/Chunked_transfer_encoding), e.g. which happens when the server compresses the content on the fly. This happened in our case because the *Go client* in Harbor offers an `Accept-Encoding` for `gzip` and the S3 server responds with a *chunked response* which then omits the `Content-Length`.

*Workaround*
Between Harbor and S3 backend we put an extra *proxy layer* that removes the `Accept-Encoding` from the request headers. Then the answer from the S3 backend contains again as expected a `Content-Length` information.
Another possible solution on Harbor (not tested) may be to set `DisableCompression` to `True` in the *Go client*, see [http package](https://golang.org/pkg/net/http/).

**Comment by bradfordcp** [comment]
I'm seeing the issue on v1.10.2 with registry.access.redhat.com. You can test with the ubi7/ubi7-minimal:latest image.
