### ISSUE TITLE
Managing signing and signed images.

### ISSUE THREAD

**Issue by smekkley** [goharbor/harbor#7424]
Currently manipulating signing of images is not possible from UI.

It would be nice to be able to manage all the operations that is supported by notary command such as delegation from Web UI.

We could add notary command in the docker image and start creating buttons for key pair generations, signing, unsigning and etc.

**Comment by reasonerjt** [comment]
@smekkley I don't think it's very valid requirement though, as the private key has to be stored offline.

**Comment by DerrickMartinez** [comment]
We need this as well... if it's coming within 6 months or so, we can live without removing any images

**Comment by xaleeks** [comment]
I agree that we shouldn't try to set up expose setting up delegations through Harbor webui because a lot is happening in the backgorund.  DTC is generating a root key and targets key which are stored client side and also snapshots key stored in the notary server and not directly exposed to the internet.  I would strongly urge users to follow the Docker Content Trust workflow on creating delegations.  And there's little value to Harbor to manage this.

**Comment by smekkley** [comment]
I can recommend skopeo signing if you use podman. @DerrickMartinez  
It's very straightforward like signing rpm.

**Comment by emansom** [comment]
Big corporations tend to have individual security teams verifying container images and only signing it once it adheres to internal policy.
The cluster is then configured to only allow signed container images to run.

Harbor implementing a workflow allowing manual or semi-automated signing would make it a worthy competitor to Quay.
