### ISSUE TITLE
Is it possible replicate all projects at once?

### ISSUE THREAD

**Issue by jeffweilee** [goharbor/harbor#7457]
Hello, Is it possible to **replicate all projects** to a remote registry without setting replication rules one by one project? (I have 100+ harbor projects, if there is no **replicate all projects**, then I have to set 100+ replication rules ....) 

Thanks!

**Comment by ctodea** [comment]
You can try using at the REST [API](https://github.com/goharbor/harbor/blob/master/docs/configure_swagger.md), but I've tried it and couldn't make it work as the /api/replication endpoint responds 404, I think the issue is related to other reported (unsolved yet) [issue](https://github.com/goharbor/harbor/issues/7518).

**Comment by ywk253100** [comment]
It's implemented and will be available in 1.8. Closing this issue.
