### ISSUE TITLE
replication error：http error: code 401, message 

### ISSUE THREAD

**Issue by watchmen1992** [goharbor/harbor#7489]
Both pull and push were successful, endpoint was successful, and the test passed, but the replication failed.

Here's an error logs

2019-04-23T03:25:05Z [INFO] initialization completed: repository: apps/test, tags: [v1], source registry: URL-http://core:8080 insecure-false, destination registry: URL-http://dhub-region2.dwbops.com insecure-true
2019-04-23T03:25:07Z [ERROR] [transfer.go:228]: an error occurred while creating project apps on destination registry: http error: code 401, message

**Comment by watchmen1992** [comment]
Server Error logs:

Apr 23 13:33:09 172.20.0.1 core[997]: 2019-04-23T05:33:09Z [ERROR] [security.go:211]: failed to authenticate admin: Failed to authenticate user, due to error 'Invalid credentials'
Apr 23 13:33:09 172.20.0.1 core[997]: 2019-04-23T05:33:09Z [INFO] unauthorized

**Comment by 542928492** [comment]
**the same error ，**  replace job can not continue 

May 22 10:49:28 172.18.0.1 jobservice[1322]:
May 22 10:49:28 172.18.0.1 jobservice[1322]: 2019-05-22T02:49:28Z [INFO] Job incoming: IMAGE_TRANSFER:d3ddcd81eb69c35f1364d5ec
May 22 10:49:28 172.18.0.1 jobservice[1322]: 2019-05-22T02:49:28Z [INFO] Receive event 'register_hook' with data(unformatted): map[string]interface {}{"job_id":"277c215d3e9554908c2f6efe", "hook_url":"http://core:8080/service/notifications/jobs/replication/1946"}
May 22 10:49:28 172.18.0.1 jobservice[1322]: 2019-05-22T02:49:28Z [INFO] initialization completed: repository: middleware/rocketmq-namesrv, tags: [4.2.0], source registry: URL-http://core:8080 insecure-false, destination registry: URL-http://10.22.4.145:8888 insecure-true
May 22 10:49:28 172.18.0.1 jobservice[1322]: 2019-05-22T02:49:28Z [ERROR] [transfer.go:81]: an error occurred while creating project middleware on destination registry: http error: code 401, message
May 22 10:49:28 172.18.0.1 jobservice[1322]: 2019-05-22T02:49:28Z [ERROR] [redis_job_wrapper.go:70]: Job 'IMAGE_TRANSFER:514dab30ce0475f8c9b62469' exit with error: http error: code 401, message

**Comment by SweeXordious** [comment]
Have anyone managed to fix it ? Iam facing the same `401 unauthorized` error with jobservices...

**Comment by ssttgg** [comment]
I too am having a similar issue. Is there an update on this @ywk253100? 

I am running Harbor 1.8.1 with db_auth and using the default credentials and trying to replicate to another harbor node with the same version. 

I have setup push replication from node A to to node B. The endpoint has been configured on node A using node B's IP address rather than hostname. When I test the connection (via the Endpoint modal) with **blank** credentials it says "Connection tested successfully." however the replication task subsequently fails with the following error:

`Jul 24 15:16:27 172.22.0.1 core[32052]: 2019-07-24T14:16:27Z [ERROR] [/replication/operation/controller.go:102]: the execution 41 failed: failed to do the prepare work for pushing/uploading resources: http error: code 401, message {"code":401,"message":"Unauthorized"}`

If I then amend the endpoint configuration to use the default admin credentials (admin/Harbor12345) then the Test Connection function on the endpoint configuration does not succeed. core.log is as follows:

`Jul 24 15:24:13 172.22.0.1 core[32052]: 2019-07-24T14:24:13Z [ERROR] [/replication/adapter/image_registry.go:145]: failed to ping registry http://10.34.2.239: http error: code 401, message
Jul 24 15:24:13 172.22.0.1 core[32052]: 2019-07-24T14:24:13Z [ERROR] [/common/api/base.go:69]: POST /api/registries/ping failed with error: {"code":400,"message":""}`

My `harbor.yml` is pretty my default, except for the hostname and the use of `external_url`.

Thanks - happy to provide more details, or split into a separate issue, if required.

**Comment by SweeXordious** [comment]
> I too am having a similar issue. Is there an update on this @ywk253100?
> 
> I am running Harbor 1.8.1 with db_auth and using the default credentials and trying to replicate to another harbor node with the same version.
> 
> I have setup push replication from node A to to node B. The endpoint has been configured on node A using node B's IP address rather than hostname. When I test the connection (via the Endpoint modal) with **blank** credentials it says "Connection tested successfully." however the replication task subsequently fails with the following error:
> 
> `Jul 24 15:16:27 172.22.0.1 core[32052]: 2019-07-24T14:16:27Z [ERROR] [/replication/operation/controller.go:102]: the execution 41 failed: failed to do the prepare work for pushing/uploading resources: http error: code 401, message {"code":401,"message":"Unauthorized"}`
> 
> If I then amend the endpoint configuration to use the default admin credentials (admin/Harbor12345) then the Test Connection function on the endpoint configuration does not succeed. core.log is as follows:
> 
> `Jul 24 15:24:13 172.22.0.1 core[32052]: 2019-07-24T14:24:13Z [ERROR] [/replication/adapter/image_registry.go:145]: failed to ping registry http://10.34.2.239: http error: code 401, message Jul 24 15:24:13 172.22.0.1 core[32052]: 2019-07-24T14:24:13Z [ERROR] [/common/api/base.go:69]: POST /api/registries/ping failed with error: {"code":400,"message":""}`
> 
> My `harbor.yml` is very close to the default, except for the hostname and the use of `external_url`.
> 
> Thanks - happy to provide more details, or split into a separate issue, if required.

I guess its pretty much the same issue as this i guess https://github.com/goharbor/harbor/issues/8355 ... im still trying his suggestion tho

**Comment by ywk253100** [comment]
@watchmen1992 @542928492 Did you input the credential when creating the registry endpoint? As the pushing operation only valid for authorized users, you must provide the credential.

@ssttgg Did you change the `external_url` for the destination Harbor, is there a proxy before the destination Harbor? And does it serve with HTTP or HTTPS? If it is HTTPS and with a self-signed certificate, you must uncheck the `Verify Remote Cert` when creating the registry endpoint?

**Comment by ywk253100** [comment]
@ssttgg And can you show me the logs of `registry` of the destination Harbor when you trying to test the connection?

**Comment by ssttgg** [comment]
Thank you very much for the reply! 

> Did you change the external_url for the destination Harbor

Yes. Both source and destination have the same external_url (e.g. harbor.company.org.uk) as we will _eventually_ be running node B as a passive failover node.

> is there a proxy before the destination Harbor? 

No.

> does it serve with HTTP or HTTPS? 

Just HTTP. I have tried with the box ticked and unticked.

Logs from destination registry.log:

`
Jul 23 15:24:11 192.168.96.1 registry[7140]: 192.168.96.7 - - [23/Jul/2019:14:24:11 +0000] "GET /v2 HTTP/1.1" 301 39 "" "Go-http-client/1.1"
Jul 23 15:24:11 192.168.96.1 registry[7140]: time="2019-07-23T14:24:11.463852714Z" level=info msg="response completed" go.version=go1.11.8 http.request.host="registry:5000" http.request.id=34501f11-b868-4b3e-94b4-8fa6545246cf http.request.method=GET http.request.remoteaddr="192.168.96.7:34906" http.request.uri="/v2" http.request.useragent="Go-http-client/1.1" http.response.contenttype="text/html; charset=utf-8" http.response.duration="57.281µs" http.response.status=301 http.response.written=39
Jul 23 15:24:11 192.168.96.1 registry[7140]: 192.168.96.7 - - [23/Jul/2019:14:24:11 +0000] "GET /v2/ HTTP/1.1" 401 87 "http://registry:5000/v2" "Go-http-client/1.1"
Jul 23 15:24:11 192.168.96.1 registry[7140]: time="2019-07-23T14:24:11.467128708Z" level=warning msg="error authorizing context: authorization token required" go.version=go1.11.8 http.request.host="registry:5000" http.request.id=95d13f65-28d8-4130-b493-8ceb56e1437e http.request.method=GET http.request.referer="http://registry:5000/v2" http.request.remoteaddr="192.168.96.7:34906" http.request.uri="/v2/" http.request.useragent="Go-http-client/1.1"
`

**Comment by ssttgg** [comment]
I also tried to setup pull replication from B -> A. This got further in that it seeded individual tasks for every image however these all still failed to replicate. Here is an example error message:

```
2019-07-25T13:28:41Z [INFO] [/replication/transfer/image/transfer.go:95]: client for source registry [type: harbor, URL: http://10.194.2.236, insecure: true] created
2019-07-25T13:28:41Z [INFO] [/replication/transfer/image/transfer.go:105]: client for destination registry [type: harbor, URL: http://core:8080, insecure: true] created
2019-07-25T13:28:41Z [INFO] [/replication/transfer/image/transfer.go:138]: copying systems/test:[latest](source registry) to systems/test:[latest](destination registry)...
2019-07-25T13:28:41Z [INFO] [/replication/transfer/image/transfer.go:157]: copying systems/test:latest(source registry) to systems/test:latest(destination registry)...
2019-07-25T13:28:41Z [INFO] [/replication/transfer/image/transfer.go:261]: pulling the manifest of image systems/test:latest ...
2019-07-25T13:28:41Z [ERROR] [/replication/transfer/image/transfer.go:268]: failed to pull the manifest of image systems/test:latest: http error: code 401, message {"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":[{"Type":"repository","Class":"","Name":"systems/test","Action":"pull"}]}]}
2019-07-25T13:28:41Z [ERROR] [/replication/transfer/image/transfer.go:143]: http error: code 401, message {"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":[{"Type":"repository","Class":"","Name":"systems/test","Action":"pull"}]}]}
```

**Comment by ywk253100** [comment]
Cannot reproduce the issue. Make sure you are using the correct credential to creating the replication rule, you can verify it by running docker pull/push the images with the credential

**Comment by YakirShriker** [comment]
I got the same problem, After changing the Admin password on all Harbors and updating the registries.
Once in a while I got replication failed due to 401 unauthorized, it happens randomly and could not understand what exactly the issue.
![image](https://user-images.githubusercontent.com/38837459/64953010-71edb100-d88a-11e9-927f-f4696d1a889e.png)

![image](https://user-images.githubusercontent.com/38837459/64953066-921d7000-d88a-11e9-84d5-f01339f5f05d.png)

**Comment by timchenxiaoyu** [comment]
2019-09-23T03:20:37Z [WARNING] the status code is 409 when creating project abdnlp on destination registry, try to do next step
2019-09-23T03:20:37Z [ERROR] [job_logger.go:81]: an error occurred while pulling manifest of abdnlp/cu:20190917113705749991602 from source registry: 401 {"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":[{"Type":"repository","Class":"","Name":"abdnlp/cu","Action":"pull"}]}]}

**Comment by 13567436138** [comment]
how to solve this problem

**Comment by leo1971** [comment]
I too have this problem when I tried to set a remote repo.

Here is the log from `core.log`:

```
Nov  1 15:25:12 172.24.0.1 core[6356]: 2019-11-01T07:25:12Z [ERROR] [/common/api/base.go:68]: POST /api/registries/ping failed with error: {"code":401,"message":"UnAuthorized"}
```

**Comment by leo1971** [comment]
> I too have this problem when I tried to set a remote repo.
> 
> Here is the log from `core.log`:
> 
> ```
> Nov  1 15:25:12 172.24.0.1 core[6356]: 2019-11-01T07:25:12Z [ERROR] [/common/api/base.go:68]: POST /api/registries/ping failed with error: {"code":401,"message":"UnAuthorized"}
> ```

I have solved this problem, it is caused by DNS resolving, after I add a nameserver into `/etc/resolv.conf`, it works.

**Comment by ynntg** [comment]
me too ,in push-based  scheduled replication mode ,harbor version is 1.8.2 . cpu 2 mem 4 .
I use url=ip && extra_hosts for replications.
It happens randomly ,when twelve replications and fail two times.
I also found replication  log time is not right ; f.g. scheduled  2019/11/12 下午5:00 ,but  log :2019-11-12T09:00:24Z [INFO] [/replication/transfer/image/transfer.go:95]
jobservice.log has two time: Nov 12 17:30:40 IP jobservice[19273]: 2019-11-12T09:30:40Z [INFO] [/replication/transfer/image/transfer.go:142]

more errors :
2019-11-12T07:30:48Z [ERROR] [/replication/transfer/image/transfer.go:269]: failed to pull the manifest of image project:v1.0: http error: code 401, message {"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":[{"Type":"repository","Class":"","Name":"project","Action":"pull"}]}]}
2019-11-12T07:30:48Z [ERROR] [/replication/transfer/image/transfer.go:143]: http error: code 401, message {"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":[{"Type":"repository","Class":"","Name":"project","Action":"pull"}]}]}

Nov 12 15:30:50 10.48.255.193 jobservice[19273]: 2019-11-12T07:30:50Z [ERROR] [/jobservice/runner/redis.go:63]: |@_@| Job 'REPLICATION:89420c76f527e6201
d896462' exit with error: http error: code 401, message {"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":[{"Type":"repository","Class":""
,"Name":"project","Action":"pull"}]}]}

sometimes: the error is 
2019-11-12T03:00:33Z [ERROR] [/replication/transfer/image/transfer.go:269]: failed to pull the manifest of image project:v1.0: http error: code 502, message 
2019-11-12T03:00:33Z [ERROR] [/replication/transfer/image/transfer.go:143]: http error: code 502, message

**Comment by DesistDaydream** [comment]
I have the same error。
Here is a solution：https://github.com/goharbor/harbor/issues/7784#issue-443336263
Here is a solution, but is there any other better solution? such as modifying harbor.yml or something else?

**Comment by fredgate** [comment]
I have similar issue trying to replicate to an Azure Container Registry in Harbor 2.0.0.
I tried several settings in the dialog to add a registry :
- **https**://contoso.azurecr.io with valid credentials : ping fail :-\
- **https**://contoso.azurecr.io without credentials : ping is fine :-\
- **http**://contoso.azurecr.io with valid credentials : ping is fine. A replication succeeds. But the images are not present on the ACR !
- **http**://contoso.azurecr.io with invalid credentials : ping is fine :-\
- **http**://contoso.azurecr.io without credentials : ping is fine :-\

The first scenario, and only the first, should succeed. But it is not the case. All scenarios are incoherent.  
I have the problem with an ACR. I also tested authentication with Docker hub and a private docker registry, and this is ok.

**Comment by homer6** [comment]
I get this error, but when I scale down the pods to 1 replica (they should be 1 to start with) and kill the other pods, it starts working again. This happens across multiple deployments in k8s. They should all be 1/1 in the deployment list. Having 1/2 show up means that I can count on this error showing up too. I'm suspecting it has something to do with a race condition for restarting the pod, where old pod doesn't shut down until the new one comes up, but the new one failed to start due to a volume mount conflict (it's already mounted by the old pod).

**Comment by astzyj** [comment]
I got the same error, but the way I resolve it is creating the namespace(project) and repo manually in the remote endpoint.
May this help someone in the same scenario.

**Comment by AndreaTosti** [comment]
I had a similar problem and thanks to @astzyj , I got closer to the solution.

Here's how I reproduced the problem and what the solution is.

Context: Two Harbor v2.14.0 instances that we will call `Test` and `Prod`.

`Test` contains a project with several repositories.

`Prod` contains a project with **zero** repositories (the problem does not arise when the project has **at least one** repository).

I create a Replication Rule from Harbor `Test` to Harbor `Prod`. The user account used to perform the copy is a **Project Robot Account** (with ALL possible permissions).

The replication returns an error similar to the following:

```
5-11-20T09:27:04Z [INFO] [/controller/replication/transfer/image/transfer.go:290]: copying the blob sha256:191d382795e1e37405b0675884d038402f42e937b00ee4381eadc9a027b46cd5(the 1th running)...
2025-11-20T09:27:04Z [ERROR] [/controller/replication/transfer/image/transfer.go:352]: failed to mount the blob sha256:191d382795e1e37405b0675884d038402f42e937b00ee4381eadc9a027b46cd5 on the destination registry: http status code: 401, body: {"errors":[{"code":"UNAUTHORIZED","message":"unauthorized to access repository: my-project/my-repository, action: push: unauthorized to access repository: my-project/my-repository, action: push"}]}
```

How to resolve:

Use a **System Robot Account** instead of a **Project Robot Account**.

In my case, the System Robot Account has zero permissions in `System permissions` and has the same permissions as the Project Robot Account had in `Project permissions`.
