### ISSUE TITLE
Is there a documentation for auth_mode

### ISSUE THREAD

**Issue by sergeyfd** [goharbor/harbor#7711]
Is auth_mode documented anywhere in details? So for I see db_mode and ldap_mode. From the code I can guess that there's also oidc_mode and uaa_mode. Are they documented anywhere? Is it possible to configure Harbor to use Gitlab as a authn and authz provider?

**Comment by reasonerjt** [comment]
Hi,
 
The `uaa_auth` is not documented because it was for integration with product, so we don't suggest oss user to use it.
As for `oidc_auth`,  the doc is WIP.

In regards to integration with Gitlab, we haven't tested it, if Gitlab can work as an OIDC provider it may work, or you may configure Harbor and Gitlab with mutual authn backends, such as LDAP or OIDC provider.

**Comment by reasonerjt** [comment]
Closing this one, please ask me to reopen if you have further questions.
