### ISSUE TITLE
webhook 2.0 (Workflow hooks)

### ISSUE THREAD

**Issue by michmike** [goharbor/harbor#8019]
Add support for hooks for certain actions that can be plugged into a workflow for approval
1. Pulling an image
2. Creating a new user
3. Pushing a new image
etc

**Comment by kacole2** [comment]
- Individual notification/webhooks and not "all or none"

**Comment by xaleeks** [comment]
Webhooks for 1.10 updated
https://docs.google.com/document/d/1wSzQvSezKELiLyMj1wZoNk19AwEtfRGb3k3zKE9Gycw/edit

**Comment by xaleeks** [comment]
new webhooks being added for 1.10 include
--
1. replicating image / helm chart
2. replicating failed due to immutability configured
3. delete image failed due to immutability configured
4. tag retention event
5. tag immutability event
5. image / chart push failed due to project quotas exceeded

detailed PRD here: https://docs.google.com/document/d/1wSzQvSezKELiLyMj1wZoNk19AwEtfRGb3k3zKE9Gycw/edit

**Comment by michmike** [comment]
once 1.10 is over, we should lose this issue and create a new one for specific and future webhooks. thanks Alex!

**Comment by xaleeks** [comment]
got it @michmike

**Comment by xaleeks** [comment]
These have been added, closing ticket.  creating a new one for 2.0 webhooks
