### ISSUE TITLE
More explicit expiration notice of robot account.

### ISSUE THREAD

**Issue by Thoro** [goharbor/harbor#8282]
I am using robot accounts for our CI System. Today the CI system couldn't push docker images anymore.

After investigation the logs, I saw:

Jul 11 10:30:43 172.18.0.1 core[24785]: 2019-07-11T10:30:43Z [ERROR] [/common/token/htoken.go:76]: parse token error, token is expired by 309h12m44s
Jul 11 10:30:43 172.18.0.1 core[24785]: 2019-07-11T10:30:43Z [ERROR] [/core/filter/security.go:200]: failed to decrypt robot token, token is expired by 309h12m44s

**Expected behavior and actual behavior:**
There is no option in the UI:
- to regenerate the token
- it's not displayed that the token is expired
- it's not even displayed when you create a new token, that it will expire

In my opinion either the tokens should not run out (since they are only visible once anyways), or there should be an option to set the expiry date (#7919) and the option to regenerate the token in the UI.

**Steps to reproduce the problem:**
Let a robot account token run out.

**Versions:**
Please specify the versions of following systems.
- harbor version: 1.8.1
- docker engine version: 19.03

**Comment by wy65701436** [comment]
In UI, there is a column to index the expiration date of a robot account.

**Comment by Thoro** [comment]
True, sorry, but it's not clear if it's expired or not (looks exactly the same) - a  notice "expired" would be better

**Comment by xaleeks** [comment]
I think some type of alerts should be fired when nearing expiration.  let's discuss @wy65701436

**Comment by xaleeks** [comment]
Does it take the same amount of effort to resubmit a refreshed token to a k8s pullsecret as it does to consume a new robot.  Although I understand the idea behind reusing a new token instead of retiring a robot for a new one altogether, seems you have to do the same amount of work to reboot the robot in your CI no?  @Thoro

**Comment by Thoro** [comment]
Yes, that one doesn't matter, so a notification wouldn't actually help.

My comment was just about having an additional hint in the UI (i.e. red color, just writing expired instead of the date (+hover for actual date)), so that if it happens, it's clear that it happened.

**Comment by xaleeks** [comment]
this can be added @Thoro

**Comment by xaleeks** [comment]
You can now regenerate the token on each robot account during creation, please see https://github.com/goharbor/harbor/issues/8405

_'having an additional hint in the UI (i.e. red color, just writing expired instead of the date (+hover for actual date)), so that if it happens, it's clear that it happened'_

This will be tackled in the following release 2.1

**Comment by xaleeks** [comment]
can you think about how to make this expiration more prominent on UI? @lweitzman  @AllForNothing
