### ISSUE TITLE
Concurrent transfer when doing replication

### ISSUE THREAD

**Issue by mmpei** [goharbor/harbor#8455]
One work thread per job will make the transferring slow. The write rate of backend is low, but it can write concurrently. and also there are three threads for transferring when pushing image by docker client. 
we should add some mechanism to transfer blobs concurrently and make the execution of job faster.

**Comment by mmpei** [comment]
it is meaningful, it will reduce the time of transfering blobs sharply when there is just one heavy job.

**Comment by ChristianCiach** [comment]
This issue is valid. With the default value of 10 workers, a single replication job completely overloaded our registry server. There is no need to have 10 concurrent workers when the HDD is the real bottleneck. Our registry server has 4 CPU cores, but the 10 concurrent workers make our server completely unresponsive (CPU load average of 60 (!) because of the HDD bottleneck). We had to hard-reset our server to make it responsible again.

Whenever the storage is the bottleneck (which is most often the case), concurrent jobs make things slower, not faster.
