### ISSUE TITLE
仓库gc时，是否只读设为可选项，而不是必须只读

### ISSUE THREAD

**Issue by heidsoft** [goharbor/harbor#8482]
### 场景
因为镜像较多情况下，开发者删除较多镜像后，执行gc时，无法push镜像，或者pull镜像。导致进行正常的ci/cd操作。

**Comment by wy65701436** [comment]
this is as designed, we cannot guarantee that the RW conflict when to execute GC. So, read-only is required. 

If you'd like to disable read-only during GC, I think you can edit in the configuration page manually or by API.

**Comment by reasonerjt** [comment]
I suggest a won't fix
@xaleeks please triage.

**Comment by xaleeks** [comment]
@heidsoft This is by design to guarantee rw consistency.  GC is a heavy operation so it should be setup to run periodically as to not affect operational SLA.  Can you share some data on your side in terms of # or frequency of pushes and running time incurred from running GC?  Replying in Chinese is totally fine.

**Comment by heidsoft** [comment]
@xaleeks thanks

**Comment by Ghostbaby** [comment]
两套单独harbor使用replication进行同步镜像，使用nginx或者kong做反向代理，gc期间将请求转发到非维护节点。

**Comment by xaleeks** [comment]
@heidsoft  we are tackling this issue in upcoming release, please follow https://github.com/goharbor/harbor/issues/10167.  Closing this.
