### ISSUE TITLE
helm harbor 1.8.1 api Find the error

### ISSUE THREAD

**Issue by icoolchn** [goharbor/harbor#8896]
Harbor helm version 1.8.1 deploy，registry storage using the s3 object storage interface ,Find the API usage errors. Please help us, thank you
api 
 curl -X GET "http://test.com/api/search?q=redis" -H "accept: application/json"  {"code":500,"message":"Internal Server Error"}

harbor helm value.yaml
    s3:
      region: xxxxxxxxx
      bucket: xxxxxxxxx
      accesskey: xxxxxxxxx
      secretkey: xxxxxxxxx
      regionendpoint: http://xxxxxxxxx
      #encrypt: false
      #keyid: mykeyid
      #secure: true
      #v4auth: true
      #chunksize: "5242880"
      rootdirectory: /xxxxxxxxx/
      #storageclass: STANDARD

core.log日志如下
2019-08-29T10:49:23Z [ERROR] [/core/api/search.go:142]: failed to filter charts: http error: code 404, message not found
2019-08-29T10:49:23Z [ERROR] [/common/api/base.go:229]: http error: code 404, message not found
2019-08-29T10:49:23Z [ERROR] [/common/api/base.go:69]: GET /api/search?q=redis failed with error: {"code":500,"message":"Internal Server Error"}
2019/08/29 10:49:23 [D] [server.go:2619] |   10.207.170.7| 500 | 2.037835317s|   match| GET      /api/search   r:/api/search
2019/08/29 10:49:24 [D] [server.go:2619] |  10.207.170.11| 200 |   1.088475ms|   match| GET      /api/ping   r:/api/ping
2019-08-29T10:49:25Z [ERROR] [/core/proxy/interceptors.go:220]: Decode repositories error: EOF
2019/08/29 10:49:25 [D] [server.go:2619] |  10.207.176.24| 200 |24.379025673s|   match| GET      /v2/_catalog   r:/v2/*

Before the Replication failed problems，https://github.com/goharbor/harbor/issues/8281 Refer to the modified information database table，Not sure if the problem cause
ALTER TABLE replication_task ALTER COLUMN src_resource TYPE character varying(512);
ALTER TABLE replication_task ALTER COLUMN dst_resource TYPE character varying(512);

**Comment by fivezerosix** [comment]
We have seen this error but in the 1.8.0 version and using the Helm Chart. Through the UI we get a message saying that internal server errors have occurred when searching for `api` after creating a project starting with `api` in the name. Anything matching that project will get us the same result. The chrome console returns a 500 error and bunch of weird characters. and the core logs:

```
2019-09-06T21:18:15Z [ERROR] [/core/api/project.go:440]: Failed to get total of charts under project api : http error: code 404, message not found
9/6/2019 3:18:15 PM 2019-09-06T21:18:15Z [ERROR] [/common/api/base.go:229]:
9/6/2019 3:18:15 PM 2019-09-06T21:18:15Z [ERROR] [/common/api/base.go:69]: GET /api/projects?page=1&page_size=15&name=api failed with error: {"code":500,"message":"Internal Server Error"}
9/6/2019 3:18:15 PM 2019/09/06 21:18:15 [D] [server.go:2619] | 10.3.58.228| 500 | 115.069656ms| match| GET /api/projects r:/api/projects/   
```
We are still investigating what the root cause is. Our fix was to log in to the Core DB and find the project ID of the project causing the issue.
Then we would send the DELETE api request for that id. We saw this same behavior in 3 different Harbor instances all occurring after adding the `api...` project.

Hope this helps and hopefully someone can take look.
