### ISSUE TITLE
Implement the adapter service for Clair

### ISSUE THREAD

**Issue by steven-zou** [goharbor/harbor#8984]

**Comment by reasonerjt** [comment]
We need to make sure the code of the adapter is in the harbor repo, and must be tested in Harbor's automation pipeline before release.  So that we can still build Clair in the pkg, and ship Clair as the default scanner

During migration it should still use the internal DB of Harbor, while scanning the scanner of Clair may use the external network to pull image from Harbor.

**Comment by danielpacak** [comment]
@reasonerjt @steven-zou I'm happy to transfer the ownership of the POC code from https://github.com/danielpacak/harbor-scanner-clair to the https://github.com/goharbor/namespace straight away.

I was thinking that the harbor-scanner-clair can be deployed as a sidecar container in the existing harbor-scanner-clair deployment, but we can discuss it what's the best approach.

I was also wondering if you or someone from the community would like to participate in peer review of pull requests turning the above mentioned POC to production ready code? Otherwise we'll coordinate it with my team @aquasecurity.

**Comment by steven-zou** [comment]
> @reasonerjt @steven-zou I'm happy to transfer the ownership of the POC code from https://github.com/danielpacak/harbor-scanner-clair to the https://github.com/goharbor namespace straight away.
> 
> I was thinking that the harbor-scanner-clair can be deployed as a sidecar container in the existing harbor-scanner-clair deployment, but we can discuss it what's the best approach.
> 
> I was also wondering if you or someone from the community would like to participate in peer review of pull requests turning the above mentioned POC to production ready code? Otherwise I'll coordinate it with my team @aquasecurity.

Please add me in the reviewer list, thanks!

**Comment by steven-zou** [comment]
Mark the sprint of this issue to SP71.

**Comment by steven-zou** [comment]
Clair adapter repo has already been imported: https://github.com/goharbor/harbor-scanner-clair
