### ISSUE TITLE
Recursively delete images when a project is deleted

### ISSUE THREAD

**Issue by IAmATeaPot418** [goharbor/harbor#9164]
I tried to delete a project with one image within the project and this fails until I remove all images within the project. I'm not 100% if this is a design choice or not but I figured I'd open the issue just in case.

 It looks like you do not have the choice to delete a project and then recursively delete all the images within that project. It would make more intuitive sense from a UI perspective to at least warn a user that it would also delete underlying images rather than hard failing. 

Thoughts?

**Comment by xaleeks** [comment]
This is indeed by design so it doesn't over delete as delete is a dangerous operation that you can't easily recover from.  Consider using the newly released tag retention feature in 1.9 for bulk deletion first, ie use ** to match all tags in the repo for fast deletion.  Or you can do this by writing a script since we expose the APIs.  Let me know if you still have trouble.   @IAmATeaPot418

**Comment by IAmATeaPot418** [comment]
Nope that works for me!
