### ISSUE TITLE
harbor upgrade from 1.8.1 to 1.9.0 

### ISSUE THREAD

**Issue by dbenduga** [goharbor/harbor#9290]
Could you please explain how to use below command for 1.8.1. to 1.9.0 upgrade.

docker run -it --rm -v ${harbor_yml}:/harbor-migration/harbor-cfg/harbor.yml goharbor/harbor-migrator:[tag] --cfg up

**Comment by dbenduga** [comment]
As we know in harbor 1.8.1 harbor configuration file is harbor.yml
My question is why we are running command " docker run -it --rm -v ${harbor_yml}:/harbor-migration/harbor-cfg/harbor.yml goharbor/harbor-migrator:[tag] --cfg up"

**Comment by mohamed-ouakil** [comment]
Hi, i have the same question but because the upgrade didn't work for me

<<
[root@harbor01-v harbor]# docker run -it --rm -v ${harbor_yml}:/harbor-migration/harbor-cfg/harbor.yml goharbor/harbor-migrator:v1.9.0 --cfg up
WARNING: IPv4 forwarding is disabled. Networking will not work.
Please backup before upgrade, 
Enter y to continue updating or n to abort: y
Skip cfg up as no harbor.cfg in the path.
>>

i've tried to remove the --cfg, but i got a message i don't understand 

<<
[root@harbor01-v harbor]# docker run -it --rm -v ${harbor_yml}:/harbor-migration/harbor-cfg/harbor.yml goharbor/harbor-migrator:v1.9.0  up
WARNING: IPv4 forwarding is disabled. Networking will not work.
Please backup before upgrade, 
Enter y to continue updating or n to abort: y
No database has been mounted for the migration. Use '-v' to set it in 'docker run'.
>>

what is this path /harbor-migration/harbor-cfg/harbor.yml  ? 
i also tried to replace this path with the real path where is located  harbor.yaml but i get the same message "no database has been mounted for the migration..."

thanks for your help

regards

**Comment by rajendravishwa** [comment]
Yes. there is no proper explanation for the command or the guidelines. Can someone explain the command.
It says to run docker image load -i harbor/harbor.[version].tar.gz command but there is no .tar.gz file. where do we get that file from?
Plus the command,
docker run -it --rm -v ${harbor_yml}:/root/Harbor/harbor.yml goharbor/harbor-migrator:v1.10.1 --cfg up.
I get the same error. 
Skip cfg up as no harbor.cfg in the path. 
What are these paths. All the files are there in the required folder. Why doesn't it work?

**Comment by prasad15** [comment]
${harbor_yml} is SHELL variable. So we have to run the command substituting the variable. I had to upgrade from 1.7.3 version, so had to use two config files harbor.cfg and harbor.yml. Upgrade documentation had this command:

`docker run -it --rm -v ${harbor_cfg}:/harbor-migration/harbor-cfg/harbor.yml -v ${harbor_yml}:/harbor-migration/harbor-cfg-out/harbor.yml goharbor/harbor-migrator:[tag] --cfg up
`
And my command was like this :

`$sudo docker run -it --rm -v /home/prasad/harbor/harbor/harbor.cfg:/harbor-migration/harbor-cfg/harbor.yml -v /home/prasad/harbor/harbor/harbor.yml:/harbor-migration/harbor-cfg-out/harbor.yml goharbor/harbor-migrator:v1.10.1 --cfg up
Please backup before upgrade,
Enter y to continue updating or n to abort: y
Command for config file migration: python ./cfg/run.py --input /harbor-migration/harbor-cfg/harbor.yml --output /harbor-migration/harbor-cfg-out/harbor.yml
input version: 1.7.0, migrator chain: ['1.8.0', '1.9.0', '1.10.0']
migrating to version 1.8.0
migrating to version 1.9.0
migrating to version 1.10.0
Written new values to /harbor-migration/harbor-cfg-out/harbor.yml`
