### ISSUE TITLE
Additional tag retention rules

### ISSUE THREAD

**Issue by eroji** [goharbor/harbor#9350]
The current tag retention rules restrict to settings based on recently pushed/pull images or retain always. There should be a rule to allow retention based on creation time of the image such that you can retain the last X number of created images. Or perhaps the last X versions, although that may be very difficult to implement as you will need some means to filter out the version number in the tag and not all image tags follow some form of semver standard.

**Comment by steven-zou** [comment]
@xaleeks 

What's your opinions?

**Comment by xaleeks** [comment]
By version number is definitely not supported as this is hard to define and then parse.  By creation time is more reasonable, we will look into this. @eroji

**Comment by xaleeks** [comment]
We will not be adding tag retention by creation time any time soon because CIs usually push these to registry as soon as they are created, rendering the same outcome as ordering by push time.  Kind of low priority for us but feel free to submit a PR for it if you really need it.  Closing it until then
