### ISSUE TITLE
By default Harbor should serve https

### ISSUE THREAD

**Issue by reasonerjt** [goharbor/harbor#9525]
Involve update to `harbor.yml`

Fix CI

Make sure `prepare` generate a friendly error message if cert does not exist.

**Comment by michmike** [comment]
@stuclem in our docs we should explain to folks why we did this change (for security by default reasons) and to also guide them how to get free certs using lets encrypt

**Comment by stuclem** [comment]
@michmike I already have this in progress in https://github.com/goharbor/harbor/pull/9508. The current doc describes how to get certs from Open SSL. https://github.com/goharbor/harbor/blob/master/docs/configure_https.md

So, we need to add instructions for https://letsencrypt.org/ too? Instead of Open SSL, or as well as? I imagine as well as, but just checking.

**Comment by michmike** [comment]
@stuclem that's great we have openssl. in that case you may as well just reference that users could also use https://letsencrypt.org/ if they wanted to, without adding any of the steps or details you had for openssl

**Comment by ninjadq** [comment]
done in #9550
