### ISSUE TITLE
Meet errors of faling to do authentication with robot account generated for scan

### ISSUE THREAD

**Issue by steven-zou** [goharbor/harbor#9628]
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**

In the log files, found some errors say failing to do authentication with robot account `$robot_uuid`, actually there should NOT be any errors

**Steps to reproduce the problem:**

Not confirmed

**Versions:**
Please specify the versions of the following systems.

- harbor version: [1.10.0]
- docker engine version: [y.y.y]
- docker-compose version: [z.z.z]

**Additional context:**

> Oct 28 14:06:18 192.168.112.1 core[1185]: 2019-10-28T14:06:18Z [ERROR] [/core/service/token/token.go:40]: Unable to handle service: 
Oct 28 14:06:18 192.168.112.1 core[1185]: 2019-10-28T14:06:18Z [ERROR] [/pkg/token/token.go:66]: parse token error, token is expired by 460h28m36s
Oct 28 14:06:18 192.168.112.1 core[1185]: 2019-10-28T14:06:18Z [ERROR] [/core/filter/security.go:196]: failed to decrypt robot token, token is expired by 460h28m36s
Oct 28 14:06:20 192.168.112.1 core[1185]: 2019-10-28T14:06:20Z [ERROR] [/core/filter/security.go:431]: failed to authenticate robot$4004fd50-ea74-11e9-a182-0242c0a85008: Failed to authenticate user, due to error 'Invalid credentials'

**Comment by steven-zou** [comment]
After clear the old env, now see the new errors:

> Oct 29 01:06:36 192.168.176.1 core[1185]: 2019-10-29T01:06:36Z [ERROR] [/core/service/token/token.go:40]: Unable to handle service: 
Oct 29 01:06:36 192.168.176.1 core[1185]: 2019-10-29T01:06:36Z [ERROR] [/pkg/token/token.go:66]: parse token error, crypto/rsa: verification error
Oct 29 01:06:36 192.168.176.1 core[1185]: 2019-10-29T01:06:36Z [ERROR] [/core/filter/security.go:196]: failed to decrypt robot token, crypto/rsa: verification error
Oct 29 01:06:37 192.168.176.1 core[1185]: 2019-10-29T01:06:37Z [ERROR] [/core/filter/security.go:431]: failed to authenticate robot$4004fd50-ea74-11e9-a182-0242c0a85008: Failed to authenticate user, due to

**Comment by steven-zou** [comment]
Confirmed. The requests with the malformed robot accounts are sent from Anchore engine which has been installed for a long while. They used the outdated malformed robot account to do the async work.

A fresh installation will not have such errors.

No actions need to be taken. Close this issue now.

**Comment by catchAsh** [comment]
Hello together,
I am still facing the similar issue as mentioned above.

**Versions:**
Harbor version [v1.9.0 ]
Docker Engine version [v18.09.7]
Docker-Compose version [1.23.1]

core.log 

Nov 15 19:32:37 192.168.192.1 core[2035]: 2019/11/15 11:32:37 #033[1;44m[D] [server.go:2774] |      127.0.0.1|#033[42m 200 #033[0m|   1.371031ms|   match|#033[44m GET     #033[0m /api/ping   r:/api/ping#033[0m
Nov 15 19:33:07 192.168.192.1 core[2035]: 2019/11/15 11:33:07 #033[1;44m[D] [server.go:2774] |      127.0.0.1|#033[42m 200 #033[0m|   1.204183ms|   match|#033[44m GET     #033[0m /api/ping   r:/api/ping#033[0m
Nov 15 19:33:32 192.168.192.1 core[2035]: 2019/11/15 11:33:32 #033[1;44m[D] [server.go:2774] |   53.99.105.23|#033[43m 401 #033[0m|   3.353569ms|   match|#033[44m GET     #033[0m /v2/   r:/v2/*#033[0m
Nov 15 19:33:33 192.168.192.1 core[2035]: 2019-11-15T11:33:33Z [ERROR] [/core/filter/security.go:422]: failed to authenticate robot: Failed to authenticate user, due to error 'Invalid credentials'
Nov 15 19:33:37 192.168.192.1 core[2035]: 2019/11/15 11:33:37 #033[1;44m[D] [server.go:2774] |      127.0.0.1|#033[42m 200 #033[0m|   2.747406ms|   match|#033[44m GET     #033[0m /api/ping   r:/api/ping#033[0m

**and i also get this error on my command prompt**:
Error response from daemon: Get https://****************/v2/: unauthorized: authentication required


Is there is specific format in which we need to enter the robot token credentials while performing docker login, cause i tried pretty much all but no luck :( 

Please help me. Thanks in advance!
