### ISSUE TITLE
User permission is not honored if user logins before member role is assigned via group

### ISSUE THREAD

**Issue by ericvmw** [goharbor/harbor#9749]
**Expected behavior and actual behavior:**
http_auth is configured on the Harbor server. User logins first, then project is created, and user is added as a member to the project

expected: user should be able to see the project by refreshing UI or call APIs

actual: project doesn't show on UI, API call returns forbidden with error:
Error: ForbiddenResponse bodyDownload{"code":403,"message":"administrator@vsphere.local"}

**Steps to reproduce the problem:**
1. user A logins first
2. create project, and add user A as master role to the project
3. refresh UI, project doesn't show even after several minutes
4. call REST API to get the project, it gets response:
Error: ForbiddenResponse bodyDownload{"code":403,"message":"administrator@vsphere.local"}

If user logout and login again, the project will show up.

**Versions:**
Please specify the versions of following systems.
- harbor version: 1.9.1

**Comment by reasonerjt** [comment]
I don't reproduce this problem via either UI or API.

Perhaps it's a dup of #9466 ?  That you used different case of username?

**Comment by reasonerjt** [comment]
This is a valid issue, actually when adding member to project the group was used, not username.

This is a general issue in Harbor, that when user login and security context get generated, it tries to query the group ID from Harbor DB and at that point of time, any groups that are not added to Harbor's DB will be dropped.  

I think we should seek a more general fix to this problem.  Perhaps at that step we should **populate** the group IDs rather than query. 

@stonezdj thoughts?
