### ISSUE TITLE
Return the relative URL as token realm to avoid configuring hostname/externalURL

### ISSUE THREAD

**Issue by ywk253100** [goharbor/harbor#9794]
A new configuration item `autoredirect` is introduced in docker registry: https://github.com/docker/distribution/blob/master/docs/configuration.md#token. We can use it to return the relative URL as token realm to avoid configuring the hostname/externalURL, this will reduce the complexity of configuration.

When `autoredirect` is enabled, the path of token service is fixed as `/auth/token/`, but ours is `/service/token` currently, this maybe a break change.

**Comment by ywk253100** [comment]
Another issue we should consider is that how we pass the Harbor URL to scanner to pull images. Maybe we can configure it when adding the scanner?

**Comment by reasonerjt** [comment]
We'll re-visit this to double check if the `client` supports the relative URL when fetching the token.

**Comment by reasonerjt** [comment]
This relies on how much work is needed to change the client to handle the relative url, if we can't make the change in a couple of days I hope this change can be deferred.

**Comment by reasonerjt** [comment]
The real goal for this issue is to eliminate the usage of `EXT_ENDPOINT` in `harbor-core`
Unfortunately this is not realistic, this endpoint is needed when Harbor sending webhook to notify third party about URI of resources, or trigger scanner to pull and scan images.

Per discussion I'm closing this issue as `won't fix`
