### ISSUE TITLE
http header  lost xsrf when delayed request

### ISSUE THREAD

**Issue by jwangyangls** [goharbor/harbor#9844]
![image](https://user-images.githubusercontent.com/29826789/68664529-6e6d6200-057b-11ea-817f-51775918ea34.png)
![image](https://user-images.githubusercontent.com/29826789/68664566-7f1dd800-057b-11ea-9ec2-2f8f3738a4d8.png)

**Comment by jwangyangls** [comment]
The reason for this error is: csrf has an expiration time (60min), repeated timeouts, posting a message in the page or placing a request will report a 403 error, and the return of this error is not a standard port return, resulting in an erroneous error message.

**Comment by jwangyangls** [comment]
I found that the csrf in the cookie was not updated as I continued to request it. I think this is a bug.

**Comment by ywk253100** [comment]
Did some investigation as follows:
* For Beego 1.9(used in Harbor 1.8, 1.9 and 1.10)
  * Run mode of beego: `dev`
When sending a request without XSRF token, a 403 error will be returned with error message defined here: https://github.com/astaxie/beego/blob/develop/context/context.go#L172. So maybe the frontend can check the message to decide whether redirect the user to the login page
  * Run mode of beego: `prod`
When sending the request, backend will report an error in the log but 200 will be returned as the status code. This is a bug caused by https://github.com/astaxie/beego/blob/v1.9.0/config.go#L175
* For Beego latest release: 1.12.0
  * For both `dev` and `prod` run modes, only status code 403 will be returned without any error message. If the PR https://github.com/astaxie/beego/pull/3867 can be merged, then status code 422 will be returned and the frontend can distinguish the XSRF token missing error

So for Harbor 1.8, 1.9 and 1.10, we can keep the run mode as `dev` and the frontend needs to check the 403 error message to decide whether it's a XSRF error
But after we upgrading the beego to the latest version, we need to find another way to handle this

**Comment by ywk253100** [comment]
Or we can just extend the expiration of XSRF token, such as 1 day, to reduce the possibilities of the issue

**Comment by jwangyangls** [comment]
In the front end you can handle this error, but to write some very strange code, logically this is also unreasonable.
